### ISSUE TITLE
can't  Export tf graph from onnx file due to ValueError: Dimensions must be equal

### ISSUE THREAD

**Issue by Daveorr** [onnx/onnx-tensorflow#1005]
**Describe the bug**

Hi, I'm facing the following issue and I really need some help please:

-    Can convert to pytorch to Onnx
-    Can run inference using ONNX runtime
-    Can generate Tensorflow Representation as `tf_rep = prepare(onnx_model)`
-    **CAN'T export .pb when calling `tf_rep.export_graph(out.pb')`**

FAILS  with:

`ValueError: Dimensions must be equal, but are 3072 and 96 for '{{node Add_1263}} = AddV2[T=DT_FLOAT](concat_19/concat, Add_1263/y)' with input shapes: [?,?,?,3072], [96]`.

I tried thousand of approaches but really can't succed to export .pb graph, any help, advice is more than welcome.

**To Reproduce**

```
import onnx

from onnx_tf.backend import prepare

onnx_model = onnx.load("input_path")  # load onnx model
tf_rep = prepare(onnx_model)  # prepare tf representation
tf_rep.export_graph("output_path")  # export the model  <---- IT FAILS HERE

```

**ONNX model file**

https://drive.google.com/file/d/1PfrJW_f5WoIhGiQ5eKuWespsNZ31iw31/view?usp=sharing

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.8,1 (latest)
 - ONNX version:  1.9.0 (latest from pip)
 - ONNX-TF version: 1.9.0 (latest from pip)
 - Tensorflow version: tried 2.8 and 2.7 (CPU no CUDA)

**Additional context**

I'd like to convert this to tf and then tflite (maybe wt quantization)

**Comment by ushasai** [comment]
Can you please let me know if you were able to resolve this issue?
