### ISSUE TITLE
Error while converting from onnx to tf Resize coordinate_transformation_mode=half_pixel and  mode=nearest is not supported in Tensorflow

### ISSUE THREAD

**Issue by Daveorr** [onnx/onnx-tensorflow#1006]
I'm trying to convert a model from ONNX model to TF  and I'm facing the following issue

``` 
RuntimeError: Resize coordinate_transformation_mode=half_pixel and  mode=nearest is not supported in Tensorflow.
``` 

The original model from which I've obtained the onnx model is from MXNET.

code snippet:
```
import onnx 
from onnx_tf.backend import prepare

onnx_model = onnx.load(onnx_file)
tf_rep = prepare(onnx_model, strict=True)

pb_path = "./weights/converted/exported.pb"
tf_rep.export_graph(pb_path)
```

I'm using:
```
tensorflow-addons            0.15.0   
tensorflow-gpu               2.7.0    
tensorflow-probability       0.15.0  
onnx                         1.10.2   
onnx-tf                      1.9.0    
onnxruntime                  1.10.0   
```

Anyone know how this issue con be solve?

Edit the problem seems to be from this mxnet layer layer

      "op": "UpSampling", 
      "name": "rf_c3_upsampling", 
      "attrs": {
        "num_args": "1", 
        "sample_type": "nearest", 
        "scale": "2", 
        "workspace": "512"

**Comment by chinhuang007** [comment]
Unfortunately the combination of coordinate_transformation_mode=half_pixel and mode=nearest for resize is currently not supported. The supported cases can be seen at https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status_v1_9_0.md
I am not familiar with mxnet, so just wonder if the UpSampling op could be converted into one the supported resize cases.

**Comment by Daveorr** [comment]
Yes I came to the same conclusion this morning.

I forced the conversion to use a supported case and I managed to convert the model both to tf and tflite.

Still need to check if there are regressions in terms of accuracy. I will report the results.

Thanks a lot for the answer

**Comment by HemanthSingh** [comment]
@Daveorr I have a similar problem with  coordinate_transformation_mode=half_pixel. Can you please explain how you fixed it?

**Comment by Daveorr** [comment]
so, my solution is nothing more than a dirty hack but in my case it worked and performances are kept.

As already stated while converting to TF in the resize OP the combinaytion: 

`coordinate_transformation_mode=half_pixel `and  `mode=nearest` is not supported.

So what I did was just to change the `PATH$/lib/python3.8/site-packages/onnx_tf/handlers/backend/resize.py` so when the stated condition occours instead of trwoing an error it will automatically just convert the OP using 

`Resize mode ---> linear`
`coordinate_transformation_mode ---> half_pixel`

In this way I ended up with succesful conversion and working module but obviously is not only guaranteed

**Comment by putizi-super** [comment]
> so, my solution is nothing more than a dirty hack but in my case it worked and performances are kept.
> 
> As already stated while converting to TF in the RESIZE OP the combination:
> 
> `coordinate_transformation_mode=half_pixel `and `mode=nearest` is not supported.
> 
> So what I did was just to change the `PATH$/lib/python3.8/site-packages/onnx_tf/handlers/backend/resize.py` so when the stated condition occours instead of trowing an error it will automatically just convert the OP using
> 
> `Resize mode ---> linear` `coordinate_transformation_mode ---> half_pixel`
> 
> In this way I ended up with succesful conversion and working model (also in tflite) but obviously is not always guaranteed

@Daveorr 
Can you be more specific about the solution?
