### ISSUE TITLE
Renaming `master` to `main`

### ISSUE THREAD

**Issue by kevinch-nv** [onnx/onnx-tensorflow#1007]
Hello ONNX partner,

Based on best practices at most of the ONNX member companies, the ONNX community is recommending that we rename the master branch in our repos as main.

GitHub has simplified the process as described at[ https://github.com/github/renaming](https://github.com/github/renaming). Please switch over once all dependencies are aware of the change.

Thanks!

**Comment by chinhuang007** [comment]
Renamed default to main. If you have a local clone, you can update it by running the following commands. 
```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a
```
You might need to rename the branch in your cloned repo to "main" before running the commands.

**Comment by chinhuang007** [comment]
Done!
