### ISSUE TITLE
Add clear summary of relationship to tf2onnx project at top of README.md

### ISSUE THREAD

**Issue by felker** [onnx/onnx-tensorflow#1010]
While the README has a section discussing how users should use `tf2onnx` for `tf->onnx` frontend capabilities https://github.com/onnx/onnx-tensorflow#migrating-from-onnx-tf-to-tf-onnx , it wasn't entirely clear to me (and other users, if the Issues are any indication) that this package should still be used for `onnx->tf` backend capabilities, i.e. that `tf2onnx` does not fully replace `onnx-tf`. "Migrating" possibly connotes that this package is deprecated, if a reader misses the subtle ONNX frontend vs. backend qualifier. 

Setting out the relationship between the two projects at the very top of the README in plain language, e.g. in  #422 or 
https://github.com/onnx/tensorflow-onnx/issues/1793
would be very helpful.

**Comment by chinhuang007** [comment]
Thanks for comments! A little clarification is added to the README.
