### ISSUE TITLE
No module named 'tensorflow_probability'

### ISSUE THREAD

**Issue by JinXiaozhao** [onnx/onnx-tensorflow#1015]
**Describe the bug**

from onnx_tf.backend import prepare
  File "/usr/local/lib/python3.6/dist-packages/onnx_tf/__init__.py", line 1, in <module>
    from . import backend
  File "/usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py", line 28, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "/usr/local/lib/python3.6/dist-packages/onnx_tf/common/handler_helper.py", line 3, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "/usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend/bernoulli.py", line 2, in <module>
    from tensorflow_probability import distributions as tfd
ModuleNotFoundError: No module named 'tensorflow_probability'

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.6.9
 - ONNX version: 1.10
 - ONNX-TF version:1.10
 - Tensorflow version: 2.6.2

**Comment by kikoland** [comment]
I suggest you try: pip install tensorflow-probability

**Comment by chudegao** [comment]
@JinXiaozhao , as suggested as @kikoland , you need to install TensorFlow >= 2.8.0, tensorflow-probability and tensorflow-addons by yourself. The installation steps should be updated in Readme.

**Comment by vonschultz** [comment]
I don't understand, @chudegao. `tensorflow_addons` is mentioned in the `install_requires` in `setup.py`, which seems like the nice way to do it. Why not do it that way for `tensorflow-probability` too? Shouldn't the package declare the dependencies it has in `install_requires`? Why treat `tensorflow-probability` any different from `tensorflow_addons`?

**Comment by chudegao** [comment]
Yes. You are right. It should be add in the install_requires. Would you like create a PR for it? Otherwise I will create one for it.

**Comment by Vozf** [comment]
For tf 2.7.0 this helped
```
pip install tensorflow-probability==0.15.0
```
for tf >= 2.8.0  tensorflow-probability==0.16.0 should help
