### ISSUE TITLE
Adds training (gradient) pass

### ISSUE THREAD

**Issue by AtuNuka** [onnx/onnx-tensorflow#105]
Hi,

I'm interested to train ONNX model on TensorFlow.
However this project supports only inference pass (forward pass) for now.

I know that ONNX supports only inference ops now.
I also know that ONNX is going to support training ops in future.
https://github.com/onnx/onnx/wiki/%5BAnnouncement%5D-ONNX-working-groups-established#training
So, the converter must make gradient graphs from inference graphs for now.

Is there any schedule for supporting training pass (gradient pass) in future?
And adding training pass is contribution welcomed?

Thanks

**Comment by fumihwh** [comment]
@AtuNuka 
As ONNX training support is under discussion, I think we should not go too far.
Of course, we will work on it when ONNX side is landed.

**Comment by AtuNuka** [comment]
@fumihwh 

Thanks for your fast reply. OK,  I will wait ONNX side too, and continue checking the ONNX side.
