### ISSUE TITLE
Variable length input 

### ISSUE THREAD

**Issue by thatindiandude** [onnx/onnx-tensorflow#130]
We've been using ONNX-Tensorflow to convert an RNN-based model that consumes variable length input. 

When the model is converted to TF, the consumed example `input` from the `torch._export(model, (input, input_lengths)...)` call will have its own `input_length` parameter, but this variable depending on the longest sequence length in the batch currently being consumed by the model. 

Thus, we'd like ONNX-TF to be smart enough to know how to parameterize the dimensions of intermediary layers so that it avoids needing fixed dimensions for individual operators. Dynamic RNNs in Tensorflow are flexible enough to avoid fixed dimensions, but converting to a `tf.slice` operator with parameters such as the following in `onnx-tensorflow/backends/backend_v1.py:handle_slice()`:

```return [tf.slice(input_dict[node.inputs[0]], tf.constant(full_begin), tf.constant(full_sizes))``` 

where `full_sizes = [None, 32, 55, None]`. 

`tf.constant` cannot handle `None` elements , and I'm not entirely sure that `tf.slice` would know what to do with `None`.

**Comment by fumihwh** [comment]
@thatindiandude 
I've add two PRs to fix this.
BTW, as we can not check if starts and ends is valid for shape [None, 30, 30, None],
there is a constraint, if inputs could be [5, 30, 30, 10], [10, 30, 30, 15], [15, 30, 30, 20]
when full_begin=[0, 0, 0, 0], full_sizes should be min_input_shape by all axes, says [<=5, <=30, <=30, <=10]

**Comment by fumihwh** [comment]
Fixed.
