### ISSUE TITLE
Error in `python': free(): invalid pointer: 0x00007fbbe8b1a520

### ISSUE THREAD

**Issue by cl5220418** [onnx/onnx-tensorflow#138]
I ran the code 'test_model_large_stepping.py' in the example and reported the following error. What should I do? Thank you for your rely!!

`*** Error in `python': free(): invalid pointer: 0x00007fbbe8b1a520 ***
======= Backtrace: =========
/lib/x86_64-linux-gnu/libc.so.6(+0x777e5)[0x7fbbf44077e5]
/lib/x86_64-linux-gnu/libc.so.6(+0x8037a)[0x7fbbf441037a]
/lib/x86_64-linux-gnu/libc.so.6(cfree+0x4c)[0x7fbbf441453c]
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(_ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE+0x142)[0x7fbbe8817a02]
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(_ZNSt6locale5_ImplC1Em+0x1e3)[0x7fbbe8815ad3]
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(_ZNSt6locale18_S_initialize_onceEv+0x15)[0x7fbbe8816a45]
/lib/x86_64-linux-gnu/libpthread.so.0(+0xea99)[0x7fbbf5080a99]
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(_ZNSt6locale13_S_initializeEv+0x21)[0x7fbbe8816a91]
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(_ZNSt6localeC1Ev+0x13)[0x7fbbe8816ad3]
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(_ZNSt8ios_base4InitC2Ev+0xbc)[0x7fbbe8817d4c]
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(+0x103840)[0x7fbbe8673840]
/lib64/ld-linux-x86-64.so.2(+0x106ba)[0x7fbbf578f6ba]
/lib64/ld-linux-x86-64.so.2(+0x107cb)[0x7fbbf578f7cb]
/lib64/ld-linux-x86-64.so.2(+0x158e2)[0x7fbbf57948e2]
/lib64/ld-linux-x86-64.so.2(+0x10564)[0x7fbbf578f564]
/lib64/ld-linux-x86-64.so.2(+0x14da9)[0x7fbbf5793da9]
/lib/x86_64-linux-gnu/libdl.so.2(+0xf09)[0x7fbbf4e6ef09]
/lib64/ld-linux-x86-64.so.2(+0x10564)[0x7fbbf578f564]
/lib/x86_64-linux-gnu/libdl.so.2(+0x1571)[0x7fbbf4e6f571]
/lib/x86_64-linux-gnu/libdl.so.2(dlopen+0x31)[0x7fbbf4e6efa1]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(_PyImport_FindSharedFuncptr+0x73)[0x7fbbf54116a3]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(_PyImport_LoadDynamicModuleWithSpec+0x147)[0x7fbbf53ece97]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x15acaf)[0x7fbbf53e9caf]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyCFunction_Call+0xf9)[0x7fbbf534b5e9]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x6ba0)[0x7fbbf53d07c0]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7fbbf53d3b49]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x91d5)[0x7fbbf53d2df5]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7fbbf53d3166]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7fbbf53d3166]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7fbbf53d3166]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7fbbf53d3166]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7fbbf53d3b49]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x48)[0x7fbbf53d3cd8]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x9a542)[0x7fbbf5329542]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyObject_Call+0x56)[0x7fbbf52f6236]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(_PyObject_CallMethodIdObjArgs+0xf8)[0x7fbbf52f9098]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyImport_ImportModuleLevelObject+0x403)[0x7fbbf53eaef3]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x13872f)[0x7fbbf53c772f]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyCFunction_Call+0x131)[0x7fbbf534b621]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x6ba0)[0x7fbbf53d07c0]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7fbbf53d3b49]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x91d5)[0x7fbbf53d2df5]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7fbbf53d3166]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7fbbf53d3b49]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x48)[0x7fbbf53d3cd8]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x9a542)[0x7fbbf5329542]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyObject_Call+0x56)[0x7fbbf52f6236]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(_PyObject_CallMethodIdObjArgs+0xf8)[0x7fbbf52f9098]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyImport_ImportModuleLevelObject+0x403)[0x7fbbf53eaef3]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x13872f)[0x7fbbf53c772f]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyCFunction_Call+0x131)[0x7fbbf534b621]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyObject_Call+0x56)[0x7fbbf52f6236]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_CallObjectWithKeywords+0x43)[0x7fbbf53c81b3]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x4f88)[0x7fbbf53ceba8]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7fbbf53d3b49]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalCodeEx+0x48)[0x7fbbf53d3cd8]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalCode+0x3b)[0x7fbbf53d3d1b]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x137dfe)[0x7fbbf53c6dfe]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyCFunction_Call+0xf9)[0x7fbbf534b5e9]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x6ba0)[0x7fbbf53d07c0]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(+0x144b49)[0x7fbbf53d3b49]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x91d5)[0x7fbbf53d2df5]
/home/cl/anaconda3/bin/../lib/libpython3.5m.so.1.0(PyEval_EvalFrameEx+0x9546)[0x7fbbf53d3166]
======= Memory map: ========
00400000-00401000 r-xp 00000000 08:01 1595318                            /home/cl/anaconda3/bin/python3.5
00601000-00602000 rw-p 00001000 08:01 1595318                            /home/cl/anaconda3/bin/python3.5
01acb000-022ce000 rw-p 00000000 00:00 0                                  [heap]
7fbbe4000000-7fbbe4021000 rw-p 00000000 00:00 0 
7fbbe4021000-7fbbe8000000 ---p 00000000 00:00 0 
7fbbe8570000-7fbbe88f2000 r-xp 00000000 08:01 667938                     /home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so
7fbbe88f2000-7fbbe8af1000 ---p 00382000 08:01 667938                     /home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so
7fbbe8af1000-7fbbe8b06000 rw-p 00381000 08:01 667938                     /home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so
7fbbe8b06000-7fbbe8b5c000 rw-p 00000000 00:00 0 
7fbbe8b5c000-7fbbe8b60000 r-xp 00000000 08:01 267737                     /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7fbbe8b60000-7fbbe8d5f000 ---p 00004000 08:01 267737                     /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7fbbe8d5f000-7fbbe8d60000 r--p 00003000 08:01 267737                     /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7fbbe8d60000-7fbbe8d61000 rw-p 00004000 08:01 267737                     /lib/x86_64-linux-gnu/libuuid.so.1.3.0
7fbbe8d61000-7fbbe901c000 r-xp 00000000 08:01 1602591                    /home/cl/anaconda3/lib/libprotobuf.so.15.0.1
7fbbe901c000-7fbbe921b000 ---p 002bb000 08:01 1602591                    /home/cl/anaconda3/lib/libprotobuf.so.15.0.1
7fbbe921b000-7fbbe922b000 rw-p 002ba000 08:01 1602591                    /home/cl/anaconda3/lib/libprotobuf.so.15.0.1
7fbbe922b000-7fbbe922d000 rw-p 00000000 00:00 0 
7fbbe922d000-7fbbe926e000 r-xp 00000000 08:01 1601632                    /home/cl/anaconda3/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so
7fbbe926e000-7fbbe946e000 ---p 00041000 08:01 1601632                    /home/cl/anaconda3/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so
7fbbe946e000-7fbbe9474000 rw-p 00041000 08:01 1601632                    /home/cl/anaconda3/lib/python3.5/site-packages/google/protobuf/pyext/_message.cpython-35m-x86_64-linux-gnu.so
7fbbe9474000-7fbbe9485000 r-xp 00000000 08:01 1603438                    /home/cl/anaconda3/lib/libgcc_s.so.1
7fbbe9485000-7fbbe9684000 ---p 00011000 08:01 1603438                    /home/cl/anaconda3/lib/libgcc_s.so.1
7fbbe9684000-7fbbe9685000 r--p 00010000 08:01 1603438                    /home/cl/anaconda3/lib/libgcc_s.so.1
7fbbe9685000-7fbbe9686000 rw-p 00011000 08:01 1603438                    /home/cl/anaconda3/lib/libgcc_s.so.1
7fbbe9686000-7fbbe97b0000 r-xp 00000000 08:01 1603575                    /home/cl/anaconda3/lib/libstdc++.so.6.0.24
7fbbe97b0000-7fbbe99af000 ---p 0012a000 08:01 1603575                    /home/cl/anaconda3/lib/libstdc++.so.6.0.24
7fbbe99af000-7fbbe99b9000 r--p 00129000 08:01 1603575                    /home/cl/anaconda3/lib/libstdc++.so.6.0.24
7fbbe99b9000-7fbbe99bd000 rw-p 00133000 08:01 1603575                    /home/cl/anaconda3/lib/libstdc++.so.6.0.24
7fbbe99bd000-7fbbe99c0000 rw-p 00000000 00:00 0 
7fbbe99c0000-7fbbe99c1000 r-xp 00000000 08:01 1601631                    /home/cl/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/_api_implementation.cpython-35m-x86_64-linux-gnu.so
7fbbe99c1000-7fbbe9bc0000 ---p 00001000 08:01 1601631                    /home/cl/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/_api_implementation.cpython-35m-x86_64-linux-gnu.so
7fbbe9bc0000-7fbbe9bc1000 rw-p 00000000 08:01 1601631                    /home/cl/anaconda3/lib/python3.5/site-packages/google/protobuf/internal/_api_implementation.cpython-35m-x86_64-linux-gnu.so
7fbbe9bc1000-7fbbe9e01000 rw-p 00000000 00:00 0 
7fbbe9e01000-7fbbe9e02000 r-xp 00000000 08:01 1749284                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_opcode.so
7fbbe9e02000-7fbbea001000 ---p 00001000 08:01 1749284                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_opcode.so
7fbbea001000-7fbbea002000 rw-p 00000000 08:01 1749284                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_opcode.so
7fbbea002000-7fbbea082000 rw-p 00000000 00:00 0 
7fbbea082000-7fbbea091000 r-xp 00000000 08:01 1749291                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_socket.so
7fbbea091000-7fbbea291000 ---p 0000f000 08:01 1749291                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_socket.so
7fbbea291000-7fbbea296000 rw-p 0000f000 08:01 1749291                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_socket.so
7fbbea296000-7fbbea2d6000 rw-p 00000000 00:00 0 
7fbbea2d6000-7fbbea30a000 r-xp 00000000 08:01 1749311                    /home/cl/anaconda3/lib/python3.5/lib-dynload/pyexpat.so
7fbbea30a000-7fbbea50a000 ---p 00034000 08:01 1749311                    /home/cl/anaconda3/lib/python3.5/lib-dynload/pyexpat.so
7fbbea50a000-7fbbea50e000 rw-p 00034000 08:01 1749311                    /home/cl/anaconda3/lib/python3.5/lib-dynload/pyexpat.so
7fbbea50e000-7fbbea54e000 rw-p 00000000 00:00 0 
7fbbea54e000-7fbbea553000 r-xp 00000000 08:01 1749314                    /home/cl/anaconda3/lib/python3.5/lib-dynload/select.so
7fbbea553000-7fbbea752000 ---p 00005000 08:01 1749314                    /home/cl/anaconda3/lib/python3.5/lib-dynload/select.so
7fbbea752000-7fbbea754000 rw-p 00004000 08:01 1749314                    /home/cl/anaconda3/lib/python3.5/lib-dynload/select.so
7fbbea754000-7fbbea757000 r-xp 00000000 08:01 1749286                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_posixsubprocess.so
7fbbea757000-7fbbea956000 ---p 00003000 08:01 1749286                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_posixsubprocess.so
7fbbea956000-7fbbea957000 rw-p 00002000 08:01 1749286                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_posixsubprocess.so
7fbbea957000-7fbbea95d000 r-xp 00000000 08:01 1749320                    /home/cl/anaconda3/lib/python3.5/lib-dynload/zlib.so
7fbbea95d000-7fbbeab5d000 ---p 00006000 08:01 1749320                    /home/cl/anaconda3/lib/python3.5/lib-dynload/zlib.so
7fbbeab5d000-7fbbeab5f000 rw-p 00006000 08:01 1749320                    /home/cl/anaconda3/lib/python3.5/lib-dynload/zlib.so
7fbbeab5f000-7fbbeab7b000 r-xp 00000000 08:01 1602436                    /home/cl/anaconda3/lib/libz.so.1.2.11
7fbbeab7b000-7fbbead7b000 ---p 0001c000 08:01 1602436                    /home/cl/anaconda3/lib/libz.so.1.2.11
7fbbead7b000-7fbbead7c000 rw-p 0001c000 08:01 1602436                    /home/cl/anaconda3/lib/libz.so.1.2.11
7fbbead7c000-7fbbead81000 r-xp 00000000 08:01 1749302                    /home/cl/anaconda3/lib/python3.5/lib-dynload/binascii.so
7fbbead81000-7fbbeaf81000 ---p 00005000 08:01 1749302                    /home/cl/anaconda3/lib/python3.5/lib-dynload/binascii.so
7fbbeaf81000-7fbbeaf82000 rw-p 00005000 08:01 1749302                    /home/cl/anaconda3/lib/python3.5/lib-dynload/binascii.so
7fbbeaf82000-7fbbeb082000 rw-p 00000000 00:00 0 
7fbbeb082000-7fbbeb13d000 r-xp 00000000 08:01 1865682                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/random/mtrand.cpython-35m-x86_64-linux-gnu.so
7fbbeb13d000-7fbbeb33d000 ---p 000bb000 08:01 1865682                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/random/mtrand.cpython-35m-x86_64-linux-gnu.so
7fbbeb33d000-7fbbeb362000 rw-p 000bb000 08:01 1865682                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/random/mtrand.cpython-35m-x86_64-linux-gnu.so
7fbbeb362000-7fbbeb3a4000 rw-p 00000000 00:00 0 
7fbbeb3a4000-7fbbeb3ad000 r-xp 00000000 08:01 1758019                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/fft/fftpack_lite.cpython-35m-x86_64-linux-gnu.so
7fbbeb3ad000-7fbbeb5ac000 ---p 00009000 08:01 1758019                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/fft/fftpack_lite.cpython-35m-x86_64-linux-gnu.so
7fbbeb5ac000-7fbbeb5ad000 rw-p 00008000 08:01 1758019                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/fft/fftpack_lite.cpython-35m-x86_64-linux-gnu.so
7fbbeb5ad000-7fbbeb5ed000 rw-p 00000000 00:00 0 
7fbbeb5ed000-7fbbeb638000 r-xp 00000000 08:01 1749274                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_decimal.so
7fbbeb638000-7fbbeb838000 ---p 0004b000 08:01 1749274                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_decimal.so
7fbbeb838000-7fbbeb841000 rw-p 0004b000 08:01 1749274                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_decimal.so
7fbbeb841000-7fbbeb86a000 r-xp 00000000 08:01 1865679                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
7fbbeb86a000-7fbbeba69000 ---p 00029000 08:01 1865679                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
7fbbeba69000-7fbbeba6e000 rw-p 00028000 08:01 1865679                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/linalg/_umath_linalg.cpython-35m-x86_64-linux-gnu.so
7fbbeba6e000-7fbbeba72000 r-xp 00000000 08:01 1865642                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
7fbbeba72000-7fbbebc72000 ---p 00004000 08:01 1865642                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
7fbbebc72000-7fbbebc75000 rw-p 00004000 08:01 1865642                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/linalg/lapack_lite.cpython-35m-x86_64-linux-gnu.so
7fbbebc75000-7fbbebdb6000 rw-p 00000000 00:00 0 
7fbbebdb6000-7fbbebdb9000 r-xp 00000000 08:01 1749287                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_random.so
7fbbebdb9000-7fbbebfb8000 ---p 00003000 08:01 1749287                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_random.so
7fbbebfb8000-7fbbebfb9000 rw-p 00002000 08:01 1749287                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_random.so
7fbbebfb9000-7fbbec1cf000 r-xp 00000000 08:01 1968906                    /home/cl/anaconda3/lib/libcrypto.so.1.0.0
7fbbec1cf000-7fbbec3ce000 ---p 00216000 08:01 1968906                    /home/cl/anaconda3/lib/libcrypto.so.1.0.0
7fbbec3ce000-7fbbec3ea000 r--p 00215000 08:01 1968906                    /home/cl/anaconda3/lib/libcrypto.so.1.0.0
7fbbec3ea000-7fbbec3f5000 rw-p 00231000 08:01 1968906                    /home/cl/anaconda3/lib/libcrypto.so.1.0.0
7fbbec3f5000-7fbbec3f9000 rw-p 00000000 00:00 0 
7fbbec3f9000-7fbbec465000 r-xp 00000000 08:01 1606243                    /home/cl/anaconda3/lib/libssl.so.1.0.0
7fbbec465000-7fbbec664000 ---p 0006c000 08:01 1606243                    /home/cl/anaconda3/lib/libssl.so.1.0.0
7fbbec664000-7fbbec669000 r--p 0006b000 08:01 1606243                    /home/cl/anaconda3/lib/libssl.so.1.0.0
7fbbec669000-7fbbec66f000 rw-p 00070000 08:01 1606243                    /home/cl/anaconda3/lib/libssl.so.1.0.0
7fbbec66f000-7fbbec674000 r-xp 00000000 08:01 1749276                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_hashlib.so
7fbbec674000-7fbbec874000 ---p 00005000 08:01 1749276                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_hashlib.so
7fbbec874000-7fbbec875000 rw-p 00005000 08:01 1749276                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_hashlib.so
7fbbec875000-7fbbec899000 r-xp 00000000 08:01 666461                     /home/cl/anaconda3/lib/liblzma.so.5.2.2
7fbbec899000-7fbbeca99000 ---p 00024000 08:01 666461                     /home/cl/anaconda3/lib/liblzma.so.5.2.2
7fbbeca99000-7fbbeca9a000 rw-p 00024000 08:01 666461                     /home/cl/anaconda3/lib/liblzma.so.5.2.2
7fbbeca9a000-7fbbecaa0000 r-xp 00000000 08:01 1749280                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_lzma.so
7fbbecaa0000-7fbbecca0000 ---p 00006000 08:01 1749280                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_lzma.so
7fbbecca0000-7fbbecca2000 rw-p 00006000 08:01 1749280                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_lzma.so
7fbbecca2000-7fbbeccb3000 r-xp 00000000 08:01 1749260                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_bz2.so
7fbbeccb3000-7fbbeceb3000 ---p 00011000 08:01 1749260                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_bz2.so
7fbbeceb3000-7fbbeceb5000 rw-p 00011000 08:01 1749260                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_bz2.so
7fbbeceb5000-7fbbeceb7000 r-xp 00000000 08:01 1749305                    /home/cl/anaconda3/lib/python3.5/lib-dynload/grp.so
7fbbeceb7000-7fbbed0b7000 ---p 00002000 08:01 1749305                    /home/cl/anaconda3/lib/python3.5/lib-dynload/grp.so
7fbbed0b7000-7fbbed0b8000 rw-p 00002000 08:01 1749305                    /home/cl/anaconda3/lib/python3.5/lib-dynload/grp.so
7fbbed0b8000-7fbbed138000 rw-p 00000000 00:00 0 
7fbbed138000-7fbbed14f000 r-xp 00000000 08:01 1749285                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_pickle.so
7fbbed14f000-7fbbed34f000 ---p 00017000 08:01 1749285                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_pickle.so
7fbbed34f000-7fbbed353000 rw-p 00017000 08:01 1749285                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_pickle.so
7fbbed353000-7fbbed3d3000 rw-p 00000000 00:00 0 
7fbbed3d3000-7fbbed3f3000 r-xp 00000000 08:01 1749269                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_ctypes.so
7fbbed3f3000-7fbbed5f2000 ---p 00020000 08:01 1749269                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_ctypes.so
7fbbed5f2000-7fbbed5f7000 rw-p 0001f000 08:01 1749269                    /home/cl/anaconda3/lib/python3.5/lib-dynload/_ctypes.so
7fbbed5f7000-7fbbed677000 rw-p 00000000 00:00 0 
7fbbed677000-7fbbed808000 r-xp 00000000 08:01 1618002                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/core/umath.cpython-35m-x86_64-linux-gnu.so
7fbbed808000-7fbbeda08000 ---p 00191000 08:01 1618002                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/core/umath.cpython-35m-x86_64-linux-gnu.so
7fbbeda08000-7fbbeda0e000 rw-p 00191000 08:01 1618002                    /home/cl/anaconda3/lib/python3.5/site-packages/numpy/core/umath.cpython-35m-x86_64-linux-gnu.so
7fbbeda0e000-7fbbeda10000 rw-p 00000000 00:00 0 Aborted (core dumped)
`

**Comment by fumihwh** [comment]
@cl5220418 
I can't reproduce your problem. The suggestion I could give is clean up your environment and compile caffe2 again.

**Comment by tjingrant** [comment]
Also looking at the 4th line of stacktrace:
/home/cl/anaconda3/lib/python3.5/site-packages/onnx/onnx_cpp2py_export.cpython-35m-x86_64-linux-gnu.so(_ZNSt6locale5_Impl16_M_install_facetEPKNS_2idEPKNS_5facetE+0x142)[0x7fbbe8817a02]

It doesn't seem to be an onnx-tensorflow issue.
