### ISSUE TITLE
Missing "ArgMax" operator in frontend_tf_opset_version 

### ISSUE THREAD

**Issue by greenwaves** [onnx/onnx-tensorflow#147]
Hi, I'm trying to convert a TF cifar10 graph to ONNX graph and I'm missing the ArgMax operator in the frontend_tf_opset_version in file opset_version.py. 

$ python tf2onnx.py 
DDDD Operand Name
Identity
DDDD Operand Name
Identity
DDDD Operand Name
Conv2D
DDDD Operand Name
Add
DDDD Operand Name
MaxPool
DDDD Operand Name
Identity
DDDD Operand Name
Identity
DDDD Operand Name
Conv2D
DDDD Operand Name
Add
DDDD Operand Name
MaxPool
DDDD Operand Name
Reshape
DDDD Operand Name
Identity
DDDD Operand Name
Identity
DDDD Operand Name
MatMul
DDDD Operand Name
Add
DDDD Operand Name
Relu
DDDD Operand Name
Softmax
DDDD Operand Name
ArgMax
Traceback (most recent call last):
  File "tf2onnx.py", line 16, in <module>
    onnx_graph=convert_graph(graph_def=tf_graph, output="prediction/y_output", name="cifar10")
  File "/home/corine_lamagdeleine/onnx-tensorflow/onnx_tf/frontend.py", line 222, in tensorflow_graph_to_onnx_graph
    versions = frontend_tf_opset_version[op_name_to_lower(op_name)]
KeyError: u'arg_max'

Any body knows where I can implement this conversion function?

Greenwaves.

**Comment by fumihwh** [comment]
Merged
