### ISSUE TITLE
ImportError: cannot import name 'tensorflow_graph_to_onnx_model'

### ISSUE THREAD

**Issue by cl5220418** [onnx/onnx-tensorflow#153]
When I run the following ‘OnnxTensorflowExport’ code, I get ImportError: cannot import name 'tensorflow_graph_to_onnx_model'. What should I do? Thanks!

`import tensorflow as tf
import onnx_tf.frontend
from onnx_tf.frontend import tensorflow_graph_to_onnx_model

with tf.gfile.GFile("frozen_graph.pb", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                     "fc2/add",
                                     opset=6)
    file = open("mnist.onnx", "wb")
    file.write(onnx_model.SerializeToString())
    file.close()
`

**Comment by tjingrant** [comment]
@cl5220418 as @fumihwh pointed out, can you tell us more about how you installed the package?

**Comment by cl5220418** [comment]
I got another error,  TypeError: make_graph() got an unexpected keyword argument 'value_info'

> Traceback (most recent call last):
  File "OnnxTensorflowExport.py", line 9, in <module>
    "fc2/add")
  File "/home/cl/onnx/onnx-tensorflow/onnx_tf/frontend.py", line 337, in tensorflow_graph_to_onnx_model
    opset, graph_name)
  File "/home/cl/onnx/onnx-tensorflow/onnx_tf/frontend.py", line 291, in tensorflow_graph_to_onnx_graph
    value_info=value_info_proto)
TypeError: make_graph() got an unexpected keyword argument 'value_info'
