### ISSUE TITLE
TypeError: make_graph() got an unexpected keyword argument 'value_info'

### ISSUE THREAD

**Issue by cl5220418** [onnx/onnx-tensorflow#158]
> Traceback (most recent call last):
File "OnnxTensorflowExport.py", line 9, in 
"fc2/add")
File "/home/cl/onnx/onnx-tensorflow/onnx_tf/frontend.py", line 337, in tensorflow_graph_to_onnx_model
opset, graph_name)
File "/home/cl/onnx/onnx-tensorflow/onnx_tf/frontend.py", line 291, in tensorflow_graph_to_onnx_graph
value_info=value_info_proto)
TypeError: make_graph() got an unexpected keyword argument 'value_info'

**Comment by fumihwh** [comment]
Upgrade your onnx.

**Comment by cl5220418** [comment]
It still doesn't work.

**Comment by fumihwh** [comment]
Please provide more information about problem you are facing.
`value_info` has been added from Apr 6, 2018.
Current master: https://github.com/onnx/onnx/blob/master/onnx/helper.py#L55
Make sure you are working with onnx after Apr 6, 2018.

**Comment by tjingrant** [comment]
Please give our latest release a try here: https://pypi.org/project/onnx-tf/. I believe this issue has been properly resolved.
