### ISSUE TITLE
Updates necessary for newly added test cases

### ISSUE THREAD

**Issue by dzhulgakov** [onnx/onnx-tensorflow#17]
We're shooting for ONNX v1 announcement at NIPS next week and thus it'd be awesome to make sure that all tests are passing with the latest ONNX master.

We added a few backend test cases upstream in ONNX (by exporting some of the PyTorch's tests) and some of them are not passing the tests in TF converter. Those tests do pass Caffe2 backend but they might still contain deviations from the spec. If you find some discrepancies - let us know.

I haven't dug into details yet, but it seems that there are some shape mismatches from looking at the contbuild.

@tjingrant  - would you be able to take a look?

**Comment by tjingrant** [comment]
Hi @dzhulgakov, thanks for the heads-up.
Yep, we are aware of the NIPS event and will definitely try our best to make sure they pass the tests.

**Comment by tjingrant** [comment]
Please take a look at this updated backend test file: https://github.com/onnx/onnx-tensorflow/blob/4b04a94bca9a893fa69c7fc1967782218c2a8760/test/backend/onnx_backend_test.py

Reasons of exclusion are commented right near the exclusion.
