### ISSUE TITLE
Cannot import tf inception into caffe2

### ISSUE THREAD

**Issue by lburzawa** [onnx/onnx-tensorflow#175]
Hi, I am having trouble importing a inception v3 converted from tensorflow-slim through onnx-tf into caffe2. I get error: "onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: out_type | Context: Bad node spec: input: "InceptionV3/Logits/SpatialSqueeze" output: "InceptionV3/Predictions/Shape" name: "InceptionV3/Predictions/Shape" op_type: "Shape" attribute { name: "out_type" i: 3 type: INT }". Where does "out_type" come from? It does not look like ONNX operator "Shape" has such an attribute.

 - Python version: 3.5
 - ONNX version: master
 - ONNX-TF version: master
 - Tensorflow version: 1.8

**Comment by fumihwh** [comment]
`out_type` comes from [tf.shape](https://www.tensorflow.org/api_docs/python/tf/shape)
We need to remove it from tf attr when converting.

**Comment by fumihwh** [comment]
@lburzawa 
I created some PRs and you can take them to check if it works.

**Comment by lburzawa** [comment]
Thanks a lot, that fixed it. However now I am getting "RuntimeError: Inferred shape and existing shape differ in dimension 1: (32) vs (149)" . ONNX specifies that input for a Conv should be in format NxCxHxW while weights should be in format MxCxkHxkW. I believe that tf inception was exported to have input format NxHxWxC and weights format kHxkWxCxM. Could this be an issue?

**Comment by tjingrant** [comment]
That's a known limitation we are actively working on. Basically ONNX community considers NHWC a heresy (thus refuse to incorporate any NHWC support) and we have to come up with convoluted workaround to bridge such a gap; but we are getting there.
