### ISSUE TITLE
Cut a release matching onnx-v1

### ISSUE THREAD

**Issue by dzhulgakov** [onnx/onnx-tensorflow#18]
We're shooting for ONNX v1 announcement at NIPS next week and it makes sense to produce matching artifacts to PyPI. The branch is at https://github.com/onnx/onnx/tree/rel-1.0 and even though some secondary tests are failing (#17) the original set of model tests does pass.

This is just a heads up. Would you be able to help cut the release early next week (by Dec 5th).

**Comment by tjingrant** [comment]
Yes, of course.

**Comment by tjingrant** [comment]
Just updated our PyPi package.
