### ISSUE TITLE
NotImplementedError: StridedSlice op is not implemented

### ISSUE THREAD

**Issue by dli2016** [onnx/onnx-tensorflow#207]
I am a newer for onnx and tensorflow, and also onnx-tensorflow. While I try to export a tensorflow model ([faster-rcnn-tf](https://github.com/dli2016/Faster-RCNN_TF/tree/python3), VGGnet_test) to onnx based on the suggestions in page:
https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowExport.ipynb
However I meet the error 'NotImplementedError: StridedSlice op is not implemented'  reported in frontend.py. Is there any way to resolve it? Thanks!

I use 'onnx_tf-1.1.1-py3.6' in my experiments.

**Comment by fumihwh** [comment]
There is two way if you want to run converted onnx pb with other backend:
- implement StridedSlice op in onnx-tensorflow frontend (recommend)
- implement StridedSlice op in other backend

else, use `ignore_implemented` to skip StridedSlice op.

**Comment by dli2016** [comment]
Thanks for your answer! 

However, I meet some other problems when `ignore_unimplemented`:
`The handle_reshape in onnx_tf/frontends/frontend_v1.py: assert node.inputs[1] in consts.keys()`
And I find:
`Reshape/shape; Reshape_1/shape; rpn_cls_prob/shape; Reshape_2/shape`
are not in `consts.keys()`.

I don't know the reasons caused the aforementioned issues. Or as you suggest that I need implement some source codes to achieve my purpose.

**Comment by fumihwh** [comment]
So in your source, shape is not a const (`tf.reshape(x, [1, 2, 3, 4])`), right? 
If could, try install onnx-tensorflow from souce. I refactored frontend just few days ago.

**Comment by dli2016** [comment]
Thanks a lot, I will have a try!

**Comment by dli2016** [comment]
I tried to install onnx-tensorflow from source. For one hand, the tensorflow 1.8 is necessary for the new onnx-tensorflow code. For the other, a error appear when I covert the frozen graph:

 `in onnx-tensorflow/onnx_tf/common/data_type.py, when mapping.NP_TYPE_TO_TENSOR_TYPE[np.dtype(tf_dype.as_numpy_dtype)]: KeyError: dtype('O')`. 

It seems that `<dtype: 'String'>` is not supported in current onnx? 
`TENSOR_TYPE_TO_NP_TYPE = {
    TensorProto.FLOAT: np.dtype('float32'),
    TensorProto.UINT8: np.dtype('uint8'),
    TensorProto.INT8: np.dtype('int8'),
    TensorProto.UINT16: np.dtype('uint16'),
    TensorProto.INT16: np.dtype('int16'),
    TensorProto.INT32: np.dtype('int32'),
    TensorProto.INT64: np.dtype('int64'),
    TensorProto.BOOL: np.dtype('bool'),
    TensorProto.FLOAT16: np.dtype('float16'),
    TensorProto.DOUBLE: np.dtype('float64'),
    TensorProto.COMPLEX64: np.dtype('complex64'),
    TensorProto.COMPLEX128: np.dtype('complex128'),
    TensorProto.UINT32: np.dtype('uint32'),
    TensorProto.UINT64: np.dtype('uint64'),
}

NP_TYPE_TO_TENSOR_TYPE = {v: k for k, v in TENSOR_TYPE_TO_NP_TYPE.items()}`

**Comment by fumihwh** [comment]
@dli2016 It's a onnx-tensorflow bug when deal with `dtype=string`. I will take a look of this. Thanks.

**Comment by dli2016** [comment]
@fumihwh Thanks for the quick reply. Look forward to using the latest code.

**Comment by fumihwh** [comment]
@dli2016 Could you tell me which op needs dtype string?

**Comment by dli2016** [comment]
@fumihwh I got the node op and node name using following code in `onnx-tensorflow/onnx_tf/frontend.py`:
```
for node in graph_def.node:
        print(node.name)
        print(node.op)
        new_nd = TensorflowNode(node)
```
It shows me that the node op is `Const` and node name is `PyFunc/input_3`. I don't know if I got the correct information. Hope that is useful to you, thanks!

**Comment by dli2016** [comment]
@fumihwh Hi~Is the bug fixed? Or other problems led to the issue? Thanks!

**Comment by fumihwh** [comment]
Actually, string is not supported in ONNX yet. 
It's better if you could remove node using string. But I see your input is `PyFunc/input_3`. Maybe it's hard to remove it.....

**Comment by dli2016** [comment]
@fumihwh OK, I see, thanks a lot!
