### ISSUE TITLE
Frontend support

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx-tensorflow#22]
Hi,
I just would know if you plan to develop more complete Frontend of TF (TF -> ONNX) ?
With some tests and examples.

**Comment by tjingrant** [comment]
Yes, of course. We are actively working on the frontend, but now the frontend is only preliminary thus we did not mention it in our documentation. Support for new ops are being added every week. Soon we plan to support most vision-based DL models.

**Comment by LucasMahieu** [comment]
Really thanks for your quick reply.
Would you be interested to get helped to improve the frontend ?

**Comment by tjingrant** [comment]
Absolutely. PRs are always welcome, but if you are working on something big, please let us know in advance what you'll be working on to avoid conflicts.

**Comment by LucasMahieu** [comment]
@tjingrant I let you an email on your private mail address to have more information about the frontend project.

**Comment by LucasMahieu** [comment]
@tjingrant I think we should implement the convolution and polling ops in order to be able to process entire networks like GoogLeNet. What do you think bout that ?

**Comment by tjingrant** [comment]
Conv and Pooling sound like the perfect thing to do!

As for your question regarding tf.Variable, take a look here: https://www.tensorflow.org/extend/tool_developers/#freezing.

As a starter, I think we can require user to freeze the graph and get rid of the variables before exporting to ONNX .

**Comment by LucasMahieu** [comment]
Ok, so I will try to find time to implement the Pooling (max and avg) , could you implement the conv2d ?

The freezing is exactly what we need, I will look to it more precisely how it works.

> As a starter, I think we can require user to freeze the graph and get rid of the variables before exporting to ONNX .

If I understood correctly, freezing the graph removes all variables and replaces them by constants. So the user will just have to call the freezing script.

**Comment by LucasMahieu** [comment]
I wrote a random generator of unit tests.
It generate tests like the "unit.py" at the end of this message.
It seems to work well.
You just have to run `python unit.py` and the deploy.frozen.pb will be generated.

So, to resume, the final user must add in his tensorflow model script:
```python
tf.train.write_graph(sess.graph, os.path.dirname(os.path.realpath(__file__)), 'deploy.pbtxt', as_text=True)
save_path = saver.save(sess, os.path.dirname(os.path.realpath(__file__))+'/model.ckpt')
        print('Model saved in file: {}'.format(save_path))
        # Look here for more details https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph_test.py
        freeze_graph.freeze_graph(
           os.path.join(os.path.dirname(os.path.realpath(__file__)), 'deploy.pbtxt'), # GraphDef
           '',
           False, # is the GraphDef in binary format
           os.path.join(os.path.dirname(os.path.realpath(__file__)), 'model.ckpt'), # checkpoint name
           'prob', # output node name
           '', '',
           os.path.join(os.path.dirname(os.path.realpath(__file__)), 'deploy.frozen.pb'), # output frozen path graph
           True, # clear devices info from meta-graph
           '', '', '')
```
and the onnx front-end will takes as input the : deploy.frozen.pb
Is it rights ?

This is the unit.py:
----
```python
import argparse
if __name__ == '__main__':
    parser = argparse.ArgumentParser()
    parser.add_argument('--input', help='input of the net (if not provied, the net will create one)')
    args = parser.parse_args()
import os
import numpy
import tensorflow as tf
from tensorflow.python.tools import freeze_graph

if __name__ == '__main__':
    ############################################################################################
    # input placeholder, this variable have to be give to the feel_dict in order to run the graph
    ############################################################################################
    data = tf.placeholder(dtype=tf.float32, shape=[None,16,17,32])
    prob = tf.nn.conv2d(data
        ,filter=tf.Variable(tf.random_normal([1, 1, 32, 31]))
        ,strides=[1, 4, 4, 1]
        ,padding='VALID'
        ,data_format='NHWC'
        ,name='prob'
)
#output size: b,h,w,d = None, 4,5,31
    saver = tf.train.Saver()
    global_init = tf.global_variables_initializer()
    with tf.Session() as sess:
        sess.run(global_init)
        tf.train.write_graph(sess.graph, os.path.dirname(os.path.realpath(__file__)), 'deploy.pbtxt', as_text=True)
        if args.input is None or not os.path.exists(args.input):
            input = numpy.random.rand(1, 16, 17, 32).astype(dtype=numpy.float32)
            if args.input is not None:
                print('Input given don\'t exists, so random input was generated and saved at given location :{}'.format(args.input))
                input.tofile(args.input)
            else:
                in_path = os.path.dirname(os.path.realpath(__file__))+'/input'
                print('No input was given, so random input was generated and saved at: {}'.format(in_path))
                input.tofile(in_path)
        else:
            input = numpy.fromfile(args.input, dtype=numpy.float32)
            input = numpy.reshape(input, (1,16,17,32))
        sess.run(prob, feed_dict={data:input})
        save_path = saver.save(sess, os.path.dirname(os.path.realpath(__file__))+'/model.ckpt')
        print('Model saved in file: {}'.format(save_path))
        # Look here for more details https://github.com/tensorflow/tensorflow/blob/master/tensorflow/python/tools/freeze_graph_test.py
        freeze_graph.freeze_graph(
           os.path.join(os.path.dirname(os.path.realpath(__file__)), 'deploy.pbtxt'), # GraphDef
           '',
           False, # is the GraphDef in binary format
           os.path.join(os.path.dirname(os.path.realpath(__file__)), 'model.ckpt'), # checkpoint name
           'prob', # output node name
           '', '',
           os.path.join(os.path.dirname(os.path.realpath(__file__)), 'deploy.frozen.pb'), # output frozen path graph
           True, # clear devices info from meta-graph
           '', '', '')
```

**Comment by LucasMahieu** [comment]
Please, note that in this unit tests, it also writes on disk the input and output to be saved into onnx format

**Comment by LucasMahieu** [comment]
please, note this comment that could help the front end development : https://github.com/onnx/onnx-tensorflow/issues/31#issuecomment-352019711

**Comment by davidbuniat** [comment]
Following @LucasMahieu added a simple experimental test [here](https://github.com/davidbuniat/onnx-tensorflow/blob/master/test/frontend/test_conv.py) and simple covn2d handler, but stuck on generalizing to have multiple Conv layers. Also onnx backend does not support Identity op for testing.

**Comment by LucasMahieu** [comment]
Hi, it great to see contributors.
I think a first things to do is to use [these](https://github.com/tensorflow/tensorflow/blob/c496f53af0cf4bba27b30ae7bc8886171fed867a/tensorflow/tools/graph_transforms/README.md#fold_constants) functions. They permits to remove all  useless parts of the graph. Also it permits to fold all constants in the graph which simplify hugely the graph for inference.

**Comment by chinhuang007** [comment]
Frontend converter is at tf-onnx now.
