### ISSUE TITLE
NotImplementedError: StopGradient op is not implemented

### ISSUE THREAD

**Issue by yli5** [onnx/onnx-tensorflow#222]
Hi, I am a newer in onnx and onnx-tensorflow. When I convert pre-trained ResNet50 model from tensorflow to onnx, I get the following error:
*NotImplementedError: StopGradient op is not implemented.*

When I set *ignore_unimplemented=True* in *tensorflow_graph_to_onnx_model* function, I get warnings of following ops:
>/usr/local/lib/python2.7/dist-packages/onnx_tf/frontend.py:533: UserWarning: StopGradient op is not implemented.
  exception(message)
/usr/local/lib/python2.7/dist-packages/onnx_tf/frontend.py:533: UserWarning: SquaredDifference op is not implemented.
  exception(message)
/usr/local/lib/python2.7/dist-packages/onnx_tf/frontend.py:533: UserWarning: Rsqrt op is not implemented.
  exception(message)
/usr/local/lib/python2.7/dist-packages/onnx_tf/frontend.py:533: UserWarning: Switch op is not implemented.
  exception(message)
/usr/local/lib/python2.7/dist-packages/onnx_tf/frontend.py:533: UserWarning: Merge op is not implemented.
  exception(message)
/usr/local/lib/python2.7/dist-packages/onnx_tf/frontend.py:533: UserWarning: StridedSlice op is not implemented.
  exception(message)
/usr/local/lib/python2.7/dist-packages/onnx_tf/frontend.py:533: UserWarning: Pack op is not implemented.
  exception(message)

My question is: Is it because onnx-tensorflow hasn't implemented these ops? If so, do we have any plans to implement them? Or it is intended to be implemented by users?
Thanks a lot!

**To Reproduce**

I use the following commands to install onnx and onnx-tf:
>pip install onnx
>pip install onnx-tf

My program to convert Tensorflow model(frozen .pb file) to onnx is:
```
import sys
import tensorflow as tf
from tensorflow.python.tools import freeze_graph
from tensorflow.python.tools import optimize_for_inference_lib
from onnx_tf.frontend import tensorflow_graph_to_onnx_model

output_graph = './tmp/resnet50_model_frozen.pb'
output_node_names = 'Softmax'

with tf.gfile.GFile(output_graph, 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                    output_node_names, ignore_unimplemented=True)
    file = open("mnist.onnx", "wb")
    file.write(onnx_model.SerializeToString())
    file.close()
```

**Comment by fumihwh** [comment]
There are two cases about unimplemented ops.
1. ONNX does not support that op (We will not go to implement them.)
2. onnx-tf does not have implemented currently (We will but there is no schedule yet. Contribution is welcome.)
   1) op is an ONNX op
   2) op can be implemented by primary ONNX op

Please refer [ONNX Operators](https://github.com/onnx/onnx/blob/master/docs/Operators.md) and [ONNX-TF support status](https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status.md)

**Comment by lcskrishna** [comment]
Hello @fumihwh, 
Not sure if this is the right place to ask the question? I see that there is a Rsqrt operator in tensorflow that can be splitted into Reciprocal and sqrt ops which are shown as supported by both onnx and onnx-tf. Is there any way that you can support this op?

**Comment by fumihwh** [comment]
@lcskrishna 
FYI, https://github.com/onnx/onnx/wiki/Proposal----Adding-Function-into-ONNX
With same motivation of reducing number of primitive operators, we don't want to add op which can be composited by primary ops. It will be endless, tf has so many ops.

**Comment by tjingrant** [comment]
Closing, same as https://github.com/onnx/onnx-tensorflow/issues/86.
