### ISSUE TITLE
KeyError: dtype('O') in tensorflow_graph_to_onnx_model

### ISSUE THREAD

**Issue by blagodurov** [onnx/onnx-tensorflow#230]
I am trying to convert a TF frozen graph into an onnx file using the instructions on https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowExport.ipynb

Since I want to convert a TF model with multi nodes to onnx format (see issue for https://github.com/onnx/onnx-tensorflow/issues/203), I've installed the latest onnx-tensorflow inside a TF docker like so:
pip install onnx-tf
wget https://github.com/onnx/onnx-tensorflow/archive/master.zip
unzip master.zip
cd onnx-tensorflow-master .
pip install -e .

I've taken a frozen-graph.tb from http://download.tensorflow.org/models/object_detection/ssd_inception_v2_coco_2018_01_28.tar.gz

Here is how I am trying to do so:
import tensorflow as tf
from onnx_tf.frontend import tensorflow_graph_to_onnx_model
with tf.gfile.GFile("/notebooks/frozen_inference_graph.pb", "rb") as f:
  graph_def = tf.GraphDef()
  graph_def.ParseFromString(f.read())
  
  node_names = [node.name for node in graph_def.node]
  output_node_names = node_names
  onnx_model = tensorflow_graph_to_onnx_model(graph_def, output_node_names)

Gives the following error:
Traceback (most recent call last):
  File "<stdin>", line 10, in <module>
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 306, in tensorflow_graph_to_onnx_graph
    node_tup = [(node.name, TensorflowNode(node)) for node in graph_def.node]
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 48, in __init__
    new_val = attr_translator.translate_tf(key, val)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/attr_translator.py", line 28, in translate_tf
    return __tf_attr_translator.get(key, lambda x: x)(val)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/attr_translator.py", line 10, in <lambda>
    "dtype": lambda x: data_type.tf2onnx(x.type),
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/data_type.py", line 16, in tf2onnx
    return mapping.NP_TYPE_TO_TENSOR_TYPE[np.dtype(tf_dype.as_numpy_dtype)]
KeyError: dtype('O')

Any help is appreciated,
--Sergey

**Comment by fumihwh** [comment]
@blagodurov 
The pb contains too many unsupported ops. 
For example, Assert, While Loop. The problem you posted is onnx-tf can't deal with dtype string because of different interpretation between tf and onnx. This can be fixed soon but not while loop.

**Comment by blagodurov** [comment]
@fumihwh
Thank you! Would it be possible to explain briefly why certain ops, like Assert or While loop, are not supported in onnx? What are the difficulties of adding such support? Is it purely lack of time, or are there some fundamental differences between tensorflow and onnx?

**Comment by fumihwh** [comment]
@blagodurov 
All ONNX operators are listed here https://github.com/onnx/onnx/blob/master/docs/Operators.md
Of course they are working on improving ONNX, for example, support more ops.

**Comment by tjingrant** [comment]
Closing due to lack of response and activity.
Also the questions seem to have been resolved.
