### ISSUE TITLE
Error with input dict when converting from PyTorch -- ONNX -- TensorflowNet

### ISSUE THREAD

**Issue by vidyamuthukumar1** [onnx/onnx-tensorflow#231]
Hi,

I'd like to convert a model from PyTorch to ONNX to TensorflowNet and it seems like there is a problem with the input dict attribute. Here is the sample code (essentially taken from the ONNX tutorial links at https://onnx.ai/getting-started):

import torch
import torch.onnx
import onnx
from onnx_tf.backend import prepare

---Saving model_pt (which is a PyTorch.nn module)
torch.onnx.export(model_pt, dummy_input, onnx_file)
model_tf = onnx.load(onnx_file)

--- Sanity checks for ONNX model work ---
onnx.checker.check_model(model_tf)
print(onnx.helper.printable_graph(model_tf.graph))

tf_rep = prepare(model_tf)
print(tf_rep.predict_net)
print('-----')
print(tf_rep.predict_net.input_dict)
print('-----')
print(tf_rep.uninitialized)

Result: print(tf_rep.predict_net.input_dict) throws up an error message
AttributeError: 'TensorflowNet' object has no attribute 'input_dict'.
When I type 
print(tf_rep.__dict__) 
(to check for attributes) input_dict does not show up at all.
It looks like the input dict is not being saved at all.
Any reason that strikes you as to why this is happening? Much appreciated!

**Comment by tjingrant** [comment]
Hi, we probably need to update our tutorial. Things have changed. 

TensorflowRep has been much simplified; cf the definition of TensorflowRep here (https://github.com/onnx/onnx-tensorflow/blob/00061329adc996f080163cae5ecaa0dd6748e6c3/onnx_tf/backend_rep.py). Hopefully everything is explanatory there.

**Comment by vidyamuthukumar1** [comment]
Thanks, this certainly looks simpler to read. One more thing, what do I change the following line to -- 
tf_rep = prepare(model_onnx)

Do I still import backend or should I now import backend_rep?

**Comment by tjingrant** [comment]
I think there's nothing you need to do to that line plus the "import". The only thing to look out for is the missing fields/attrs, which should be self-evident when you look at backend_rep.py

**Comment by Coderx7** [comment]
@vidyamuthukumar1 Hi did you solve this? ,I'm getting the same error:
```
C:\Users\test\Anaconda3\lib\site-packages\h5py\__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
<onnx_tf.tf_net.TensorflowNet object at 0x00000281357D27B8>
-----
Traceback (most recent call last):
  File "convert_onnx.py", line 174, in <module>
    print(tf_rep.input_dict)
AttributeError: 'TensorflowRep' object has no attribute 'input_dict'
```

Whats wrong here? how can I solve this?
Thanks in advance

**Comment by fumihwh** [comment]
@vidyamuthukumar1 In master branch, you can get inputs by `tf_rep.inputs`. For more details, please see https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/backend_rep.py
