### ISSUE TITLE
onnx_tf/handlers/frontend/slice.py args_check error

### ISSUE THREAD

**Issue by chenghaz** [onnx/onnx-tensorflow#232]
**Describe the bug**

The function check whether input[1] and input[2] is constant. But from tf.slice document, the input[1]: begin and input[2]: size just need to be INT32 or INT64 tensor.

**To Reproduce**

import tensorflow as tf

t = tf.constant([1,1,1,1,1,1,1,1,1,1,1,1,1])
slice_begin = tf.constant(1)
g = tf.slice(t, tf.expand_dims(slice_begin, 0), [3]) 
with tf.Session() as sess: 
    sess.run(g)

In this case, the input[1] for tf.slice is not const type. 

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.5
 - ONNX version: 1.2.2
 - ONNX-TF version: 1.1.2
 - Tensorflow version: 1.9.0

**Additional context**

**Comment by fumihwh** [comment]
@chenghaz Yes, tf doesn't need input must be a constant but ONNX needs.
https://github.com/onnx/onnx/blob/master/docs/Operators.md#Slice

There is an idea to solve such problem. Use dummy input and `eval()` to get the tensor's value.

**Comment by chenghaz** [comment]
@fumihwh Oh, I noticed that. Thank you for your information! 
ONNX AttributeProto seems a little bit weird comparing to tensorflow.
