### ISSUE TITLE
NotImplementedError: Unpack op is not implemented when converting tensorflow LSTM to ONNX

### ISSUE THREAD

**Issue by jack9766** [onnx/onnx-tensorflow#235]
# Describe the bug

When calling `tensorflow_graph_to_onnx_model` on a frozen graph of LSTM, `NotImplementedError: Unpack op is not implemented.` is raised.

# To Reproduce

### ALL scripts and files needed is in [THIS](https://github.com/jack9766/tf_onnx_test) repo.

**Generate checkpoint and graph.proto.**

[This](https://github.com/jack9766/tf_onnx_test/blob/master/tf_lstm.py) tensorflow script is used to train a MNIST LSTM and save its `graph.proto` and `ckpt`.
Run it using `python tf_lstm.py`.

**Generate `frozen_graph.pb`**

The following command is used to generate the frozen graph from the outputs of `tf_lstm.py`.
```shell
bazel-bin/tensorflow/python/tools/freeze_graph --input_graph=graph.proto --input_checkpoint=ckpt/lstm.ckpt --output_graph=frozen_graph.pb --output_node_names=Softmax --input_binary=True
```
The `frozen_graph.pb` i generated is [here](https://github.com/jack9766/tf_onnx_test/blob/master/frozen_graph.pb).

**Convert to onnx model**

I run [this](https://github.com/jack9766/tf_onnx_test/blob/master/tf2onnx.py) script using `python onnx2tf.py`.

And the following output is produced:
```shell
Traceback (most recent call last):
  File "tf2onnx.py", line 9, in <module>
    opset=6)
  File "/home/j84095329/anaconda3/envs/doml/lib/python3.5/site-packages/onnx_tf/frontend.py", line 442, in tensorflow_graph_to_onnx_model
    graph_def, output_node, opset, graph_name, ignore_unimplemented)
  File "/home/j84095329/anaconda3/envs/doml/lib/python3.5/site-packages/onnx_tf/frontend.py", line 294, in tensorflow_graph_to_onnx_graph
    "{} op is not implemented.".format(node.op))
  File "/home/j84095329/anaconda3/envs/doml/lib/python3.5/site-packages/onnx_tf/frontend.py", line 531, in _catch_exception
    raise exception(message)
NotImplementedError: Unpack op is not implemented.
```

# Python, ONNX, ONNX-TF, Tensorflow version

This section can be obtained by running `get_version.py` from util folder.

- Python version:
`3.5.5 | packaged by conda-forge | (default, Jul 23 2018, 23:45:43)
[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]`
- ONNX version:
`1.2.2`
- ONNX-TF version:
`1.1.2`
- Tensorflow version:
`1.10.0`

**Comment by tjingrant** [comment]
Unpack op is not part of ONNX standard. If you have such need, you can add your comment to this issue: https://github.com/onnx/onnx/issues/859.

**Comment by jack9766** [comment]
So onnx-tensorflow has a temporary fix for `unstack` mentioned in [this issue](https://github.com/onnx/tensorflow-onnx/issues/10). Is there a way to port that over?

**Comment by tjingrant** [comment]
Looking at it now. will keep you updated.

**Comment by fumihwh** [comment]
@jack9766 
#236 You can have a try.

**Comment by jack9766** [comment]
So I  built from the new source and run `tensorflow_graph_to_onnx_model` and got this error:

```shell
Traceback (most recent call last):
  File "tf2onnx.py", line 18, in <module>
    ignore_unimplemented=True)
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/frontend.py", line 304, in tensorflow_graph_to_onnx_graph
    handlers = get_all_frontend_handlers(opset_dict)
  File "/home/j84095329/tf2onnx/onnx-tensorflow/onnx_tf/common/handler_helper.py", line 31, in get_all_frontend_handlers
    max_inclusive_version=version).since_version
RuntimeError: No schema registered for 'Cos'!
```

**Comment by tjingrant** [comment]
Closing since the problem has been resolved by the new PR.
