### ISSUE TITLE
Questions about class TensorflowRep

### ISSUE THREAD

**Issue by LexXia** [onnx/onnx-tensorflow#239]
Hi, I am using the "prepare" function to make an ONNX model executed by Tensorflow. I have just fixed a bug:
(code)    tf.import_graph_def(tf_model.graph.as_graph_def(), name='')
AttributeError: 'TensorflowRep' object has no attribute 'graph'

This bug is fixed when I change "tf_model.graph" to "tf_model.predict_net.graph" according to the codes in Issue #167 . However, I am still not understand why this bug is fixed. According to the codes in onnx_tf/backend.py, the prepare function returns an object whose class is TensorflowRep. In onnx_tf/backend_rep.py, the TensorflowRep class doesn't contain an attribute named predict_net. Although the predict_net is mentioned in the tutorial file, I connot find the definitions in the source codes.

Since I need to use the Tensorflow API (like sess.run()), I want to understant the definition of TensorflowRep to use its attribute as a Tensorflow graph. Maybe this question is a really basic and beginning question, but I am really confused now. Thank you so much.

**Comment by fumihwh** [comment]
I assume you installed by `pip install onnx-tf`.
`predict_net` is not in master branch any more.

**Comment by LexXia** [comment]
You are right @fumihwh . Thank you for your reply.

After I re-installed the master branch, I can use tf_model.graph. I have also changed tf_model.predict_net.external_input to tf_model.graph, and the codes run well.

BTW, I meet some new warnings after re-installed the master branch:

Fail to get since_version of Acos in domain `` with max_inclusive_version=3. Set to 1.
Fail to get since_version of Asin in domain `` with max_inclusive_version=3. Set to 1.
Fail to get since_version of Atan in domain `` with max_inclusive_version=3. Set to 1.
Fail to get since_version of Cos in domain `` with max_inclusive_version=3. Set to 1.
Fail to get since_version of Sin in domain `` with max_inclusive_version=3. Set to 1.
Fail to get since_version of Tan in domain `` with max_inclusive_version=3. Set to 1.

Do you have any idea about that? Thank you so much!

**Comment by fumihwh** [comment]
@LexXia Because `Acos`, `Atan`, `Sin` and others are added from opset 7.
If you don't set the opset to 3, you should update your onnx.

**Comment by LexXia** [comment]
@fumihwh Actually, my onnx version is the latest 1.2.2 and these operators are added in version 1.2.1. I do not set the opset to 3 in my python codes, but I am not familiar with the opset. If I have set the opset to 3, does that mean I use some functions to set the opset? Or the "set" finished in some kinds of ONNX configurations? Thank you.

**Comment by fumihwh** [comment]
@LexXia 
I see. You are trying to run an onnx model exported with opset 3.
Never mind, the warning is harmless.....

**Comment by LexXia** [comment]
@fumihwh OK. I have tried that with these warnings appear once the prepare function is operated. Anyway, the original question is solved. Thank you!
