### ISSUE TITLE
Reshape Input for Dynamic Batch Size

### ISSUE THREAD

**Issue by akurniawan** [onnx/onnx-tensorflow#24]
Hey guys, as I have written on [this](https://github.com/onnx/onnx-caffe2/issues/70) issue before, is there any way we can modify the input shape so that it can be more dynamic? Not only the batch_size though, if we use RNN for example, we might want to keep the length size dynamic as well

**Comment by tjingrant** [comment]
This might be a problem for the ONNX Spec repository. Specifically, whether it is possible to specify dimension of unknown size. There seems to be a somewhat related discussion regarding the RNN feature you requested (https://github.com/onnx/onnx/issues/140).

**Comment by chinhuang007** [comment]
Handling dynamic input shape is a general concern in onnx-tf. A more recent issue is opened, https://github.com/onnx/onnx-tensorflow/issues/464. Let's close this one and use 464 to provide updates.
