### ISSUE TITLE
Padding issue: VALID instead of SAME

### ISSUE THREAD

**Issue by blagodurov** [onnx/onnx-tensorflow#242]
I am trying to run inference in TF with vgg19 and other models converted with ONNX from caffe2, but I see errors that stem from the padding tag being VALID. When I replace VALID with SAME, the errors go away, and the runs achieve their expected level of accuracy.

Here is how I generate the frozen_graph.pb:
# Obtaining reference models:
wget https://github.com/caffe2/models/raw/master/vgg19/init_net.pb
wget https://github.com/caffe2/models/raw/master/vgg19/predict_net.pb

# Converting to .onnx:
# To get to the caffe2 onnx conversion modules, need to install caffe2 from source: https://github.com/pytorch/pytorch/issues/9349
#pip install onnx
#pip install future
import onnx
import caffe2.python.onnx.frontend
from caffe2.proto import caffe2_pb2
data_type = onnx.TensorProto.FLOAT
data_shape = (1, 3, 224, 224)
value_info = {
    'gpu_0/data': (data_type, data_shape)
}
predict_net = caffe2_pb2.NetDef()
with open('validation-models/caffe2/vgg19/predict_net.pb', 'rb') as f:
  predict_net.ParseFromString(f.read())
init_net = caffe2_pb2.NetDef()
with open('validation-models/caffe2/vgg19/init_net.pb', 'rb') as f:
  init_net.ParseFromString(f.read())
onnx_model = caffe2.python.onnx.frontend.caffe2_net_to_onnx_model(predict_net, init_net, value_info, )
onnx.save(onnx_model, 'validation-models/caffe2/convert-onnx/vgg19.onnx')

# Generate .pb from .onnx files:
# install onnx-tensorflow inside a TF docker like so:
#pip install onnx
#pip install onnx-tf
import tensorflow as tf
import onnx
from onnx_tf.backend import prepare
model = onnx.load('/notebooks/caffe2/vgg19.onnx')
tf_rep = prepare(model)
tf_rep.export_graph('/notebooks/caffe2/vgg19.pb')

Here is how to check the padding tags:
import tensorflow as tf
from tensorflow.python.platform import gfile
with tf.Session() as sess:
  with gfile.FastGFile("./validation-models/caffe2/convert-frozen/vgg19.pb", 'rb') as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
  node_names = [node.name for node in graph_def.node]
  node_paddings = [node.attr['padding'].s for node in graph_def.node]
  i=0
  for node_name in node_names:
    if node_paddings[i] != "":
      print node_name + " " + node_paddings[i]
    i+=1

The output is:
convolution VALID
convolution_1 VALID
max_pool VALID
convolution_2 VALID
convolution_3 VALID
max_pool_1 VALID
convolution_4 VALID
convolution_5 VALID
convolution_6 VALID
convolution_7 VALID
max_pool_2 VALID
convolution_8 VALID
convolution_9 VALID
convolution_10 VALID
convolution_11 VALID
max_pool_3 VALID
convolution_12 VALID
convolution_13 VALID
convolution_14 VALID
convolution_15 VALID
max_pool_4 VALID

This graph gives the errors when running similar to:
ValueError: Negative dimension size caused by subtracting 3 from 1 for 'conv16/Conv2D' (op: 'Conv2D') with input shapes: [1,1,1,512], [3,3,512,512].

Replacing VALID with SAME results in those errors go away, and the runs achieve their expected level of accuracy.

**Comment by fumihwh** [comment]
I don't get `replace VALID with SAME`.... Could you explain more?

**Comment by blagodurov** [comment]
Replacing "VALID" padding with "SAME" padding makes the error go away.
The .pb generated from .onnx:
convolution VALID
convolution_1 VALID
max_pool VALID
convolution_2 VALID
convolution_3 VALID
max_pool_1 VALID
convolution_4 VALID
convolution_5 VALID
convolution_6 VALID
convolution_7 VALID
max_pool_2 VALID
convolution_8 VALID
convolution_9 VALID
convolution_10 VALID
convolution_11 VALID
max_pool_3 VALID
convolution_12 VALID
convolution_13 VALID
convolution_14 VALID
convolution_15 VALID
max_pool_4 VALID

When I replace like so, the error goes away:
convolution SAME
convolution_1 SAME
max_pool SAME
convolution_2 SAME
convolution_3 SAME
max_pool_1 SAME
convolution_4 SAME
convolution_5 SAME
convolution_6 SAME
convolution_7 SAME
max_pool_2 SAME
convolution_8 SAME
convolution_9 SAME
convolution_10 SAME
convolution_11 SAME
max_pool_3 SAME
convolution_12 SAME
convolution_13 SAME
convolution_14 SAME
convolution_15 SAME
max_pool_4 SAME

**Comment by fumihwh** [comment]
@blagodurov 
Could you output the other params, e.g. each layers input shape and other attrs, to figure out the problem?

**Comment by blagodurov** [comment]
Sorry, we thought that the padding for convolution nodes is being set in within-op padding value, and we initially skipped the ‘Pad’ node in the pb file. After incorporating info from the 'Pad' nodes, the error went away. Thank you for your help!
