### ISSUE TITLE
[Front-end] Concat tf to onnx

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx-tensorflow#25]
Hi, 
I trying to implement concat op from TF to ONNX graph.
I am facing a "big" problem because TF concat API is : `tf.concat([T0, T1, ...], axis)`
and axis is considered as an input.

But TF do not puts the value of inputs in the tf graph.
So it is not possible to get the axis value in order to put it into the axis attr of onnx graph...

Did you ever faced this king of issue ?
Does someone have some ideas to solve it ?

NOTE : https://github.com/LucasMahieu/onnx-tensorflow/commit/7eedae1fedd866802019d76baad52a26cd3a086b
This is my work for now about the concat op

**Comment by tjingrant** [comment]
Yes we have seen that before. This is basically handled here: https://github.com/onnx/onnx-tensorflow/blob/ca5c120d12282f11152ebc3ef29141f369953f66/onnx_tf/frontend.py#L117.

We require axis to be a constant tensor and access its value by name through the consts variable in the handler. Take a look at how pad op is implemented here https://github.com/onnx/onnx-tensorflow/blob/ca5c120d12282f11152ebc3ef29141f369953f66/onnx_tf/frontend.py#L185.

**Comment by LucasMahieu** [comment]
It a great idea.
I will make this pull request soon. 

Thanks
