### ISSUE TITLE
Converting onnx model to tensorflow model using Saver method fails

### ISSUE THREAD

**Issue by parth1595** [onnx/onnx-tensorflow#257]
I have already converted the onnx model to tensorflow model using SaveModelBuilder method and it works fine. But I want the final pb to be which should be generated using .meta .data and .index file and should be directly be able to load in tensorboard utility using **import_pb_to_tensorboard.py**

Here is the snippet code which I have tried to generate tensorflow model using Saver method:

    onnx.checker.check_model(onnx_model)
    print('prepare tf model')
    tf_rep = prepare(onnx_model)

    if path.exists(export_path):
        shutil.rmtree(export_path)
    with tf.Session() as sess:
        print("load graph")
        sess.graph.as_default()
        tf.import_graph_def(tf_rep.graph.as_graph_def(), name='')

        saver = tf.train.Saver()
        saver.save(sess, ".")
        tf.train.write_graph(sess.graph.as_graph_def(), "./", "parth", true)

**Error:**

Traceback (most recent call last):
  File "converter_modify_1.py", line 42, in <module>
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1284, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1296, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1321, in _build
    raise ValueError("No variables to save")
ValueError: No variables to save

I have attached the onnx model and this is the mnist model.
[model.onnx.zip](https://github.com/onnx/onnx-tensorflow/files/2404792/model.onnx.zip)

**Comment by tjingrant** [comment]
Have you checked out our API doc: https://github.com/onnx/onnx-tensorflow/blob/master/doc/API.md ?

Specifically, the export_graph method.

**Comment by parth1595** [comment]
@tjingrant I think the export_graph method will only generate meta data.

**Comment by fumihwh** [comment]
@parth1595 I think you got `ValueError: No variables to save` because you need to init variable before call `saver = tf.train.Saver()`.

**Comment by parth1595** [comment]
@fumihwh Yes I know but what i think there are no variables after we perform **tf_rep = prepare(onnx_model)**. But I am not sure of this if you know how to do this then please help me to solve this.
Thanks

**Comment by fumihwh** [comment]
@parth1595 I do *import_to_tensorboard* successfully. 
```
import onnx
from tensorflow.python.tools.import_pb_to_tensorboard import import_to_tensorboard

from onnx_tf.backend import prepare

onnx_model = onnx.load("pb/model_var.onnx")

tf_rep = prepare(onnx_model)
tf_rep.export_graph("tb_pb/model_var.pb")

import_to_tensorboard("tb_pb/model_var.pb", "tb_log")
```

Then `tensorboard --logdir=tb_log`

**Comment by parth1595** [comment]
@fumihwh are you able to do inference using that pb successfully in tensorflow or not ?

**Comment by fumihwh** [comment]
@parth1595 At least, I succeeded in doing inference by using onnx-tf backend.

**Comment by parth1595** [comment]
@fumihwh Can you tell me the method how to do inference using onnx-tf backend ?

**Comment by fumihwh** [comment]
@parth1595 Just call `tf_rep.run`.

**Comment by chenyuZha** [comment]
@fumihwh  I have export the model onnx to model tensorflow (.pb), but when I tried to run the inference  by calling this model tensorflow (.pb), I had the problem between **NHWC** and **NCHW.** As you see, the onnx model is arranged like NCHW  but tensorflow model is NHWC..
So when I load my image by opencv to feed my input_tensor, I have this problem:
`ValueError: Cannot feed value of shape (512, 1024, 3) for Tensor '0:0', which has shape '(1, 3, 512, 1024)'`
So I reload my input image by permute the channels, then another error occurs:
`2018-09-24 16:50:10.159484: E tensorflow/core/common_runtime/executor.cc:645] Executor failed to create kernel. Invalid argument: Conv2DCustomBackpropInputOp only supports NHWC.
`
Any suggestions to solve this issue?

**Comment by fumihwh** [comment]
@chenyuZha Maybe this will help? https://github.com/tensorflow/tensorflow/issues/20405

**Comment by ellonde** [comment]
@chenyuZha Did you solve this? I get somewhat the same issue when exporting my model to tensorflow serve, more info here:[https://stackoverflow.com/questions/55192452/tf-saved-model-acting-different-when-run-at-endpoint](url)
