### ISSUE TITLE
Failures using onnx-tf on onnx model zoo models

### ISSUE THREAD

**Issue by mvermeulen** [onnx/onnx-tensorflow#259]
I get failures when trying to use released version of onnx-tf + released version of onnx + tensorflow on examples in the onnx model zoo saved onnx files.

Here is an example of what I see trying resnet50:

prompt% python3 inference_tf_backend.py
Traceback (most recent call last):
  File "../../inference_tf_backend.py", line 14, in <module>
    np.testing.assert_almost_equal(outputs,backend.run_model(model,inputs))
  File "/home/mev/.local/lib/python3.5/site-packages/onnx/backend/base.py", line 57, in run_model
    return cls.prepare(model, device, **kwargs).run(inputs)
  File "/home/mev/.local/lib/python3.5/site-packages/onnx_tf/backend.py", line 345, in prepare
    super(TensorflowBackendBase, cls).prepare(model, device, **kwargs)
  File "/home/mev/.local/lib/python3.5/site-packages/onnx/backend/base.py", line 53, in prepare
    onnx.checker.check_model(model)
  File "/home/mev/.local/lib/python3.5/site-packages/onnx/checker.py", line 77, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Input index 3 must be set to consumed for operator BatchNormalization

==> Context: Bad node spec: input: "gpu_0/conv1_1" input: "gpu_0/res_conv1_bn_s_0" input: "gpu_0/res_conv1_bn_b_0" input: "gpu_0/res_conv1_bn_rm_0" input: "gpu_0/res_conv1_bn_riv_0" output: "gpu_0/res_conv1_bn_1" name: "" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1.0000001e-05 type: FLOAT } attribute { name: "is_test" i: 1 type: INT }

This particular example is opset6 (release 1.1.2), but I see similar errors using opset7 (release 1.2) and opset8 (release 1.3).

I have installed released versions, with following abbreviated output from "pip3 list":
onnx                          1.1.2                 
onnx-tf                       1.1.2                 
tensorflow                  1.8.0
Tensorflow is AMD version with rocm GPU support, but others are defaults I get from a pip3 install.  

My python script is based on instructions in the onnx model zoo and is listed below:

import numpy as np
import onnx
import onnx_tf.backend as backend

#load the model, sample inputs and data
npz_path = 'test_data_0.npz'
model_pb_path = 'model.onnx'
model = onnx.load(model_pb_path)
sample = np.load(npz_path,encoding='bytes')
inputs = list(sample['inputs'])
outputs = list(sample['outputs'])

#run the model with an onnx backend and verify the results
np.testing.assert_almost_equal(outputs,backend.run_model(model,inputs))

I can certainly try building latest versions of onnx & onnx-tf if I am running into issues known to be fixed on the development branch. However, before I go there, file this bug partially to understand the level of interoperability expected between onnx model zoo models and onnx-tf capability - or if I have a user error here.

**Comment by tjingrant** [comment]
Hi this is a known issue from onnx side actually. Building from master should fix it, or alternatively, bumping onnx version alone should fix it.

This is one of the features ONNX (correctly) abandoned during its development. In general, you should expect quite high interoperability between model zoo and onnx-tf backend. If you are using imagenet models, I'd expect all of them to work out of the box (c.f. http://onnx.ai/backend-scoreboard/).

**Comment by mvermeulen** [comment]
Updating to onnx 1.3 (or onnx 1.2.3) fixes the issue described below. Thanks.

I can now demonstrate running the model zoo example for resnet50 model using the onnx-tf backend and tensorflow, so this issue can be closed.  [Note: The results don't compare, but there are multiple pieces involved and so I'll narrow that with smaller cases and as necessary file an issue on appropriate piece that might not onnx-tf]

**Comment by feiwang3311** [comment]
There are 4 Tensors in batch normalization layer, can anyone tell me which is input mean and variance, and which is learn-able parameter scale and shift?
"gpu_0/res_conv1_bn_s_0"      --- all positive
"gpu_0/res_conv1_bn_b_0"      --- some positive, some negative, relatively large absolute value
"gpu_0/res_conv1_bn_rm_0"    --- some positive, some negative, relatively small absolute value
"gpu_0/res_conv1_bn_riv_0"    --- all positive

**Comment by fumihwh** [comment]
@feiwang3311 https://github.com/pytorch/pytorch/blob/master/caffe2/python/layers/batch_normalization.py#L51

**Comment by JoeyCarson** [comment]
I have a similar error when trying to convert ResNet-18v2 from onnx to tf.  

Input index 3 must be set to consumed for operator BatchNormalization

==> Context: Bad node spec: input: "data" input: "resnetv22_batchnorm0_gamma" input: "resnetv22_batchnorm0_beta" input: "resnetv22_batchnorm0_running_mean" input: "resnetv22_batchnorm0_running_var" output: "resnetv22_batchnorm0_fwd" name: "resnetv22_batchnorm0_fwd" op_type: "BatchNormalization" attribute { name: "epsilon" f: 1e-05 type: FLOAT } attribute { name: "momentum" f: 0.9 type: FLOAT } attribute { name: "spatial" i: 1 type: INT }

I very recently installed onnx, so I would expect to be on a more to up-to-date version, but I see 1.1.1.
>>> import onnx
>>> onnx.__version__
'1.1.1'

**Comment by JoeyCarson** [comment]
Requirement already satisfied: onnx in \appdata\local\continuum\anaconda3\lib\site-packages (1.3.0)

**Comment by fumihwh** [comment]
@JoeyCarson 
In latest version of onnx, BatchNormalization no longer has `consumed_inputs` attribute. Maybe you could try to install from source.

**Comment by JoeyCarson** [comment]
@fumihwh would that require setting up a build environment?  Is there not a beta release of onnx I could install instead?  I just wanted to get a better grasp of the actual error here.  Does the ResNet-18v2 onnx model need to be updated for compatibility or is it just that it's newer and the onnx runtime itself needs to be updated?

**Comment by fumihwh** [comment]
@JoeyCarson An other thing is you should get 1.3.0 from `pip install onnx`..not 1.1.1. https://pypi.org/project/onnx/
