### ISSUE TITLE
[Front-End] How to deals with data_format : 'NHWC' (tf) vs. 'NCHW' (onnx)

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx-tensorflow#26]
I would like to have idea from the community to implement the conversion from tensorflow data_format 'NHWC' to onnx data_format 'NCHW'.

Should we have to add an op node of type transpose ?
If yes, the classmethod handler_name seems to not be very adapted to add 2 nodes into the "ops_proto" list ...

**Comment by LucasMahieu** [comment]
After having thought, I think it is just attr that need to be re ordered.
Can be closed

**Comment by tjingrant** [comment]
Yes. It seems to be that you could modify the return ops to be a list of ops instead of one single op...

**Comment by LucasMahieu** [comment]
That is what i was trying to implmement.
But in that case, if we convert a tf graph into onnx (with this method) then convert back in tf, we will get 2 transposes before and after each max pool. The two transposes will be the strict oposite of each others...

The perfect front end + back end would get back the same tf graph that the initial.

-------------------------
Lucas MAHIEU
Lucas.mahieu@icloud.com

**Comment by tjingrant** [comment]
Indeed I resonate strongly with your feeling about the "perfect front end + back end". One thing we can do is to extend the model converter to have optimization passes. In such passes we can implement transposition folding algorithm that looks for consecutive transpositions that are inverses of each other and eliminate them (or compose consecutive transpositions and then eliminate the identity transpositions).

**Comment by LucasMahieu** [comment]
Perfect, it was exactly what i Wanted to propose you.

-------------------------
Lucas MAHIEU
Lucas.mahieu@icloud.com

**Comment by LucasMahieu** [comment]
Related post : https://github.com/onnx/onnx-tensorflow/issues/31#issuecomment-352019711

**Comment by chinhuang007** [comment]
We no longer support frontend.
