### ISSUE TITLE
NotImplementedError: Split is not implemented

### ISSUE THREAD

**Issue by wwwanghao** [onnx/onnx-tensorflow#261]

**Comment by fumihwh** [comment]
Please provide more information.
And as https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status.md, split should be supported already.

**Comment by Mu7ammad** [comment]
I'm facing this same error here while trying to convert a frozen TensorFlow model to ONNX. I attach here a tiny example model which is an RNN that has a single output named "output". Using the conversion function tensorflow_graph_to_onnx_model( .. ) as per tutorial, and setting output node to "output", it gives me a "Split op not implemented" Error.
I wonder if that's related to having the older split_v and not Split written in the supported Ops list for the Frontend. Any Idea how to fix this?
[frozen.pb.zip](https://github.com/onnx/onnx-tensorflow/files/2431283/frozen.pb.zip)

**Comment by fumihwh** [comment]
@wwwanghao @Mu7ammad I got the bug and am working on this now.

**Comment by fumihwh** [comment]
@wwwanghao @Mu7ammad Should be fixed now. If the problem still exists, feel free to reopen this issue.
