### ISSUE TITLE
Problem in TF Backend Conversion

### ISSUE THREAD

**Issue by jsigee87** [onnx/onnx-tensorflow#268]
**Describe the bug**

I successfully converted several CoreML models to ONNX and then to Tensor Flow with the same code, but this small and simple model fails on a key error when the prepare function is building the graph. Looks like a key error in the ONNX Node, but didn't finish tracing it.

```
/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/onnx-tensorflow/onnx_tf/common/handler_helper.py:71: UserWarning: Fail to get since_version of Expand in domain `` with max_inclusive_version=7. Set to 1.
  handler.ONNX_OP, handler.DOMAIN, version))
/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/onnx-tensorflow/onnx_tf/common/handler_helper.py:74: UserWarning: Unknown op ConstantLike in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
2018-10-01 13:18:56.823270: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Traceback (most recent call last):
  File "Converter.py", line 120, in <module>
    tf_model = prepare(model)
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/onnx-tensorflow/onnx_tf/backend.py", line 76, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/onnx-tensorflow/onnx_tf/backend.py", line 96, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/onnx-tensorflow/onnx_tf/backend.py", line 150, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/home/johnsigmon/programming/ml-sandbox/.env/lib/python3.5/site-packages/onnx-tensorflow/onnx_tf/backend.py", line 243, in _onnx_node_to_tensorflow_op
    handler = handlers[node.domain].get(node.op_type, None)
KeyError: 'ai.onnx.ml'
```

**To Reproduce**

Please give us instructions to reproduce your problem.

Download an mlmodel from https://coreml.store/mnist

```
import onnx
from onnx_tf.backend import prepare
import onnxmltools
import coremltools

path = <path to downloaded coreml model>
coreml_model = coremltools.utils.load_spec(path)
onnx_model = onnxmltools.convert_coreml(coreml_model, 'test')
onnxmltools.utils.save_model(onnx_model, 'test.onnx')
model = onnx.load('test.onnx')
tf_model = prepare(model)
```

**ONNX model file**

I can provide this if needed, I assume the full steps above are better. Let me know if you would prefer the onnx model, or the code above works fine for you.

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.5.2
 - ONNX version: 1.3.0
 - ONNX-TF version: 1.2.0
 - Tensorflow version: 1.10.1

--edited to update minimal example and error output without warning filter

**Comment by tjingrant** [comment]
Hi, since you mentioned it, could you upload the onnx model in question so that we don't have to install onnx-coreml? By looking at it, it's a neural network based model, but somehow it used some operators from onnx.ai.ml domain, which is for classical machine learning algorithms. Very weird model to begin with, but I have to actually look at the onnx file to get a definitive answer.

**Comment by jsigee87** [comment]
You got it, I hosted it on my google drive [here].(https://drive.google.com/file/d/1QtzukAPLb_MjB7KXELtHXonYPU24Yot4/view?usp=sharing)

**Comment by tjingrant** [comment]
Several problems:

- There is an op "ImageScalar" that are explicitly marked as "experimental" in the onnx spec; when you have onnx models using experimental ops, you obviously shouldn't expect the models to inter-operate well.

- In addition, this is a neural network model, but makes use of ops in onnx.ai.ml, which is for, and I quote the onnx spec:

> the Classical Machine Learning extension, ONNX-ML, also recognizes sequences and maps. ONNX-ML extends the ONNX operator set with ML algorithms that are not based on neural networks

So there's no reason to expect support for classical machine learning algorithms when you are working with a neural network models to begin with. The issue you are seeing right now is merely a manifestation of problems stemming from your upstream toolchains.

Getting back to your situation, it's not impossible to get your model working in onnx_tf, but certainly requires additional work. What I'd suggest you do is to first switch to another model (if this is a problem of the upstream coreml model), there should be plenty of mnist models that do not make use of weird experimental or classical ml ops.

If you are really keen to get this model working, I can probably help you navigate through what additional work is required and where you should put them (three ops are needed, ImageScalar, ArrayFeatureExtractor, ZipMap).

**Comment by jsigee87** [comment]
Thanks for looking into this. This MNIST model was downloaded from a 3rd party source and I was attempting to use it as a test model. I have no control over how this model is defined within CoreML, or even ONNX (as it was converted to ONNX with ONNX tools). CoreML also does not allow such control over architecture, and I am not familiar enough with ONNX to figure out why it was converted this way. I would have expected the ONNX tools to convert from CoreML to use the appropriate ops, not experimental or unsupported ops. I can reopen a new issue concerning the CoreML to ONNX conversion under onnxmltools if it is appropriate.

Regardless of this conversion, my ultimate goal is compression of CoreML models. The CoreML framework does not allow the needed control and so I must convert CoreML models into another format to perform inference. I wanted to convert from CoreML to TensorFlow to do this inference, through ONNX. I can use a different model for testing purposes in the meantime, but thought I would report what I saw to be a bug. Feel free to close this or let me know the best way to move forward.

**Comment by tjingrant** [comment]
I feel like testing out other models might be worth trying. 

Also i'm curious, why start from CoreML when you'll end up in Tensorflow anyways? Are you looking to go from Tensorflow back to CoreML afterwards? 

In general, onnx_tf backend should be robust enough to fulfill your requirements and I agree that ONNX is the right tool to do what you want.

**Comment by jsigee87** [comment]
Fair question, the larger picture is ML development for ios apps. The workflow is make ML model -> convert to CoreML and integrate, then come back later and compress the CoreML model as time allows. The compression is recently added to the workflow, hence my attempts. Sadly, my models will likely already be in CoreML form, and will have to return to CoreML form. 

Since this is a one-off and I have no interest in pursuing this particular conversion further I am going to close. Thanks for all the help.

**Comment by Nimitz14** [comment]
After converting a model from pytorch to onnx which is just a linear layer + relu and another linear layer + softmax I get 
```
INFO:root:Start converting onnx pb to tf pb:
/home/seni/git/onnx-tensorflow/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op ConstantLike in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/home/seni/git/onnx-tensorflow/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op DynamicSlice in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
INFO:root:Converting completes successfully.
```
It says it converted successfully.. so I'm unsure whether I should care about the warnings or not?

**Comment by fumihwh** [comment]
@Nimitz14 No, you don't. We should make warnings more user friendly.

**Comment by GantMan** [comment]
I'm also having the same problem as above.

I need a model converted from CoreML to TensorFlow.js, so I need TensorFlow as a middle.

```python
tf_model = prepare(model_onnx)
```

```
/usr/local/lib/python3.6/dist-packages/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op ConstantFill in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/usr/local/lib/python3.6/dist-packages/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op ImageScaler in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-15-1a704c26de68> in <module>()
----> 1 tf_model = prepare(model_onnx)

6 frames
/usr/local/lib/python3.6/dist-packages/onnx/numpy_helper.py in to_array(tensor)
     63                 dtype=storage_np_dtype)
     64             .astype(np_dtype)
---> 65             .reshape(dims)
     66         )
     67 

ValueError: cannot reshape array of size 3 into shape (3,3,1)
```
Here's the error result.

**Comment by Rphaet0n** [comment]
> I'm also having the same problem as above.
> 
> I need a model converted from CoreML to TensorFlow.js, so I need TensorFlow as a middle.
> 
> ```python
> tf_model = prepare(model_onnx)
> ```
> 
> ```
> /usr/local/lib/python3.6/dist-packages/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op ConstantFill in domain `ai.onnx`.
>   handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
> /usr/local/lib/python3.6/dist-packages/onnx_tf/common/handler_helper.py:37: UserWarning: Unknown op ImageScaler in domain `ai.onnx`.
>   handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
> ---------------------------------------------------------------------------
> ValueError                                Traceback (most recent call last)
> <ipython-input-15-1a704c26de68> in <module>()
> ----> 1 tf_model = prepare(model_onnx)
> 
> 6 frames
> /usr/local/lib/python3.6/dist-packages/onnx/numpy_helper.py in to_array(tensor)
>      63                 dtype=storage_np_dtype)
>      64             .astype(np_dtype)
> ---> 65             .reshape(dims)
>      66         )
>      67 
> 
> ValueError: cannot reshape array of size 3 into shape (3,3,1)
> ```
> 
> Here's a colab: https://colab.research.google.com/drive/1gGyQI-e4vY8TFiUmhF7UnYNwxATvtdox

I have exact same issue, CoreML Model is created using turicreate.
versions: tf - 1.15, all onnx related packages - 1.5.0.

Any ideas how to solve this problem?

**Comment by trialzuki** [comment]
I solve same issue.
In my case, I just change the order of import tf and onnx.
