### ISSUE TITLE
No test discovered?

### ISSUE THREAD

**Issue by kindlychung** [onnx/onnx-tensorflow#27]
```
$  ~/PycharmProjects/onnx-tensorflow > python -m unittest discover test

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK
```

**Comment by LucasMahieu** [comment]
did you try to go into test directory then run `python -m unittest discover test`

**Comment by tjingrant** [comment]
The documentation about tests are unfortunately outdated since we re-organized our tests. For now, please c.f. our CI script and here's the relevant part:
https://github.com/onnx/onnx-tensorflow/blob/ca5c120d12282f11152ebc3ef29141f369953f66/.travis/build.sh#L12
