### ISSUE TITLE
TypeError: Cannot convert value 0 to a TensorFlow DType.

### ISSUE THREAD

**Issue by blagodurov** [onnx/onnx-tensorflow#276]
I am trying to convert a pspnet TF .ckpt into an onnx file. I have downloaded pspnet cityscapes TF .ckpt from:
https://github.com/hellochick/PSPNet-tensorflow 
https://drive.google.com/drive/folders/1S90PWzXEX_GNzulG1f2eTHvsruITgqsm?usp=sharing 

However, I got the following error when issuing the conversion:
import tensorflow as tf
from onnx_tf.frontend import tensorflow_graph_to_onnx_model
with tf.Session(graph=tf.Graph()) as sess:
  new_saver = tf.train.import_meta_graph('/notebooks/pspnet101.ckpt/model.ckpt-0.meta')
  new_saver.restore(sess, '/notebooks/pspnet101.ckpt/model.ckpt-0')
  
  graph_def = sess.graph.as_graph_def()
  node_names = [node.name for node in graph_def.node]
  output_node_names = node_names

  onnx_model = tensorflow_graph_to_onnx_model(graph_def, output_node_names)
  file = open("/notebooks/pspnet101.onnx", "wb")
  file.write(onnx_model.SerializeToString())
  file.close()

2018-10-07 04:19:30.340822: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
INFO:tensorflow:Restoring parameters from /notebooks/pspnet101.ckpt/model.ckpt-0
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Pack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/notebooks/onnx-tensorflow-master/onnx_tf/common/handler_helper.py:38: UserWarning: Unknown op Undefined in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Relu6 doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Unpack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
Traceback (most recent call last):
  File "<stdin>", line 8, in <module>
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 306, in tensorflow_graph_to_onnx_graph
    node_tup = [(node.name, TensorflowNode(node)) for node in graph_def.node]
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 48, in __init__
    new_val = attr_translator.translate_tf(key, val)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/attr_translator.py", line 28, in translate_tf
    return __tf_attr_translator.get(key, lambda x: x)(val)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/attr_translator.py", line 9, in <lambda>
    "T": lambda x: data_type.tf2onnx(x.type),
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/data_type.py", line 11, in tf2onnx
    tf_dype = tf.as_dtype(dtype)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/dtypes.py", line 712, in as_dtype
    raise TypeError("Cannot convert value %r to a TensorFlow DType." % type_value)
TypeError: Cannot convert value 0 to a TensorFlow DType.

Any help is appreciated. Thanks!

**Comment by fumihwh** [comment]
@blagodurov 
Could you use following source to create freezing graph and share to us?
```
minimal_graph = tf.graph_util.convert_variables_to_constants(
            sess,
            sess.graph.as_graph_def(add_shapes=True),
            ['output'],
        )
```

**Comment by blagodurov** [comment]
Here it is: https://www.dropbox.com/s/vsdl4ov0nh0727l/pspnet101.pb?dl=0

minimal_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(add_shapes=True), ['output'], )
gave the following error: AssertionError: output is not in graph

So I used the code below to generate:
import tensorflow as tf
from onnx_tf.frontend import tensorflow_graph_to_onnx_model
with tf.Session(graph=tf.Graph()) as sess:
  new_saver = tf.train.import_meta_graph('/notebooks/pspnet101.ckpt/model.ckpt-0.meta')
  new_saver.restore(sess, '/notebooks/pspnet101.ckpt/model.ckpt-0')
  graph_def = sess.graph.as_graph_def()
  node_names = [node.name for node in graph_def.node]
  output_node_names = node_names
  minimal_graph = tf.graph_util.convert_variables_to_constants(sess, sess.graph.as_graph_def(add_shapes=True), output_node_names, )
  with tf.gfile.GFile("/notebooks/pspnet101.pb", "wb") as f:
    f.write(minimal_graph.SerializeToString())

**Comment by fumihwh** [comment]
@blagodurov Yes, you should replace 'output' with your output names.
And do you have pspnet50?..pspnet100 too large to open in Netron.

**Comment by blagodurov** [comment]
Here you go: https://www.dropbox.com/s/pojkggbjs6drvk0/pspnet50.pb?dl=0

**Comment by fumihwh** [comment]
@blagodurov BTW, you should set output name explicitly. 
Not just
```
node_names = [node.name for node in graph_def.node]
output_node_names = node_names
```

**Comment by blagodurov** [comment]
Thank you! Now I see a different error in tensorflow_graph_to_onnx_model():
2018-10-16 18:05:18.433930: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: FMA
INFO:tensorflow:Restoring parameters from /notebooks/pspnet101.ckpt/model.ckpt-0
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Pack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/notebooks/onnx-tensorflow-master/onnx_tf/common/handler_helper.py:38: UserWarning: Unknown op Undefined in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Relu6 doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
/notebooks/onnx-tensorflow-master/onnx_tf/common/handler_helper.py:38: UserWarning: Unknown op DynamicSlice in domain `ai.onnx`. Can't check specification by ONNX. Please set should_check flag to False when call make_node method in handler.
  "ai.onnx"))
/notebooks/onnx-tensorflow-master/onnx_tf/handlers/handler.py:35: UserWarning: Unpack doesn't have ONNX_OP. Please use Handler.onnx_op decorator to register ONNX_OP.
  cls.__name__))
Traceback (most recent call last):
  File "<stdin>", line 7, in <module>
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 399, in tensorflow_graph_to_onnx_model
    graph_def, output_nodes, opset, graph_name, ignore_unimplemented)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/frontend.py", line 328, in tensorflow_graph_to_onnx_graph
    domain=None if node.domain in handlers else node.domain)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/notebooks/onnx-tensorflow-master/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: ReadFile is not implemented.

**Comment by tjingrant** [comment]
Seems like you have some training related nodes. We do not have support for ReadFile Op and we should not have support for it. Maybe try removing training nodes first? c.f. https://www.tensorflow.org/api_docs/python/tf/graph_util/remove_training_nodes

**Comment by blagodurov** [comment]
It looks like remove_training_nodes() only strips away Identity and CheckNumerics nodes: https://github.com/tensorflow/tensorflow/blob/r1.11/tensorflow/python/framework/graph_util_impl.py

So onnx conversion is only for inference, correct? It is not meant for training models? Thanks!

**Comment by blagodurov** [comment]
So I checked, and it appears I only have one ReadFile op in the graph, in the very beginning... Why do you say that ReadFile is a training related op? According to [1] all it does is it reads and outputs the entire contents of the input filename. If you do image inference, wouldn't you still need to read the image file? Thanks!

[1] https://www.tensorflow.org/api_docs/cc/class/tensorflow/ops/read-file

**Comment by blagodurov** [comment]
I will create a separate issue for it. Thanks!
