### ISSUE TITLE
Issue in test_node of front-end

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx-tensorflow#28]
Hi,
I think that there is a bad thing appending with test_node of the front-end.

In ONNX, inputs and ops are thought to be in order : 'NCHW'

But in Tensorflow, data are often in order 'NHWC'. (for some tf operations, only 'NHWC' is supported, and for other operations is it impossible to know the data_format (Placeholers for example)).
So, we can imagine to require that user puts all his tensorflow operation in 'NHWC' data format.

In that case, we should consider only inputs in 'NHWC' in the test_node of tensorflow.
That is not the case...

**Comment by tjingrant** [comment]
You can simply insert transpositions. Check here https://github.com/onnx/onnx-tensorflow/blob/ca5c120d12282f11152ebc3ef29141f369953f66/onnx_tf/backend.py#L537 to see an example of how we dealt with this in our backend.

**Comment by LucasMahieu** [comment]
Do you agree that the input of the onnx graph is the transpose of the tf graph if working in CPU ?

**Comment by tjingrant** [comment]
Hi, yes I agree.

Can you paste a reference to the specific test that you think is problematic?

**Comment by LucasMahieu** [comment]
In fact all tests are implicated ... but solving https://github.com/onnx/onnx-tensorflow/issues/31#issuecomment-352019711 will solve the problem.

**Comment by LucasMahieu** [comment]
I think this the issue : 
https://github.com/onnx/onnx-tensorflow/blob/c1fc643cab821ae6800ab32e48e2c892478ac338/test/frontend/test_node.py#L56

This line gives to the back end to input as is. Even if the input is 'NHWC' whereas ONNX should always gives feed dict to the back end to the form 'NCHW'.
am I right ?

**Comment by tjingrant** [comment]
To be fair, there has not been a test that requires special treatment regarding data formats. And yes you are right, going forward, we'd need to have some ways of detecting what data format to use.

**Comment by LucasMahieu** [comment]
You are right. Tomorow i will push the modification about all these issues of data format that implements my proposal made on other issue last week.

**Comment by chinhuang007** [comment]
We no longer support frontend, therefore close the issue.
