### ISSUE TITLE
getting wrong model while converting tensorflow to onnx

### ISSUE THREAD

**Issue by peteryang1** [onnx/onnx-tensorflow#289]
**Describe the bug**

while converting a tensorflow model to onnx, I get a wrong model.
tf.conv2d uses NHWC format, but onnx uses NCHW as default. In my tf model ,I use reshape to get a tensor like (1,28,28,1), then put it into a conv2d node, when i convert it to an onnx model, it goes wrong.

any idea how to deal with it?

**To Reproduce**

Please give us instructions to reproduce your problem.
the tf model and onnx model are given in the file, i convert it using the script below:

```Python
onnx_model = tensorflow_graph_to_onnx_model(graph_def,
                                        output_node_name)
onnx_model = onnx.optimizer.optimize(onnx_model,passes=["nop","eliminate_identity","eliminate_nop_transpose","eliminate_nop_pad","eliminate_unused_initializer","fuse_consecutive_squeezes","fuse_consecutive_transposes","fuse_add_bias_into_conv","fuse_transpose_into_gemm"])
        
```

**ONNX model file**

[models.zip](https://github.com/onnx/onnx-tensorflow/files/2477815/models.zip)

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.5
 - ONNX version: 1.3.0
 - ONNX-TF version:1.2.0
 - Tensorflow version: 1.11.0

**Additional context**

**Comment by fumihwh** [comment]
@peteryang1 You're right. I will add pre-transpose and post-transpose to make the data format correct.

**Comment by fumihwh** [comment]
@peteryang1 Could you try #290

**Comment by peteryang1** [comment]
I think it's not the Conv node which makes this issue, It's the reshape node.your code still doesn't make the right model.

Instead i did some change in my code, after your code I make some change, then i got the right model.

the script is below:

```Python
def add_transpose_around_reshape(model):
    reshape_node_list = []
    for node in model.graph.node:
        if node.op_type == "Reshape" :
            reshape_node_list.append(node)
    
    for node in reshape_node_list:
        if check(model, node):
            new_transpose = onnx.NodeProto()
            new_transpose_attribute = onnx.AttributeProto()
            new_transpose_attribute.name = "perm"
            new_transpose_attribute.ints.extend([0,3,1,2])
            new_transpose.attribute.extend([new_transpose_attribute])

            new_transpose.name = "Reshape_T_" + get_unique_suffix()
            new_transpose.input.extend([node.output[0]])
            new_transpose.output.extend([new_transpose.name])
            new_transpose.op_type = "Transpose"
            for next_node in model.graph.node:
                for next_node_input_index in range(len(next_node.input)):
                    if next_node.input[next_node_input_index] == node.output[0]:
                        next_node.input[next_node_input_index] = new_transpose.name
            node_behind_list = []
            after_current_node = False

            for i in range(0,len(model.graph.node)):
                if model.graph.node[i].name == node.name:
                    break

            for j in range(i+1,len(model.graph.node)):
                node_behind_list.append(model.graph.node[j])
            
            while i < len(model.graph.node)-1:
                del model.graph.node[i+1]
            model.graph.node.extend([new_transpose])
            model.graph.node.extend(node_behind_list)
        else:
            new_transpose = onnx.NodeProto()
            new_transpose_attribute = onnx.AttributeProto()
            new_transpose_attribute.name = "perm"
            new_transpose_attribute.ints.extend([0,2,3,1])
            new_transpose.attribute.extend([new_transpose_attribute])

            new_transpose.name = "Reshape_T_" + get_unique_suffix()
            new_transpose.output.extend([node.input[0]])
            new_transpose.input.extend([new_transpose.name])
            new_transpose.op_type = "Transpose"
            for next_node in model.graph.node:
                for next_node_output_index in range(len(next_node.output)):
                    if next_node.output[next_node_output_index] == node.input[0]:
                        next_node.output[next_node_output_index] = new_transpose.name
            node_behind_list = []
            after_current_node = False
            
            for i in range(0,len(model.graph.node)):
                if model.graph.node[i].name == node.name:
                    break

            for j in range(i,len(model.graph.node)):
                node_behind_list.append(model.graph.node[j])
            

            
            while i < len(model.graph.node):
                del model.graph.node[i]
            model.graph.node.extend([new_transpose])
            model.graph.node.extend(node_behind_list)
```

But I'm still not sure whether this function fits all the circumstances.

**Comment by peteryang1** [comment]
maxpool is dimension restricted, why don't you add transpose around maxpool node?

**Comment by peteryang1** [comment]
I think your function makes the model much slower because you add too much transpose node.

**Comment by fumihwh** [comment]
@peteryang1 In that PR we just fix Conv, patch for PoolOp will come later.
You can use [optimizer](https://github.com/onnx/onnx/blob/master/docs/Optimizer.md) to fuse consecutive transposes.

**Comment by peteryang1** [comment]
you do solved my problem, but for speed reasons, it's not a very good way. But I do appreciate your help. tks a lot!

**Comment by tjingrant** [comment]
@peteryang1 speed will not be a problem because eliminating redundant transpositions are one of the things ONNX optimizers are designed to do.

**Comment by peteryang1** [comment]
I think the transpose node you added to the graph is not redundant, it will be a node wihch the refenrence should deal with. And dealing with a transpose node is very time-consuming .
But I didn't find a more efficent way to solve it, considering your function is the only generous way, let's make it a solution.
still tks!
