### ISSUE TITLE
onnx datatype are int64 or float32, onnx_tf always generate float tensor

### ISSUE THREAD

**Issue by wangyunxiaa** [onnx/onnx-tensorflow#293]
When i am converting the onnx model (which is converted from pytorch) to tensorflow,I got a error as following:
TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: int32, int64
I check the network, and i found that,my pytorch model's input is a LongTensor, when i conver it to onnx,the op's type is int64, but when i do tensorflow rep_tf it changed to float. I read the source code,and found that:
in file "onnx-tensorflow/blob/master/onnx_tf/backend.py",line 182-199
`@classmethod
  def _onnx_initializer_to_input_dict_items(cls, initializer):
    """ Convert ONNX graph initializer to input dict items.
    :param initializer: ONNX graph initializer, list of TensorProto.
    :return: List of input dict items.
    """

    def tensor2list(onnx_tensor):
      # Use the onnx.numpy_helper because the data may be raw
      return numpy_helper.to_array(onnx_tensor).flatten().tolist()

    return [(init.name,
             tf.constant(
                 tensor2list(init),
                 shape=init.dims,
                 dtype=data_type.onnx2tf(init.data_type)))
for init in initializer]`
when i print the init.data_type of the  line "dtype=data_type.onnx2tf(init.data_type)))" the result always get value=1, no matter what the origin type the op is(such as int64,float32)
I want to know if my input data type is int64, what the  data_type should be?

**Comment by fumihwh** [comment]
@wangyunxiaa 
I tried and `onnx2tf` works well.
```
from onnx_tf.common.data_type import onnx2tf
from onnx import TensorProto
print(onnx2tf(TensorProto.INT64))
print(onnx2tf(TensorProto.FLOAT))

<dtype: 'int64'>
<dtype: 'float32'>
```
Could you give us a simple pb to test?

**Comment by wangyunxiaa** [comment]
the model path is [https://github.com/wangyunxiaa/model/](url)
ptb.new is pretraind pytorch model, the lm.onnx is converted onnx model.
the input of the pytorch is just as one batch "input = torch.LongTensor([[m,n]]), lengths = torch.LongTensor([n-1])"
printed onnx struct:
`graph torch-jit-export ( ) initializers (
  %input_1[INT64, 1x2]
  %input_2[INT64, 1]
  %learned_0[FLOAT, 10001x200]
  %learned_1[FLOAT, 800x200]
  %learned_2[FLOAT, 800x200]
  %learned_3[FLOAT, 800]
  %learned_4[FLOAT, 800]
  %learned_5[FLOAT, 200x200]
  %learned_6[FLOAT, 10001]
  %learned_7[FLOAT, 10001]
)`

tf-onnx source code output:
`[('input_1', <tf.Tensor 'Const:0' shape=(10001, 200) dtype=float32>), ('input_2', <tf.Tensor 'Const_1:0' shape=(800, 200) dtype=float32>), ('learned_0', <tf.Tensor 'Const_2:0' shape=(800, 200) dtype=float32>), ('learned_1', <tf.Tensor 'Const_3:0' shape=(800,) dtype=float32>), ('learned_2', <tf.Tensor 'Const_4:0' shape=(800,) dtype=float32>), ('learned_3', <tf.Tensor 'Const_5:0' shape=(200, 200) dtype=float32>), ('learned_4', <tf.Tensor 'Const_6:0' shape=(10001,) dtype=float32>), ('learned_5', <tf.Tensor 'Const_7:0' shape=(10001, 200) dtype=float32>), ('learned_6', <tf.Tensor 'Const_8:0' shape=(10001,) dtype=float32>), ('learned_7', <tf.Tensor 'Const_9:0' shape=(10001, 200) dtype=float32>)]`

**Comment by fumihwh** [comment]
@wangyunxiaa 
Seems some bug exists in `onnx.load`.
After `model = onnx.load("lmmodel.onnx")`, I get "input_1" by `[init for init in model.graph.initializer if init.name == "input_1"]` which should be `int64` but data type is float.
I will follow this issue, please let me know if any updates you get.

**Comment by wangyunxiaa** [comment]
my environment "python:3.6.6, torch:1.0.0, onnx:1.3.0,pytorch and onnx all installed by source",
when i convert the torch model to onnx, there are some ops donot supported,I just add 2 functions in symbolic.py as follwoings:
`@parse_args('v', 'v', 'v', 'i', 'i')
def nll_loss(g, input, target, weight, reduction, ignore_index):
    # target = _maybe_get_scalar(target)
    # weight = _maybe_get_scalar(weight)
    return g.op("ATen",
                input,
                target,
                weight,
                operator_s="nll_loss",
                reduction_i=reduction,
                ignore_index_i=ignore_index)


@parse_args('v', 'v')
def view_as(g, self, other):
    #other = _maybe_get_scalar(other),_if_scalar_type_as(g, other, self)
    return g.op("ATen", self, other, operator_s="view_as")
`
I checked another model,and found that the onnx struct 
`graph torch-jit-export (***inputs*** ) initializers (
  ***parameters***
) `
I think it in this sample it should be like this:
`graph torch-jit-export (%input_1[INT64, 1x2]
  %input_2[INT64, 1] ) initializers (
  %learned_0[FLOAT, 10001x200]
  %learned_1[FLOAT, 800x200]
  %learned_2[FLOAT, 800x200]
  %learned_3[FLOAT, 800]
  %learned_4[FLOAT, 800]
  %learned_5[FLOAT, 200x200]
  %learned_6[FLOAT, 10001]
  %learned_7[FLOAT, 10001]
) `
I donot know why does all input ops changed to initializers?

**Comment by fumihwh** [comment]
@wangyunxiaa BTW，your model is too big to test... It'd be better if use small one instead. (e.g. 20 * 20, 80 * 20)

**Comment by wangyunxiaa** [comment]
sorry,the model is not trained by myself,I just do the convert work, It is a language model,and has LSTM units,so it is so big

**Comment by fumihwh** [comment]
@wangyunxiaa 
From doc,
`torch.onnx.export(model, dummy_input, "alexnet.onnx", verbose=True, input_names=input_names, output_names=output_names)`
Did you pass correct input_names ? e.g. `input_names=["learned_0", "input_1"]`

**Comment by wangyunxiaa** [comment]
I used following codes when converting pytorch to onnx:
`input_names = ["input_1", "input_2"] + ["learned_%d" % i for i in range(8)]
output_names = ["output"]

torch.onnx.export(lang_model, (inputs, lens), "lmmodel.onnx", verbose=True, input_names=input_names, output_names=output_names)
# torch.onnx.export(lang_model, (inputs, lens), "./lmmodel.onnx", verbose=True, input_names=None, output_names=None)`
the net has 2 inputs,when i use "input_names=None",the input ops name are %1,%2, now my input ops name are "%input_1,%input_2"

**Comment by fumihwh** [comment]
@wangyunxiaa ..Please edit your comment.. I can't get which command you use to export.
And update the model at your repository.

**Comment by fumihwh** [comment]
@wangyunxiaa Could you also give the original one? The one exported by `input_names=None`.

**Comment by wangyunxiaa** [comment]
the code i used to convert model
`lang_model.eval()
lang_model.criterion.nce = False

inputs = torch.LongTensor([[1, 2]])
lens = torch.LongTensor([1])

output = lang_model.forward(inputs, lens)

input_names = ["input_1", "input_2"] + ["learned_%d" % i for i in range(8)]
output_names = ["output"]

torch.onnx.export(lang_model, (inputs, lens), "lmmodel.onnx", verbose=True, input_names=input_names, output_names=output_names)`

**Comment by wangyunxiaa** [comment]
the output of above codes:
`graph(%0 : Long(1, 2)
      %1 : Long(1)
      %2 : Float(10001, 200)
      %3 : Float(800, 200)
      %4 : Float(800, 200)
      %5 : Float(800)
      %6 : Float(800)
      %7 : Float(200, 200)
      %8 : Float(10001)
      %9 : Float(10001)) {
  %10 : Float(1, 2, 200) = onnx::Gather(%2, %0), scope: RNNModel/Embedding[encoder]
  %11 : Float(1, 2, 200) = onnx::Slice[axes=[0], ends=[9223372036854775807], starts=[0]](%10), scope: RNNModel
  %12 : Float(1!, 1, 200) = onnx::Slice[axes=[1], ends=[-1], starts=[0]](%11), scope: RNNModel
  %13 : Float(1!, 1!, 200) = onnx::Transpose[perm=[1, 0, 2]](%12), scope: RNNModel
  %14 : Float(1!, 1!, 200), %15 : Dynamic = onnx::Dropout[ratio=0](%13), scope: RNNModel/Dropout[drop]
  %16 : Long() = onnx::Constant[value={1}]()
  %17 : Dynamic = onnx::Shape(%14), scope: RNNModel/LSTM[rnn]
  %18 : Long() = onnx::Gather[axis=0](%17, %16), scope: RNNModel/LSTM[rnn]
  %19 : Long() = onnx::Constant[value={1}]()
  %20 : Long() = onnx::Constant[value={200}]()
  %21 : Dynamic = onnx::Unsqueeze[axes=[0]](%19), scope: RNNModel/LSTM[rnn]
  %22 : Dynamic = onnx::Unsqueeze[axes=[0]](%18), scope: RNNModel/LSTM[rnn]
  %23 : Dynamic = onnx::Unsqueeze[axes=[0]](%20), scope: RNNModel/LSTM[rnn]
  %24 : int[] = onnx::Concat[axis=0](%21, %22, %23), scope: RNNModel/LSTM[rnn]
  %25 : Float(1, 1, 200) = onnx::ConstantFill[dtype=1, input_as_shape=1, value=0](%24), scope: RNNModel/LSTM[rnn]
  %26 : Dynamic = prim::Undefined(), scope: RNNModel/LSTM[rnn]
  %27 : Dynamic = onnx::Slice[axes=[0], ends=[200], starts=[0]](%3), scope: RNNModel/LSTM[rnn]
  %28 : Dynamic = onnx::Slice[axes=[0], ends=[800], starts=[600]](%3), scope: RNNModel/LSTM[rnn]
  %29 : Dynamic = onnx::Slice[axes=[0], ends=[600], starts=[200]](%3), scope: RNNModel/LSTM[rnn]
  %30 : Dynamic = onnx::Concat[axis=0](%27, %28, %29), scope: RNNModel/LSTM[rnn]
  %31 : Dynamic = onnx::Slice[axes=[0], ends=[200], starts=[0]](%4), scope: RNNModel/LSTM[rnn]
  %32 : Dynamic = onnx::Slice[axes=[0], ends=[800], starts=[600]](%4), scope: RNNModel/LSTM[rnn]
  %33 : Dynamic = onnx::Slice[axes=[0], ends=[600], starts=[200]](%4), scope: RNNModel/LSTM[rnn]
  %34 : Dynamic = onnx::Concat[axis=0](%31, %32, %33), scope: RNNModel/LSTM[rnn]
  %35 : Dynamic = onnx::Slice[axes=[0], ends=[200], starts=[0]](%5), scope: RNNModel/LSTM[rnn]
  %36 : Dynamic = onnx::Slice[axes=[0], ends=[800], starts=[600]](%5), scope: RNNModel/LSTM[rnn]
  %37 : Dynamic = onnx::Slice[axes=[0], ends=[600], starts=[200]](%5), scope: RNNModel/LSTM[rnn]
  %38 : Dynamic = onnx::Concat[axis=0](%35, %36, %37), scope: RNNModel/LSTM[rnn]
  %39 : Dynamic = onnx::Slice[axes=[0], ends=[200], starts=[0]](%6), scope: RNNModel/LSTM[rnn]
  %40 : Dynamic = onnx::Slice[axes=[0], ends=[800], starts=[600]](%6), scope: RNNModel/LSTM[rnn]
  %41 : Dynamic = onnx::Slice[axes=[0], ends=[600], starts=[200]](%6), scope: RNNModel/LSTM[rnn]
  %42 : Dynamic = onnx::Concat[axis=0](%39, %40, %41), scope: RNNModel/LSTM[rnn]
  %43 : Dynamic = onnx::Concat[axis=0](%38, %42), scope: RNNModel/LSTM[rnn]
  %44 : Dynamic = onnx::Unsqueeze[axes=[0]](%30), scope: RNNModel/LSTM[rnn]
  %45 : Dynamic = onnx::Unsqueeze[axes=[0]](%34), scope: RNNModel/LSTM[rnn]
  %46 : Dynamic = onnx::Unsqueeze[axes=[0]](%43), scope: RNNModel/LSTM[rnn]
  %47 : Dynamic, %48 : Float(1, 1, 200), %49 : Float(1, 1, 200) = onnx::LSTM[hidden_size=200](%14, %44, %45, %46, %26, %25, %25), scope: RNNModel/LSTM[rnn]
  %50 : Float(1, 1, 200) = onnx::Squeeze[axes=[1]](%47), scope: RNNModel/LSTM[rnn]
  %51 : Float(1, 1, 200), %52 : Dynamic = onnx::Dropout[ratio=0](%50), scope: RNNModel/Dropout[drop]
  %53 : Float(1, 1, 200) = onnx::Transpose[perm=[1, 0, 2]](%51), scope: RNNModel
  %54 : Float(200!, 200!) = onnx::Transpose[perm=[1, 0]](%7), scope: RNNModel/Linear[projection]
  %55 : Float(1, 1, 200) = onnx::MatMul(%53, %54), scope: RNNModel/Linear[projection]
  %56 : Long(1, 2) = onnx::Slice[axes=[0], ends=[9223372036854775807], starts=[0]](%0), scope: RNNModel
  %57 : Long(1!, 1) = onnx::Slice[axes=[1], ends=[9223372036854775807], starts=[1]](%56), scope: RNNModel
  %58 : Float(200!, 10001!) = onnx::Transpose[perm=[1, 0]](%2), scope: RNNModel/IndexLinear[criterion]
  %59 : Float(1, 1, 10001) = onnx::MatMul(%55, %58), scope: RNNModel/IndexLinear[criterion]
  %60 : Float(1, 1, 10001) = onnx::Add(%59, %8), scope: RNNModel/IndexLinear[criterion]
  %61 : Long() = onnx::Constant[value={-1}]()
  %62 : Dynamic = onnx::Shape(%60), scope: RNNModel/IndexLinear[criterion]
  %63 : Long() = onnx::Gather[axis=0](%62, %61), scope: RNNModel/IndexLinear[criterion]
  %64 : Long() = onnx::Constant[value={-1}]()
  %65 : Dynamic = onnx::Unsqueeze[axes=[0]](%64), scope: RNNModel/IndexLinear[criterion]
  %66 : Dynamic = onnx::Unsqueeze[axes=[0]](%63), scope: RNNModel/IndexLinear[criterion]
  %67 : int[] = onnx::Concat[axis=0](%65, %66), scope: RNNModel/IndexLinear[criterion]
  %68 : Float(1, 10001) = onnx::Reshape(%60, %67), scope: RNNModel/IndexLinear[criterion]
  %69 : Dynamic = onnx::Constant[value={-1}](), scope: RNNModel/IndexLinear[criterion]
  %70 : Long(1) = onnx::Reshape(%57, %69), scope: RNNModel/IndexLinear[criterion]
  %71 : Float(1, 10001) = onnx::LogSoftmax[axis=1](%68), scope: RNNModel/IndexLinear[criterion]/CrossEntropyLoss[ce]
  %72 : Dynamic = prim::Undefined(), scope: RNNModel/IndexLinear[criterion]/CrossEntropyLoss[ce]
  %73 : Float(1) = onnx::ATen[ignore_index=-100, operator="nll_loss", reduction=0](%71, %70, %72), scope: RNNModel/IndexLinear[criterion]/CrossEntropyLoss[ce]
  %74 : Float(1, 1) = onnx::ATen[operator="view_as"](%73, %57), scope: RNNModel/IndexLinear[criterion]
  %75 : Float() = onnx::ReduceMean[keepdims=0](%74), scope: RNNModel
  return (%75);
}
`

**Comment by wangyunxiaa** [comment]
the onnx struct of input_names=None:
`graph torch-jit-export ( ) initializers (
  %0[INT64, 1x2]
  %1[INT64, 1]
  %2[FLOAT, 10001x200]
  %3[FLOAT, 800x200]
  %4[FLOAT, 800x200]
  %5[FLOAT, 800]
  %6[FLOAT, 800]
  %7[FLOAT, 200x200]
  %8[FLOAT, 10001]
  %9[FLOAT, 10001]
) {
  %10 = Gather(%2, %0)
  %11 = Slice[axes = [0], ends = [9223372036854775807], starts = [0]](%10)
  %12 = Slice[axes = [1], ends = [-1], starts = [0]](%11)
  %13 = Transpose[perm = [1, 0, 2]](%12)
  %14, %15 = Dropout[ratio = 0](%13)
  %16 = Constant[value = <Scalar Tensor []>]()
  %17 = Shape(%14)
  %18 = Gather[axis = 0](%17, %16)
  %19 = Constant[value = <Scalar Tensor []>]()
  %20 = Constant[value = <Scalar Tensor []>]()
  %21 = Unsqueeze[axes = [0]](%19)
  %22 = Unsqueeze[axes = [0]](%18)
  %23 = Unsqueeze[axes = [0]](%20)
  %24 = Concat[axis = 0](%21, %22, %23)
  %25 = ConstantFill[dtype = 1, input_as_shape = 1, value = 0](%24)
  %27 = Slice[axes = [0], ends = [200], starts = [0]](%3)
  %28 = Slice[axes = [0], ends = [800], starts = [600]](%3)
  %29 = Slice[axes = [0], ends = [600], starts = [200]](%3)
  %30 = Concat[axis = 0](%27, %28, %29)
  %31 = Slice[axes = [0], ends = [200], starts = [0]](%4)
  %32 = Slice[axes = [0], ends = [800], starts = [600]](%4)
  %33 = Slice[axes = [0], ends = [600], starts = [200]](%4)
  %34 = Concat[axis = 0](%31, %32, %33)
  %35 = Slice[axes = [0], ends = [200], starts = [0]](%5)
  %36 = Slice[axes = [0], ends = [800], starts = [600]](%5)
  %37 = Slice[axes = [0], ends = [600], starts = [200]](%5)
  %38 = Concat[axis = 0](%35, %36, %37)
  %39 = Slice[axes = [0], ends = [200], starts = [0]](%6)
  %40 = Slice[axes = [0], ends = [800], starts = [600]](%6)
  %41 = Slice[axes = [0], ends = [600], starts = [200]](%6)
  %42 = Concat[axis = 0](%39, %40, %41)
  %43 = Concat[axis = 0](%38, %42)
  %44 = Unsqueeze[axes = [0]](%30)
  %45 = Unsqueeze[axes = [0]](%34)
  %46 = Unsqueeze[axes = [0]](%43)
  %47, %48, %49 = LSTM[hidden_size = 200](%14, %44, %45, %46, %, %25, %25)
  %50 = Squeeze[axes = [1]](%47)
  %51, %52 = Dropout[ratio = 0](%50)
  %53 = Transpose[perm = [1, 0, 2]](%51)
  %54 = Transpose[perm = [1, 0]](%7)
  %55 = MatMul(%53, %54)
  %56 = Slice[axes = [0], ends = [9223372036854775807], starts = [0]](%0)
  %57 = Slice[axes = [1], ends = [9223372036854775807], starts = [1]](%56)
  %58 = Transpose[perm = [1, 0]](%2)
  %59 = MatMul(%55, %58)
  %60 = Add(%59, %8)
  %61 = Constant[value = <Scalar Tensor []>]()
  %62 = Shape(%60)
  %63 = Gather[axis = 0](%62, %61)
  %64 = Constant[value = <Scalar Tensor []>]()
  %65 = Unsqueeze[axes = [0]](%64)
  %66 = Unsqueeze[axes = [0]](%63)
  %67 = Concat[axis = 0](%65, %66)
  %68 = Reshape(%60, %67)
  %69 = Constant[value = <Tensor>]()
  %70 = Reshape(%57, %69)
  %71 = LogSoftmax[axis = 1](%68)
  %73 = ATen[ignore_index = -100, operator = 'nll_loss', reduction = 0](%71, %70, %)
  %74 = ATen[operator = 'view_as'](%73, %57)
  %75 = ReduceMean[keepdims = 0](%74)
  return %75
}
`

**Comment by wangyunxiaa** [comment]
I can do the export and chek the onnx model by `onnx.checker.check_model(model)` 
and `print(onnx.helper.printable_graph(model.graph))`
but  connot do `tf_rep = prepare(model)` which will cause an error:
`TypeError: Value passed to parameter 'indices' has DataType float32 not in list of allowed values: int32, int64`

**Comment by fumihwh** [comment]
`check_model` will only check your model's structure, not variables.
`input_1` value in your graph is mismatching with its dtype. 
You could use https://lutzroeder.github.io/netron/ to view your model.
![image](https://user-images.githubusercontent.com/6838753/47249839-c3f83d80-d453-11e8-8661-33de2580be48.png)

**Comment by fumihwh** [comment]
@wangyunxiaa 
I think your model's inputs are not `(inputs, lens)`. `(inputs, lens)` are just the arguments for method `forward`.
There should be some processors before you pass `(inputs, lens)` to your model.
You should check `forward` method to find out real inputs.

**Comment by fumihwh** [comment]
@wangyunxiaa 
![image](https://user-images.githubusercontent.com/6838753/47250007-54d01880-d456-11e8-9cc0-512ee0661a57.png)
From above screen shot, I advise you do following to export.
```
inputs = torch.LongTensor([[1, 2]])
lens = torch.LongTensor([1])

output = lang_model.forward(inputs, lens)

input_names = ["input_1", "input_2"] + ["learned_%d" % i for i in range(8)]
output_names = ["output"]

dummy_input_1, dummy_input_2 = torch.LongTensor([[10001, 200]]), torch.LongTensor([[800, 200]])
torch.onnx.export(lang_model, (dummy_input_1, dummy_input_2), "lmmodel.onnx", verbose=True, input_names=input_names, output_names=output_names)
```

**Comment by wangyunxiaa** [comment]
@fumihwh Thank you very much,
It is not just (inputs,lens) of the actual inputs for the model, in fact the inputs are as followings:
`data, target, length = process_data(data_batch, cuda=True, sep_target=False)
            loss= model(data, length.cuda())`
when I do a fake input to the model,I was not do the "process_data" function, just feed another input like the data_type of the "process_data" function's outputs. 
the process_data() function do a processing of the origin inputs:
`def process_data(data_batch, cuda=False, sep_target=True):
    """A data pre-processing util which construct the input `Variable` for model

    Args:
        - data_batch: a batched data from `PaddedDataset`
        - cuda: indicates whether to put data into GPU
        - sep_target: return separated input and target if turned on

    Returns:
        - input: the input data batch
        - target: target data if `sep_target` is True, else a duplicated input
        - effective_length: the useful sentence length for loss computation <s> is ignored
        """

    batch_sentence, length = data_batch   #data_batch是一个元组？？
    if cuda:
        batch_sentence = batch_sentence.cuda()
        length = length.cuda()

    # cut the padded sentence to max sentence length in this batch
    max_len = length.max()
    batch_sentence = batch_sentence[:, :max_len]

    # the useful sentence length for loss computation <s> is ignored
    effective_length = length - 1

    if sep_target:
        data = batch_sentence[:, :-1]
        target = batch_sentence[:, 1:]
    else:
        data = batch_sentence
        target = batch_sentence

    data = Variable(data.contiguous())
    target = Variable(target.contiguous(), requires_grad=False)
    effective_length = Variable(effective_length)

    return data, target, effective_length`
Does this way of processing data affect the result?

**Comment by wangyunxiaa** [comment]
@fumihwh Thank you very much.
My model's inputs are really not (inputs, lens),There is another process of the raw input as following:
`data, target, length = process_data(data_batch, cuda=True, sep_target=False)
            loss= model(data, length.cuda())`
the process_data function used to transform the input text to word_id and the length of the text after word-split from the dictionary, I just give a fack input of (word_id,length) so,the processing is omitted.
I want to know, does this affect the final result of the model convert?
by the way, the processing function is as followings:
`def process_data(data_batch, cuda=False, sep_target=True):
    """A data pre-processing util which construct the input `Variable` for model

    Args:
        - data_batch: a batched data from `PaddedDataset`
        - cuda: indicates whether to put data into GPU
        - sep_target: return separated input and target if turned on

    Returns:
        - input: the input data batch
        - target: target data if `sep_target` is True, else a duplicated input
        - effective_length: the useful sentence length for loss computation <s> is ignored
        """

    batch_sentence, length = data_batch   #data_batch是一个元组？？
    if cuda:
        batch_sentence = batch_sentence.cuda()
        length = length.cuda()

    # cut the padded sentence to max sentence length in this batch
    max_len = length.max()
    batch_sentence = batch_sentence[:, :max_len]

    # the useful sentence length for loss computation <s> is ignored
    effective_length = length - 1

    if sep_target:
        data = batch_sentence[:, :-1]
        target = batch_sentence[:, 1:]
    else:
        data = batch_sentence
        target = batch_sentence

    data = Variable(data.contiguous())
    target = Variable(target.contiguous(), requires_grad=False)
    effective_length = Variable(effective_length)

    return data, target, effective_length`

**Comment by wangyunxiaa** [comment]
I am confused that, what is the difference between the input of model and the arguments for method forward? the original input of text is processed by "process_data" and converted to word_id and the length of the text:
`data, target, length = process_data(data_batch, cuda=True, sep_target=False)
            loss= model(data, length.cuda())`
If I just feed the forward with `(inputs = torch.LongTensor([[1, 2]])
lens = torch.LongTensor([1]))`, where is the problem?
process_data function:
`def process_data(data_batch, cuda=False, sep_target=True):
    """A data pre-processing util which construct the input `Variable` for model

    Args:
        - data_batch: a batched data from `PaddedDataset`
        - cuda: indicates whether to put data into GPU
        - sep_target: return separated input and target if turned on

    Returns:
        - input: the input data batch
        - target: target data if `sep_target` is True, else a duplicated input
        - effective_length: the useful sentence length for loss computation <s> is ignored
        """

    batch_sentence, length = data_batch
    if cuda:
        batch_sentence = batch_sentence.cuda()
        length = length.cuda()

    # cut the padded sentence to max sentence length in this batch
    max_len = length.max()
    batch_sentence = batch_sentence[:, :max_len]

    # the useful sentence length for loss computation <s> is ignored
    effective_length = length - 1

    if sep_target:
        data = batch_sentence[:, :-1]
        target = batch_sentence[:, 1:]
    else:
        data = batch_sentence
        target = batch_sentence

    data = Variable(data.contiguous())
    target = Variable(target.contiguous(), requires_grad=False)
    effective_length = Variable(effective_length)

    return data, target, effective_length`

**Comment by wangyunxiaa** [comment]
@fumihwh  
Thanks,
I have a try and found that,it is because there has another process in my code `lang_model.eval()` 
when I delete the line of the code, Variable and LongTensor input all can work, and the input is correct in the onnx's graph(if added the line,Variable also cannot). 
May be I should not use the line of code, it changed the model to test mode.

**Comment by wangyunxiaa** [comment]
@fumihwh 
Hi, I have another question:
I am confused that the pre-trained pytorch model's forward function does not have parameter of lstm state, however in tensorflow the state should be feed to the net,when I do the convert how does onnx deal with this problem,and my lstm layer cause an error:
`ValueError: Shape must be rank 1 but is rank 2 for 'concat_10' (op: 'ConcatV2') with input shapes: [800], [200,200], [].`
the onnx struct 
`graph(%input_1 : Long(1, 2)
      %input_2 : Long(1)
      %learned_0 : Float(10001, 200)
      %learned_1 : Float(800, 200)
      %learned_2 : Float(800, 200)
      %learned_3 : Float(800)
      %learned_4 : Float(800)
      %learned_5 : Float(200, 200)
      %learned_6 : Float(10001)
      %learned_7 : Float(10001))`
 does not have the parameter input about lstm state,I think the input shape [200,200] is the state input, but i cannot get the inference to feed zero state to it, in pytorch it is automaticlly assigned,however, in tensorflow it is not, how does onnx solve this problem?

**Comment by fumihwh** [comment]
@wangyunxiaa 
In tf, you could not feed states, they will be set to 0.

**Comment by wangyunxiaa** [comment]
@fumihwh 
Thanks, 
In this way, the tf model can only process one all sequence at a time，so the numstep parameter is undefined, does it mean that the input shape of tf model is [1, -1, dim]  which correspond with (batch-size, num-step,feature-dim) ?

**Comment by wangyunxiaa** [comment]
the pytorch model's parameter are as followings:
`encoder.weight torch.Size([10001, 200])
rnn.weight_ih_l0 torch.Size([800, 200])
rnn.weight_hh_l0 torch.Size([800, 200])
rnn.bias_ih_l0 torch.Size([800])
rnn.bias_hh_l0 torch.Size([800])
projection.weight torch.Size([200, 200])
criterion.bias torch.Size([10001])
criterion.noise torch.Size([10001])
criterion.emb.weight torch.Size([10001, 200])
`
the onnx net's struct is as following:
`graph torch-jit-export (
  %input_1[INT64, 1x2]
) initializers (
  %input_2[INT64, 1]
  %learned_0[FLOAT, 10001x200]
  %learned_1[FLOAT, 800x200]
  %learned_2[FLOAT, 800x200]
  %learned_3[FLOAT, 800]
  %learned_4[FLOAT, 800]
  %learned_5[FLOAT, 200x200]
  %learned_6[FLOAT, 10001]
  %learned_7[FLOAT, 10001]
) {
  %10 = Gather(%learned_0, %input_1)
  %11 = Slice[axes = [0], ends = [9223372036854775807], starts = [0]](%10)
  %12 = Slice[axes = [1], ends = [-1], starts = [0]](%11)
  %13 = Slice[axes = [0], ends = [9223372036854775807], starts = [0]](%10)
  %14 = Slice[axes = [1], ends = [9223372036854775807], starts = [1]](%13)
  %15 = Transpose[perm = [1, 0, 2]](%12)
  %16, %17 = Dropout[ratio = 0](%15)
  %18 = Constant[value = <Scalar Tensor []>]()
  %19 = Shape(%16)
  %20 = Gather[axis = 0](%19, %18)
  %21 = Constant[value = <Scalar Tensor []>]()
  %22 = Constant[value = <Scalar Tensor []>]()
  %23 = Unsqueeze[axes = [0]](%21)
  %24 = Unsqueeze[axes = [0]](%20)
  %25 = Unsqueeze[axes = [0]](%22)
  %26 = Concat[axis = 0](%23, %24, %25)
  %27 = ConstantFill[dtype = 1, input_as_shape = 1, value = 0](%26)
  %29 = Slice[axes = [0], ends = [200], starts = [0]](%learned_1)
  %30 = Slice[axes = [0], ends = [800], starts = [600]](%learned_1)
  %31 = Slice[axes = [0], ends = [600], starts = [200]](%learned_1)
  %32 = Concat[axis = 0](%29, %30, %31)
  %33 = Slice[axes = [0], ends = [200], starts = [0]](%learned_2)
  %34 = Slice[axes = [0], ends = [800], starts = [600]](%learned_2)
  %35 = Slice[axes = [0], ends = [600], starts = [200]](%learned_2)
  %36 = Concat[axis = 0](%33, %34, %35)
  %37 = Slice[axes = [0], ends = [200], starts = [0]](%learned_3)
  %38 = Slice[axes = [0], ends = [800], starts = [600]](%learned_3)
  %39 = Slice[axes = [0], ends = [600], starts = [200]](%learned_3)
  %40 = Concat[axis = 0](%37, %38, %39)
  %41 = Slice[axes = [0], ends = [200], starts = [0]](%learned_4)
  %42 = Slice[axes = [0], ends = [800], starts = [600]](%learned_4)
  %43 = Slice[axes = [0], ends = [600], starts = [200]](%learned_4)
  %44 = Concat[axis = 0](%41, %42, %43)
  %45 = Concat[axis = 0](%40, %44)
  %46 = Unsqueeze[axes = [0]](%32)
  %47 = Unsqueeze[axes = [0]](%36)
  %48 = Unsqueeze[axes = [0]](%45)
  %49, %50, %51 = LSTM[hidden_size = 200](%16, %46, %47, %48, %, %27, %27)
  %52 = Squeeze[axes = [1]](%49)
  %53, %54 = Dropout[ratio = 0](%52)
  %55 = Transpose[perm = [1, 0, 2]](%53)
  %56 = Transpose[perm = [1, 0]](%learned_5)
  %57 = MatMul(%55, %56)
  %58 = Slice[axes = [0], ends = [9223372036854775807], starts = [0]](%input_1)
  %59 = Slice[axes = [1], ends = [9223372036854775807], starts = [1]](%58)
  %60 = Constant[value = <Scalar Tensor []>]()
  %61 = Shape(%57)
  %62 = Gather[axis = 0](%61, %60)
  %63 = Constant[value = <Scalar Tensor []>]()
  %64 = Unsqueeze[axes = [0]](%63)
  %65 = Unsqueeze[axes = [0]](%62)
  %66 = Concat[axis = 0](%64, %65)
  %67 = Reshape(%57, %66)
  %68 = Constant[value = <Scalar Tensor []>]()
  %69 = Shape(%59)
  %70 = Gather[axis = 0](%69, %68)
  %71 = Constant[value = <Scalar Tensor []>]()
  %72 = Shape(%59)
  %73 = Gather[axis = 0](%72, %71)
  %74 = Constant[value = <Tensor>]()
  %75 = Reshape(%59, %74)
  %76 = Constant[value = <Scalar Tensor []>]()
  %77 = Shape(%14)
  %78 = Gather[axis = 0](%77, %76)
  %79 = Constant[value = <Scalar Tensor []>]()
  %80 = Unsqueeze[axes = [0]](%79)
  %81 = Unsqueeze[axes = [0]](%78)
  %82 = Concat[axis = 0](%80, %81)
  %83 = Reshape(%14, %82)
  %84 = Gather[axis = 0](%learned_6, %75)
  %85 = Mul(%83, %67)
  %86 = ReduceSum[axes = [1], keepdims = 0](%85)
  %87 = Add(%86, %84)
  %88 = Unsqueeze[axes = [0]](%70)
  %89 = Unsqueeze[axes = [0]](%73)
  %90 = Concat[axis = 0](%88, %89)
  %91 = Reshape(%87, %90)
  %92 = Constant[value = <Scalar Tensor []>]()
  %93 = Sub(%91, %92)
  %94 = Exp(%93)
  %95 = Log(%94)
  %output = Neg(%95)
  return %output
}
`
but i have an error
`Traceback (most recent call last):
  File "/home/yunxiawang/anaconda2/envs/py36_torch_onnx_source/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1576, in _create_c_op
    c_op = c_api.TF_FinishOperation(op_desc)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Shape must be rank 1 but is rank 2 for 'concat_10' (op: 'ConcatV2') with input shapes: [800], [200,200], [].`
I do not know where the op is?  but only the lstm'state and projection'weight has the shape of (200,200)

**Comment by fumihwh** [comment]
@wangyunxiaa 
We do not know every thing about your task. 
The error log doesn't show there is any converting bug in onnx-tf.
If you think this is a bug, please give more details. 
For example, `concat_10`'s inputs names. And then check whether match their shapes in onnx graph.

**Comment by fumihwh** [comment]
@wangyunxiaa 
If you still have problem, feel free to reopen this.
