### ISSUE TITLE
Super-resolution network produces incorrect results

### ISSUE THREAD

**Issue by jamesr66a** [onnx/onnx-tensorflow#3]
Hey folks,

I'm writing up a tutorial for importing an ONNX graph to TF using this library. I'm using a super-resolution network as an example. Here's my draft of the tutorial: https://gist.github.com/jamesr66a/7c2c18e1479d086d28f92217975111ec

Unfortunately, when I run the Tensorflow imported network, I get a bizarre image result: 

Before
![image](https://user-images.githubusercontent.com/4685384/32922548-93e074b2-cae7-11e7-9115-a0a3cf5c28f4.png)

After
![image](https://user-images.githubusercontent.com/4685384/32922550-97086794-cae7-11e7-8da7-3cbebbeed5e6.png)

Not quite sure what's going on here, but here's visualizations of the network topologies:

ONNX model I imported
![super_resolution](https://user-images.githubusercontent.com/4685384/32922741-922ca5d6-cae8-11e7-9c2a-1c5ce94f1aa6.png)

Tensorflow model that was produced
![image](https://user-images.githubusercontent.com/4685384/32922668-2f00271c-cae8-11e7-926a-eb20b242e650.png)

The ONNX serialized network and source image (respectively) can be found here: https://github.com/onnx/tutorials/blob/master/tutorials/assets/super_resolution.onnx https://github.com/onnx/tutorials/blob/master/tutorials/assets/super-res-input.jpg. Additionally we have an mxnet tutorial that produces the correct result you can look at for comparison: https://github.com/onnx/tutorials/blob/master/tutorials/OnnxMxnetImport.ipynb

Could you all take a look?

**Comment by tjingrant** [comment]
Hi @jamesr66a we will take a look at your code shortly. 

In the mean time, if you are curious, you can actually see where it went wrong (this is what we will be doing anyways) by modifying and running this script here: https://github.com/onnx/onnx-tensorflow/blob/master/test/test_model_large_stepping.py .

This script compares the results of tf backend with caffe2 backend op by op. It is very useful when debugging a backend problem.

**Comment by tjingrant** [comment]
@jamesr66a we took a look at your model. First of all, thanks for writing up this interesting tutorial! 

Secondly, your onnx model definition says that your input 1 is type FLOAT but you are actually passing an array of UINT8. So that's problematic in the first place.

Thirdly, after we type-casted your input to be float, we stepped your model with Caffe2 backend (our master build vs caffe2 backend master build) with a relative tolerance of 1e-2, this is what we got layer by layer:

```
11 results of this layer are correct within tolerence.
12 results of this layer are correct within tolerence.
13 results of this layer are correct within tolerence.
15 mismatch with percentage  0.00214868662309 %
16 mismatch with percentage  0.00236666932398 %
17 mismatch with percentage  0.000903071189413 %
19 mismatch with percentage  0.00118333466199 %
20 mismatch with percentage  0.000685088488524 %
21 mismatch with percentage  0.000373684630105 %
23 results of this layer are correct within tolerence.
24 results of this layer are correct within tolerence.
25 results of this layer are correct within tolerence.
26 results of this layer are correct within tolerence.
27 results of this layer are correct within tolerence.
```
So caffe2 backend and our backend agree on the output of this model. But the output is still funny... So either I mishandled your input or your model weight is problematic. Given that it works with MXNet, the former is more likely.

**Comment by tjingrant** [comment]
FYI, this is from caffe2 backend after type-casting your input to float.
![super_res_output](https://user-images.githubusercontent.com/6410074/32958504-bcbbdbf6-cb8c-11e7-8612-5f2b89046e6b.jpg)

**Comment by jamesr66a** [comment]
@tjingrant Thanks so much for looking into this! The problem was indeed related to types, namely in how the network result `big_doggy` needed to be casted back to uint8 before being fed into `Image.fromarray`. I've fixed the issue and now I think the tutorial is ready to go live! :)

**Comment by jamesr66a** [comment]
We're live! https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb
