### ISSUE TITLE
saving to TF model

### ISSUE THREAD

**Issue by lukemurray** [onnx/onnx-tensorflow#30]
Not really an issue sorry. But I was wondering if it would be possible to use this to load an onnx model and save it with TF as the TF .meta format (`export_meta_graph`)?

I gave it a quick try, but it seems it does set up the default TF graph.

Thanks

**Comment by lukemurray** [comment]
OK this appears to work.

here is some code for others that may want to do this. `onnx_tf.backend.prepare` was the key

```python
import onnx_tf
import onnx
import tensorflow as tf
import argparse

def main():
    parser = argparse.ArgumentParser()
    parser.add_argument('model', help='onnx file')
    args = parser.parse_args()

    model = onnx.load(args.model)
    backend = onnx_tf.backend.prepare(model)
    with tf.Session() as sess:
        meta_graph_def = tf.train.export_meta_graph(filename='output_mode.meta')

if __name__ == "__main__":
    main()
```

**Comment by cysmith** [comment]
@lukemurray The code you posted exported a .meta but it was empty (39 bytes). I was able to solve this by:
```
import onnx
import onnx_tf.backend as tf_backend
import tensorflow as tf

ONNX_MODEL = 'test_net.onnx'
TF_MODEL = 'test_net.meta'

def onnx2tf():
	model = onnx.load(ONNX_MODEL)
	tf_rep = tf_backend.prepare(model)
	tf_rep.export_graph(path=TF_MODEL)

onnx2tf()
```

**Comment by parth1595** [comment]
Can we get other files similar to like this you have created .meta file. I would like to have all the tensorflow model files if we can (eg. .meta, .data, .ckpt ) which we generated using Saver method in tensorflow.

**Comment by alew3** [comment]
I'm trying to convert this file into a tensorflowjs mode using tfjsconverter and therefore also need the checkpoints and meta file and discover the name of the output layer. Any way for this to work?
