### ISSUE TITLE
change one dimetion of the onnx model's input to ? cause an error "ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None."

### ISSUE THREAD

**Issue by wangyunxiaa** [onnx/onnx-tensorflow#300]
The original input shape is (10,1,1000) correspond to (num_step, batchsize,dim) 
After convert the pytorch model to onnx,  I just do the modify as following:
`onnx_model.graph.input[0].type.tensor_type.shape.dim[0].dim_param = '?'` 
in order to support the dynamic input. 
But when i do `tf_rep = prepare(onnx_model, device="cpu")` 
to import onnx model to tf, I get an error 
`ValueError: Input size (depth of inputs) must be accessible via shape inference, but saw value None.`

I am tracking the source code,and found that the input of lstm layer is 
`Tensor("Reshape_1:0", shape=(?, ?, ?), dtype=float32)`
I just changed one dimention of the input, why all 3 dimentions changed to None?

**Comment by fumihwh** [comment]
@wangyunxiaa 
LSTM doesn't have `Reshape` node. Maybe You do reshape before pass to LSTM.
I assume if you reshape a Tensor with dynamic dim, all dims of reshape output would be dynamic.
onnx-tf will only change corresponding dim if you see the source at `backend.py` L106
```
shape = list(
            d.dim_value if (d.dim_value > 0 and d.dim_param == "") else None
            for d in value_info.type.tensor_type.shape.dim)
```
