### ISSUE TITLE
Unable to install onnx-tf

### ISSUE THREAD

**Issue by namanmaheshwari** [onnx/onnx-tensorflow#304]
I am getting the following error while trying to install onnx-tf (sudo git clone git@github.com:onnx/onnx-tensorflow.git) -

**_Cloning into 'onnx-tensorflow'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists._**

Please help me resolve this asap. Thank you.

**Comment by tjingrant** [comment]
@namanmaheshwari looks like your ssh is wrongly configured.

You can fix your ssh or try using HTTPS to clone the repository:
`git clone https://github.com/onnx/onnx-tensorflow.git`

BTW, no need to use sudo for git (unless you have permission issue with writing the current directory).

**Comment by namanmaheshwari** [comment]
Great, I'm able to install it now. Thanks!
