### ISSUE TITLE
Is there a way to save your model as a Keras .h5 file?

### ISSUE THREAD

**Issue by Suhail** [onnx/onnx-tensorflow#317]
Background - I am following this tutorial: https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb

Is there a way to save the model after you load it to a Keras .h5 file?

**Comment by tjingrant** [comment]
It's not going to be easy. You are essentially asking, can you save a tensorflow graph as a .5 file. 

Searching around lands me here https://github.com/keras-team/keras/issues/5273 .

**Comment by tjingrant** [comment]
Feel free to re-open this issue if you think there's anything we can help more. If not, I think this issue is not relevant to onnx-tf.
