### ISSUE TITLE
AddN version 8 Not implemented

### ISSUE THREAD

**Issue by hondaathma** [onnx/onnx-tensorflow#335]
**Describe the bug**

When converting my .pb model from TF to onnyx I get this error.
NotImplementedError: AddN version 8 is not implemented.

Could you please tell what layer is AddN version 8? Or how to fix this?

**Python, ONNX, ONNX-TF, Tensorflow version**

Python version:
2.7.6 (default, Nov 13 2018, 12:45:42) 
[GCC 4.8.4]
ONNX version:
1.3.0
ONNX-TF version:
1.2.0
Tensorflow version:
1.4.0

**Comment by fumihwh** [comment]
@hondaathma Add
```
  @classmethod
  def version_8(cls, node, **kwargs):
    return cls.basic_math_op(node, **kwargs)
```
to `add_n.py`.

**Comment by hondaathma** [comment]
@fumihwh Thank you so much! issue resolved. However I also have another NotImplementedError: ResizeBilinear is not implemented error. Could you lease let me know if this is implemented?
