### ISSUE TITLE
Sample Mnist model can run correctly, but get "Cannot reshape a tensor with 64 elements to shape [1,112,1,1]" error with inception v1 model

### ISSUE THREAD

**Issue by Ma-Dan** [onnx/onnx-tensorflow#337]
I trained Mnist sample model using assets/tf-train-mnist.py and converted to pb, then run test in OnnxTensorflowExport.ipynb, although get some "UserWarning: Rsqrt doesn't have ONNX_OP." error in model conversion step, but inference can run and output a classification result.
Then I tried inception v1 model, the pretrained weight is downloaded from http://download.tensorflow.org/models/inception_v1_2016_08_28.tar.gz
Then convert to pb file using the following code
```
import tensorflow as tf
import numpy as np

slim = tf.contrib.slim
from tensorflow.contrib.slim.python.slim.nets import inception_v1
from tensorflow.python.framework import graph_util

x = tf.placeholder("float", shape=[None, 224, 224, 3], name='input')
with slim.arg_scope(inception_v1.inception_v1_arg_scope()):
    logits, end_points = inception_v1.inception_v1(x, num_classes=1001, dropout_keep_prob=1.0, is_training=False)
predictions = tf.nn.softmax(logits, name="output")
saver = tf.train.Saver()
with tf.Session() as sess:
    saver.restore(sess, "inception_v1.ckpt")

    output_graph_def = graph_util.convert_variables_to_constants(
        sess,
        sess.graph.as_graph_def(add_shapes=True),
        ['output']
    )
    with tf.gfile.GFile("inception_v1.pb", "wb") as f:
        f.write(output_graph_def.SerializeToString())
```

Inception V1 pb file can convert to onnx format in model conversion step, also get some "UserWarning: Rsqrt doesn't have ONNX_OP." error, but can not run in inference step.
At line tf_rep = prepare(model), get the following error:
```
ValueError: Cannot reshape a tensor with 64 elements to shape [1,112,1,1] (112 elements) for 'Reshape' (op: 'Reshape') with input shapes: [64], [4] and with input tensors computed as partial shapes: input[1] = [1,112,1,1].
```

Could you please help solve this error?
Thank you!

**Comment by fumihwh** [comment]
@Ma-Dan Could you try fixed shape more than dynamic one `[None, 224, 224, 3]` first?

**Comment by Ma-Dan** [comment]
I just tried save pb with Shape [1, 224, 224, 3], still get the same error.

**Comment by fumihwh** [comment]
#338 Try this PR

**Comment by Ma-Dan** [comment]
@fumihwh This PR solved this issue, and ONNX model get the same result as the original tensorflow! But dynamic shape [None, 224, 224, 3] should be used when freezing to pb, using Shape [1, 224, 224, 3] in freezing will cause an incorrect output which is all 1. in softmax array.
Thanks a lot!

**Comment by fumihwh** [comment]
@Ma-Dan Did you try dynamic shape also?

**Comment by Ma-Dan** [comment]
@fumihwh Yes, I got incorrect output from static shape [1, 224, 224, 3], and print(onnx_model.graph.node[0]) also get weired output with static shape, shown below:
```
input: "InceptionV1/Conv2d_1a_7x7/weights"
output: "InceptionV1/Conv2d_1a_7x7/weights/read"
name: "InceptionV1/Conv2d_1a_7x7/weights/read"
op_type: "Identity"
```
