### ISSUE TITLE
 NotImplementedError: BatchNormalization version 9 is not implemented.

### ISSUE THREAD

**Issue by lookup1980** [onnx/onnx-tensorflow#358]
**Describe the bug**

I got an error when converting a model to TensorFlow.

**To Reproduce**

What I am doing is:

1. A PyTorch model is converted to ONNX model (PyTorch version is 1.0.0 GPU version):
`torch.onnx.export(model, img, "model.onnx", verbose=True)
`

1. Loaded the ONNX model and verified it:
`onnx.checker.check_model(model)`

1. ONNX model is converted to TensorFlow model:
`onnx-tf convert -t tf -i model.onnx -o model.pb  
`

The error message is:
`NotImplementedError: BatchNormalization version 9 is not implemented.`

**ONNX model file**

Can't share the model.

**Python, ONNX, ONNX-TF, Tensorflow version**
Python version:
2.7.15
ONNX version:
1.3.0, pulled today and built from source
ONNX-TF version:
1.2.1, pip install onnx-tf
Tensorflow version:
1.12.0, GPU version

**Comment by lookup1980** [comment]
I got an error when converting a model to TensorFlow.
What I am doing is:

1. A PyTorch model is converted to ONNX model (PyTorch version is 1.0.0 GPU version):
`torch.onnx.export(model, img, "model.onnx", verbose=True)
`

1. Loaded the ONNX model and verified it:
`onnx.checker.check_model(model)`

1. ONNX model is converted to TensorFlow model:
`onnx-tf convert -t tf -i model.onnx -o model.pb  
`
onnx-tf is installed by pip: pip install onnx-tf 
ONNX is intalled from source, and the ONNX code was pulled today and the version is 1.3.0

The error message is:
`NotImplementedError: BatchNormalization version 9 is not implemented.`


Python version:
2.7.15
ONNX version:
1.3.0, pulled today and built from source
ONNX-TF version:
1.2.1, pip install onnx-tf
Tensorflow version:
1.12.0, GPU version

**Comment by ikasnep** [comment]
I am having the same problem on 
python 3.6.6
tf 1.11.0
onnx and onnx-tf the same as above

**Comment by hyenal** [comment]
@ikasnep  are you also using PyTorch 1.0.0 ? I have the same issue having saved a model in this version of Torch with tensorflow 1.5.0 and python 2.7.5.

**Comment by ikasnep** [comment]
Yes,  PyTorch 1.0.0

**Comment by shridharkini6** [comment]
Yes ,
tensorflow-gpu==1.5.0
onnx==1.4.1
python 2.7.12
onnx-tf installed from source

**Comment by shridharkini6** [comment]
@tjingrant any updates on this...

**Comment by tjingrant** [comment]
@shridharkini6 it's in for review (https://github.com/onnx/onnx-tensorflow/pull/361), should be checked in soon.

**Comment by davidenitti** [comment]
@tjingrant thank you for the fix, is it possible to fix also Cast version 9 is not implemented.?
thanks

**Comment by tjingrant** [comment]
@davidenitti sure thing. Would you create another issue for tracking purpose?

**Comment by davidenitti** [comment]
sure

> @davidenitti sure thing. Would you create another issue for tracking purpose?

sure, I made it here https://github.com/onnx/onnx-tensorflow/issues/362
thanks

**Comment by lookup1980** [comment]
Tried the tip of master, and it works!
I'll close this issue. 
Thank you!

**Comment by akshayy29** [comment]
> Tried the tip of master, and it works!
> I'll close this issue.
> Thank you!

hey! what did you do? I've got the same problem.

**Comment by akshayy29** [comment]
> **Describe the bug**
> 
> I got an error when converting a model to TensorFlow.
> 
> **To Reproduce**
> 
> What I am doing is:
> 
> 1. A PyTorch model is converted to ONNX model (PyTorch version is 1.0.0 GPU version):
>    `torch.onnx.export(model, img, "model.onnx", verbose=True) `
> 2. Loaded the ONNX model and verified it:
>    `onnx.checker.check_model(model)`
> 3. ONNX model is converted to TensorFlow model:
>    `onnx-tf convert -t tf -i model.onnx -o model.pb   `
> 
> The error message is:
> `NotImplementedError: BatchNormalization version 9 is not implemented.`
> 
> **ONNX model file**
> 
> Can't share the model.
> 
> **Python, ONNX, ONNX-TF, Tensorflow version**
> Python version:
> 2.7.15
> ONNX version:
> 1.3.0, pulled today and built from source
> ONNX-TF version:
> 1.2.1, pip install onnx-tf
> Tensorflow version:
> 1.12.0, GPU version


hey! what did you do? I've got the same problem.

**Comment by jerpint** [comment]
I had the same problem, managed to fix it by installing from source (the fix probably isn't on pip yet).

To do this:

```
pip uninstall onnx-tf
cd && git clone git@github.com:onnx/onnx-tensorflow.git && cd onnx-tensorflow
pip install -e .
```
