### ISSUE TITLE
NotImplementedError: Cast version 9 is not implemented.

### ISSUE THREAD

**Issue by davidenitti** [onnx/onnx-tensorflow#362]
**Describe the bug**

NotImplementedError: Cast version 9 is not implemented.

**To Reproduce**

onnx-tf convert -t tf -i net.onnx -o net.pb

where net.onnx contains a Cast v9 operation (I suppose)

**Python, ONNX, ONNX-TF, Tensorflow version**
Python version:
3.6.7 (default, Oct 25 2018, 09:16:13) 
[GCC 5.4.0 20160609]
ONNX version:
1.4.1
ONNX-TF version:
1.2.1
Tensorflow version:
1.12.0

**Comment by chinhuang007** [comment]
The fix is merged.
