### ISSUE TITLE
ConstantFill is removed from ONNX 1.4

### ISSUE THREAD

**Issue by chinhuang007** [onnx/onnx-tensorflow#370]
The experimental ConstantFill op is totally removed from ONNX 1.4, onnx/onnx#1434. This causes issues in frontend and backend handlers. Since ConstantFill is gone from ONNX code base, we can't declare it as an ONNX op anymore.

Shall we simply delete our backend handler for ConstantFill and rework our frontend handler for tf.fill?

I am not sure how to support backward compatibility when an op is completely removed from ONNX. Since "The "experimental op" concept will be removed from ONNX standard in next release (1.5)", based on https://github.com/onnx/onnx/issues/1756, we probably should stop supporting experimentatl ops as well. Suggestions are welcome.

**Comment by houseroad** [comment]
You can export the model into some special down, such as 'onnx-tf' domain. I also created a whitelist in the onnx checker for those removed Experimental ops. If you think some operator is necessary for the model, and general enough, we should add it to ONNX standard. :-)

**Comment by chinhuang007** [comment]
We will stop supporting experimental ops. And recommend adding the ones we see necessary to ONNX standard as suggested. Therefore close this issue.
