### ISSUE TITLE
onnx export to tf error

### ISSUE THREAD

**Issue by uhvardhan** [onnx/onnx-tensorflow#374]
I am trying to export a onnx model to tf. Here is the code:

`import onnx
from onnx_tf.backend import prepare

##### Load the ONNX file
model = onnx.load('model.onnx')

##### Import the onnx model to Tensorflow
tf_rep = prepare(model)

##### Input nodes to the model
print('inputs:', tf_rep.inputs)

##### Output nodes from the model
print('outputs:', tf_rep.outputs)

##### All nodes in the model
print('tensor_dict:')
print(tf_rep.tensor_dict)`

I am following the steps in the tutorial.[Tutorial](https://github.com/onnx/tutorials/blob/master/tutorials/PytorchTensorflowMnist.ipynb)

I get the following error: 
`Traceback (most recent call last):
  File "/tmp/pycharm_project_896/utils/onnx2tf.py", line 8, in <module>
    tf_rep = prepare(model)
  File "/home/harsh/git_clone/onnx-tensorflow/onnx_tf/backend.py", line 74, in prepare
    super(TensorflowBackend, cls).prepare(model, device, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/onnx/backend/base.py", line 65, in prepare
    onnx.checker.check_model(model)
  File "/usr/local/lib/python2.7/dist-packages/onnx/checker.py", line 82, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: model with IR version < 3 cannot have opset_import specified`

Can anyone explain where I am going wrong?

Thanks

**Comment by fumihwh** [comment]
@uhvardhan @jinfei3459 
Did you still have this problem?

**Comment by jinfei3459** [comment]
yes

**Comment by fumihwh** [comment]
@jinfei3459 Which branch of onnx-tensorflow you are using? Or do you install onnx-tf by source or pypi?
