### ISSUE TITLE
How to import ONNX file to Tensorflow Serving

### ISSUE THREAD

**Issue by muyueyue** [onnx/onnx-tensorflow#38]
Hello everyone!

Now，I use pytorch to write a mnist and exports the model as a .proto file via ONNX. How can I import this .proto file into Tensorflow Serving and use Tensorflow Serving provide service.

Hope friends know how to solve this problem. Thank you!

**Comment by tjingrant** [comment]
Sorry for not getting back to you soon enough, but we have introduced an additional API to make this process easy. Please refer to our API documentation: https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/doc/API.md

Specifically, the API function you are looking for is:
`onnx_tf.backend_rep.TensorflowRep.export_graph`

**Comment by fancyerii** [comment]
I can use this api to export graph, But to use it in tensorflow serving, we need use SavedModel API to save the model and the signature.

**Comment by fumihwh** [comment]
@fancyerii 
Maybe this could help? https://stackoverflow.com/questions/44329185/convert-a-graph-proto-pb-pbtxt-to-a-savedmodel-for-use-in-tensorflow-serving-o

**Comment by chinhuang007** [comment]
Close since a tf pb can be converted to a SavedModel. Please reopen if anyone wants to continue the discussions.
