### ISSUE TITLE
ValidationError: No Op registered for DynamicSlice with domain_version of 10

### ISSUE THREAD

**Issue by chris19o4** [onnx/onnx-tensorflow#395]
**Describe the bug**

I got an error when trying to convert  a TensorFlow .pb model to ONNX:

---------------------------------------------------------------------------
ValidationError                           Traceback (most recent call last)
<ipython-input-22-652cf510c031> in <module>
      2     graph_def = tf.GraphDef()
      3     graph_def.ParseFromString(f.read())
----> 4     onnx_model = tensorflow_graph_to_onnx_model(graph_def, "outputs/BiasAdd", opset=0)
      5 
      6     file = open("pointnet.onnx", "wb")

~/onnx-tensorflow/onnx_tf/frontend.py in tensorflow_graph_to_onnx_model(cls, graph_def, output, opset, producer_name, graph_name, ignore_unimplemented, optimizer_passes)
    143     tf_graph = cls._make_tf_graph(graph_def, output, graph_name)
    144     return cls._make_onnx_model(tf_graph, opset, producer_name,
--> 145                                 ignore_unimplemented, optimizer_passes)
    146 
    147   @classmethod

~/onnx-tensorflow/onnx_tf/frontend.py in _make_onnx_model(cls, tf_graph, opset, producer_name, ignore_unimplemented, optimizer_passes)
    156     opset = cls._process_opset(opset)
    157     onnx_graph = cls.tensorflow_graph_to_onnx_graph(tf_graph, opset,
--> 158                                                     ignore_unimplemented)
    159     opset_imports = [make_opsetid(item[0], item[1]) for item in opset]
    160     onnx_model = make_model(

~/onnx-tensorflow/onnx_tf/frontend.py in tensorflow_graph_to_onnx_graph(cls, tf_graph, opset, ignore_unimplemented)
     91               consts=onnx_graph.consts,
     92               node_dict=dict(node_tup),
---> 93               data_type_cast_map=onnx_graph.data_type_cast_map)
     94         else:
     95           exception.OP_UNIMPLEMENTED_EXCEPT(

~/onnx-tensorflow/onnx_tf/handlers/frontend_handler.py in handle(cls, node, **kwargs)
     39   @classmethod
     40   def handle(cls, node, **kwargs):
---> 41     return super(FrontendHandler, cls).handle(node, **kwargs)
     42 
     43   @classmethod

~/onnx-tensorflow/onnx_tf/handlers/handler.py in handle(cls, node, **kwargs)
     58     if ver_handle:
     59       cls.args_check(node, **kwargs)
---> 60       return ver_handle(node, **kwargs)
     61     exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
     62     return None

~/onnx-tensorflow/onnx_tf/handlers/frontend/strided_slice.py in version_1(cls, node, **kwargs)
     50     slice_node = cls.make_node("DynamicSlice", node.inputs[0:3],
     51                                [slice_output_name + slice_suffix],
---> 52                                node.name + slice_suffix)
     53 
     54     if not need_post_processing:

~/onnx-tensorflow/onnx_tf/handlers/frontend_handler.py in make_node(cls, op_type, inputs, outputs, name, doc_string, version, should_check, **kwargs)
     72                             **kwargs)
     73     if should_check:
---> 74       cls.check_node(node, version)
     75     else:
     76       warnings.warn("Skipped check for {}.".format(node.op_type))

~/onnx-tensorflow/onnx_tf/handlers/frontend_handler.py in check_node(cls, node, version)
    175     ctx.ir_version = onnx.IR_VERSION
    176     ctx.opset_imports = {cls.DOMAIN: version}
--> 177     checker.check_node(node, ctx=ctx)
    178 
    179   @classmethod

~/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx-1.4.1-py3.6-linux-x86_64.egg/onnx/checker.py in checker(proto, ctx)
     50                         proto_type.__name__))
     51             return getattr(C, py_func.__name__)(
---> 52                 proto.SerializeToString(), ctx)
     53         return cast(FuncType, checker)
     54     return decorator

ValidationError: No Op registered for DynamicSlice with domain_version of 10

**To Reproduce**

I used the following code to convert to ONNX model:
`
with tf.gfile.GFile("frozen_model.pb", "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = tensorflow_graph_to_onnx_model(graph_def, "outputs/BiasAdd", opset=0)

    file = open("forzen_model.onnx", "wb")
    file.write(onnx_model.SerializeToString())
    file.close()
`
If necessary I can provide the .pb file.

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version:  
   3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:22:34) 
   [GCC 7.3.0]
 - ONNX version: 
   1.4.1
 - ONNX-TF version:
  1.2.1
 - Tensorflow version: 
   1.12.0

**Additional context**
Both ONNX and ONNX-TF are built from source.
I also used "sess.graph.as_graph_def(add_shapes=True)" while creating the .pb file

Thanks for input on this

**Comment by jamebozo** [comment]
Same issue... also trying to convert tensorflow to onnx

**Comment by chinhuang007** [comment]
The frontend converter is merged into tf-onnx project, https://github.com/onnx/tensorflow-onnx. Please check out the latest there.
