### ISSUE TITLE
Why is there reference to caffe2 into the backend of onnx-tf ?

### ISSUE THREAD

**Issue by LucasMahieu** [onnx/onnx-tensorflow#40]
As we can see in these link, some stuff are made in reference to caffe2 : 
https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/backend.py#L97
or 
https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/backend.py#L88

My question is why onnx-tf is related to caffe2 ? 
 
It seems to be due to copy-paste from the onnx-caffe2 backend

**Comment by tjingrant** [comment]
Hi, I copied this verbatim from onnx-caffe2 backend. I did not bother changing simply b/c this whole class, as per comment, will be moved to the ONNX main repo anyways.

**Comment by LucasMahieu** [comment]
Ok, it is what I thought.
Thanks for the reply

Maybe we could ask to add this to onnx main repo ?

**Comment by tjingrant** [comment]
Yes, for sure, if they haven't already done so.
