### ISSUE TITLE
InvalidArgumentError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [10], [10,10].

### ISSUE THREAD

**Issue by judytraj007** [onnx/onnx-tensorflow#400]
I've built onnx from the source following these steps:

```
git clone https://github.com/onnx/onnx.git
cd onnx
git submodule update --init --recursive
sudo python2.7 setup.py install
```
And onnx-tensorflow using these steps:
```
git clone git@github.com:onnx/onnx-tensorflow.git && cd onnx-tensorflow
pip install -e .
```
I've a binary classifier model saved in the onnx format using the pytorch onnx api. 
```
x_data =  [ 48,    1,    0.7,   0.2, 165,   32,   30,    8,    4,    1 ]
sample = np.array(x_data) 
sample_tensor = torch.from_numpy(sample).float()
torch.onnx.export(model, sample_tensor, "classifier.onnx", export_params=True)
```
When I try to load the model to tensorflow, this line 
`tf_rep = prepare(model)`
throws the error,  `InvalidArgumentError: Shape must be rank 2 but is rank 1 for 'MatMul' (op: 'MatMul') with input shapes: [10], [10,10].`

It's preceded by a set of warnings:

```
/Users/judyraj/Judy/pytorch-deployment/onnx-tensorflow/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op ConstantFill in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/Users/judyraj/Judy/pytorch-deployment/onnx-tensorflow/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op DynamicSlice in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/Users/judyraj/Judy/pytorch-deployment/onnx-tensorflow/onnx_tf/common/handler_helper.py:73: UserWarning: Unknown op ImageScaler in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
/Users/judyraj/Judy/pytorch-deployment/onnx-tensorflow/onnx_tf/common/handler_helper.py:70: UserWarning: Fail to get since_version of ThresholdedRelu in domain `` with max_inclusive_version=9. Set to 1.
  handler.ONNX_OP, handler.DOMAIN, version))
```

My tensorflow version is 1.13.1
Pytorch version is 0.2.2
Os : Mac OS Sierra
Python: 3.6

**Comment by chinhuang007** [comment]
The generated onnx model seems to have mismatched input shapes for matmul. You will get an error with tf.matmul with input shapes [10] and [10, 10]. Can you possibly provide the binary onnx file and sample input data for inference?

**Comment by judytraj007** [comment]
Here's a link to the onnx file, https://drive.google.com/file/d/1oFRPP8BU8GACclnVFkGbjJXlhRYW3LhU/view?usp=sharing
Btw, this works well when I convert it to caffe22
This is the line of data I'm trying to get a prediction for. x_data =  [ 48,    1,    0.7,   0.2, 165,   32,   30,    8,    4,    1 ]  
Here's the link to the dataset the model was originally trained on, https://drive.google.com/file/d/1WLiguqflfGQZnG5tnnS4-ly9eRxEtdEs/view?usp=sharing

**Comment by chinhuang007** [comment]
Pytorch has a special treatment for 1-dimentional inputs, as documented "If the first argument is 1-dimensional and the second argument is 2-dimensional, a 1 is prepended to its dimension for the purpose of the matrix multiply. After the matrix multiply, the prepended dimension is removed."

Tensorflow requires both inputs to be rank >=2, as documented "The inputs must, following any transpositions, be tensors of rank >= 2 where the inner 2 dimensions specify valid matrix multiplication arguments, and any further outer dimensions match."

Therefore what occurred is expected when the first input of matmul is a 1-dimentional tensor.

**Comment by chinhuang007** [comment]
Close the issue since the behavior is expected in Tensorflow, which does not auto-reshape inputs.

**Comment by s-inder-preet** [comment]
@judytraj007 It has been a while but if you reshape your input `sample_tensor=torch.from_numpy(sample.reshape(1,-1).float()` you will effectively change the rank of you tensor getting around the problem well described in https://github.com/onnx/onnx-tensorflow/issues/400#issuecomment-491455997
