### ISSUE TITLE
What can onnx-tensorflow be used to do

### ISSUE THREAD

**Issue by muyueyue** [onnx/onnx-tensorflow#41]
Hi, what can onnx-tensorflow be used to do?

**Comment by tjingrant** [comment]
Hi, this looks like a very generic question, but mostly people use this to run models exported from other deep learning libraries in ONNX format. Conversely, you can also use this to export models defined in tensorflow to ONNX format and thus run it in other deep learning libraries.

A good place for related resources is the ONNX tutorial repo here: https://github.com/onnx/tutorials/blob/master/tutorials/OnnxTensorflowImport.ipynb.

**Comment by muyueyue** [comment]
@tjingrant Thank you for your reply. Can this be used in the production environment?

**Comment by tjingrant** [comment]
@muyueyue for sure, this is not a pet project and I believe both us here and people in the ONNX spec repo are committed for supporting this project for the foreseeable future.

**Comment by chinhuang007** [comment]
Close since initial question is answered. Please reopen if anyone wants to continue the discussions.
