### ISSUE TITLE
Default ONNX arg may break logic for slice ver. 10

### ISSUE THREAD

**Issue by shawn-g-hu** [onnx/onnx-tensorflow#432]
The ONNX opset specs provide `1` as a default arg for slice steps: https://github.com/onnx/onnx/blob/master/docs/Operators.md#Slice

The correct behavior as specified for ONNX is: `If steps are omitted, they are set to [1, ..., 1] of length len(starts)`.

I think that this behavior does not occur- In https://github.com/chinhuang007/onnx-tensorflow/blob/a93a05f1945f948b33b5ac65b9667a10a8705cf2/onnx_tf/handlers/backend/slice.py#L57-L58 , the slice arg for steps is directly taken and passed to the TF op. This has caused errors for me when trying to slice on more than one axis, which I have resolved for myself in a hacky way by reshaping `steps` based on certain conditions, so I'm fairly sure this is the source of the error. (I'm submitting an issue instead of a PR because I couldn't easily think of a solution for the general case.)

I am not sure this really counts as a bug, or whether it is the responsibility of ONNX-TF (maybe you could consider this a problem of the ONNX user's model, but at the very least, this may break models exported from other deep learning frameworks.

**Comment by chinhuang007** [comment]
Thanks for theo comments! The steps is covered in the block from https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/handlers/backend/slice.py#L100. If not provided, the default is 1s.

**Comment by shawn-g-hu** [comment]
Ah, yep, I see this got merged on June 10. Thanks for taking care of it!
