### ISSUE TITLE
Tensor conversion requested dtype float32 for Tensor with dtype int64

### ISSUE THREAD

**Issue by Aeroxander** [onnx/onnx-tensorflow#435]
**Describe the bug**
So I have 3 PyTorch models (pre-trained) that I converted to ONNX and now trying to convert to Tensorflow, only 1 model converts successfully, with the rest I get the following error:

`ValueError: Tensor conversion requested dtype float32 for Tensor with dtype int64: 'Tensor("Mul_3:0", shape=(), dtype=int64)'`

Is there a way to manually cast the dtype Tensor for the 2 ONNX models to fix this issue?

I'm also unable to read the 2 faulty ONNX models in OpenCV, so I suppose OpenCV struggles with the same issue.

**ONNX model file**

[ONNX model file](https://drive.google.com/file/d/1WvwIFT_Y4e8CSmgowROo6mbPnhqE4zNz/view?usp=sharing)

**Python, ONNX, ONNX-TF, Tensorflow version**

Python version:
3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
ONNX version:
1.5.0
ONNX-TF version:
1.2.1

Tensorflow version:
1.13.1

**Comment by chinhuang007** [comment]
Currently onnx-tf does not do auto data type conversion. I opened your model in Netron and saw the inputs for Mul are type of float32 and int64 (a constant). Tensorflow API requires two inputs have the same type (no auto cast either) therefore the error. The solution seems in the original model, before converted to onnx. Change the constant to float32 might work.

**Comment by Aeroxander** [comment]
> 
> 
> Currently onnx-tf does not do auto data type conversion. I opened your model in Netron and saw the inputs for Mul are type of float32 and int64 (a constant). Tensorflow API requires two inputs have the same type (no auto cast either) therefore the error. The solution seems in the original model, before converted to onnx. Change the constant to float32 might work.

Thanks, I'll try to change it!
