### ISSUE TITLE
Is it a backend or converter ?

### ISSUE THREAD

**Issue by VincentLin78** [onnx/onnx-tensorflow#44]
I come here from the link https://onnx.ai/supported-tools.
The page there claims ONNX's supported tools including  converters for TF and coreML.

onnx-coreml does like a converter. It can output a *.mlmodel file.
https://github.com/onnx/onnx-coreml

onnx-tensorflow here doesn't. And it looks like a backend ?

I'm so confused.

**Comment by LucasMahieu** [comment]
Hi, 
Actually onnx-tensorflow permits to generate tensorflow graph from onnx graph.
(ONNX -> TF is called back-end) 
It is what converter means in https://onnx.ai/supported-tools.
And it is exactly what onnx-coreml does too.

We are actively developing the onnx front-end for Tensorflow (TF -> ONNX).
So, contributions are really welcome.

**Comment by VincentLin78** [comment]
onnx-coreml can output a mlmodel file
``
cml = onnx_coreml.convert(model)
cml.save('output/super_resolution.mlmodel')
``
But how can onnx-tensorflow do that ?

**Comment by tjingrant** [comment]
After you get your graph up and running in onnx-tf, just do:
`
tf.get_default_graph()
`
and save that graph.
