### ISSUE TITLE
Failing tests

### ISSUE THREAD

**Issue by iiSeymour** [onnx/onnx-tensorflow#445]
Many tests are failing on the master branch which makes it harder to contribute to the project. I'm creating this issue to track the progress of getting the tests green again. All the failing tests are in `backend/test_node.py` and the test runner appears to miss all the frontend tests completely. 

```python
test/test_cli.py .                                                       [  0%]
test/backend/test_model.py ..                                            [  0%]
test/backend/test_node.py ..............s.s............................. [  4%]
.........................................                                [  7%]
test/backend/test_onnx_backend.py ssssssss.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s [ 10%]
.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sFsFsFsFsFsFs.s.s.s.s.s.s.s [ 16%]
.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sss.s.s.s.s.s.s.s [ 22%]
ss.s.s.s.s.s.s.s.s.sssss.s.s.s.s.s.s.s.s.s.s.s.sss.sss.sss.s.s.s.s.s.s.s [ 28%]
.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sss.s.s.s.sssssssssss.s.s.s.s.s.s.s.s.s.s.s [ 34%]
.s.s.s.s.s.s.s.s.s.sFs.s.s.s.s.s.s.s.s.s.s.s.s.sFs.s.sssssssssssssssss.s [ 40%]
.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sFs.s.s.sFs.s.s.s.s.s.s [ 46%]
.s.s.s.s.sFsss.s.s.s.s.s.s.s.sss.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sssss [ 52%]
.s.s.s.sss.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sss.s.s.s.s.s.s.s [ 58%]
.s.s.s.s.s.s.s.s.s.sFs.s.s.s.sFs.sFs.s.s.s.s.s.s.s.s.sssFsFs.s.s.s.s.s.s [ 64%]
ss.s.s.sss.s.sFs.s.s.sFsFsFsFsFsFsFsFsFs.s.s.s.sssss.s.s.sssssssssssssss [ 70%]
.s.sss.sFsFsFsFs.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s [ 76%]
.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s [ 82%]
.s.s.sFsFsFsFsFsFsFs.sFsFsFsFsFs.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s [ 88%]
.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sFsFsFsFsFsFsss.s.s.s.s.s [ 94%]
.s.s.s.sFsFsFsFsFsFsFs.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.s.sssssssssss   [100%]
===== 55 failed, 541 passed, 610 skipped, 5567 warnings in 798.78 seconds ======
```

Most of the errors are from operators that are not implemented - 

```bash
$ grep NotImplementedError: test_results.txt | wc -l 
52
$ grep NotImplementedError: test_results.txt | sort | uniq -c| sort -rn 
   12  NotImplementedError: StringNormalizer is not implemented.
    9  NotImplementedError: NonMaxSuppression is not implemented.
    7  NotImplementedError: TfIdfVectorizer is not implemented.
    5  NotImplementedError: Resize is not implemented.
    2  NotImplementedError: Scatter is not implemented.
    2  NotImplementedError: ReverseSequence is not implemented.
    2  NotImplementedError: QLinearMatMul is not implemented.
    2  NotImplementedError: MaxUnpool is not implemented.
    2  NotImplementedError: MaxPool version 10 is not implemented.
    2  NotImplementedError: ConvInteger is not implemented.
    1  NotImplementedError: RoiAlign is not implemented.
    1  NotImplementedError: QuantizeLinear is not implemented.
    1  NotImplementedError: QLinearConv is not implemented.
    1  NotImplementedError: MeanVarianceNormalization version 9 is not implemented.
    1  NotImplementedError: MatMulInteger is not implemented.
    1  NotImplementedError: DequantizeLinear is not implemented.
    1  NotImplementedError: AveragePool version 10 is not implemented.
```

This is with the currently released version of onnx *(1.5.0)*. Using the `ONNX_VERSION_NUMBER` release of *1.1.2* results in all tests failing with `'TestCaseFunction' object has no attribute 'get_marker' `

**Comment by iiSeymour** [comment]
Pull request #448 explicitly skips the `NotImplementedError` failures.

Issues for supporting the operations:
 - Opset 9 #413 
 - Opset 10 #418 #430

**Comment by chinhuang007** [comment]
We are working on a release build, https://github.com/onnx/onnx-tensorflow/pull/444, that would pass all tests with ONNX 1.3 and Tensorflow 1.13.1. We are still not yet quite up to ONNX 1.4 and 1.5. Therefore the master build with more recent ONNX is known to fail a number of test cases. The purpose of our unit test is to report the accurate status of onnx-tf with regard to an ONNX build. I suggest we don't change the nature of unit test, ie not skipping the NotImplementedError failures, so we can always see the true state of onnx-tf converter. Moreover, the use of filtering in test_onnx_backend.py is for the issues/mismatches we identified in coding, and hence permanent. I am not sure if we should use the same filtering mechanism to temporarily remove NotImplementedError from unit test output. @tian, any comments?

**Comment by iiSeymour** [comment]
Sure, it makes sense to test against the master of ONNX as part of the testing but I think it would be a good idea to have the tests passing against the latest supported version, 1.2.1 (or 1.3.0 #444).

The test suite doesn't seem compatible with ONNX 1.3.0. Running the tests with 1.3.0 leads to all tests failing with `AttributeError: 'TestCaseFunction' object has no attribute 'get_marker'`.

> ============== 1078 failed, 5 warnings, 1 error in 14.10 seconds ===============

It's also easy for actual issues to slip by if it's expected that the tests will fail. There are 3 tests that are failing due to issues other than `NotImplementedError`. See the difference in output [here](https://travis-ci.org/iiSeymour/onnx-tensorflow/jobs/552868506) vs [here](https://travis-ci.org/onnx/onnx-tensorflow/jobs/553079948).

**Comment by chinhuang007** [comment]
I just ran the unit test following instructions on onnx-tf readme, https://github.com/onnx/onnx-tensorflow#to-test. With onnx 1.3.0 and tf 1.13.1, it turns out to be okay.

Ran 1078 tests in 1292.134s
OK (skipped=493)

Could you try using the docker container and verify working or not? If you use native/self installs, please make sure onnx=1.3.0 and tf=1.13.1. I don't see why it would fail all tests. So please provide more details on your system configurations if you still can't get unit tests to pass.

**Comment by iiSeymour** [comment]
Yes, all the tests pass when using onnx==1.3.0 and the python unittest runner. The problems occur when trying to use the pytest runner, sorry for the confusion!

I think it would be good to have the default testing behaviour uses the recommended onnx and tensorflow versions and have the daily triggered jobs use onnx from master and tf-nightly.

**Comment by chinhuang007** [comment]
Yeah, we have been trying to better in CI... here I opened an issue to track it, https://github.com/onnx/onnx-tensorflow/issues/451
