### ISSUE TITLE
Missing Tag v1.2.1 

### ISSUE THREAD

**Issue by iiSeymour** [onnx/onnx-tensorflow#447]
The current version of `onnx-tf` on https://pypi.org is 1.2.1 but the associated tag doesn't exist. The relevant commit is 8a640a525510b958a16ddbe400bcf2a3cd3711fc.

**Comment by chinhuang007** [comment]
Thanks for bringing it to our attention. I just added a tag for v1.2.1. And we should have a new release soon, https://github.com/onnx/onnx-tensorflow/pull/444
