### ISSUE TITLE
Remove frontend support from this repo

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx-tensorflow#450]
Since we have joined force with Microsoft to co-develop ONNX Tensorflow frontend. We are going to remove all the frontend code from this repo for the next release.

**Comment by Vozf** [comment]
tensorflow onnx readme has nothing about converting onnx to tensorflow. Their readme only mentions tf to onnx. So how to convert onnx to tensorflow using tensorflow-onnx?

**Comment by winnietsang** [comment]
@Vozf This issue is only trying to remove the frontend which is the convertion from Tensorflow to ONNX. That is the only piece which is merge with the tensorflow-onnx repo. 
If you want to convert ONNX to Tensoflow please continue to use this repo(onnx-tensoflow). If you want to convert Tensorflow to ONNX then please use tensorflow-onnx.
