### ISSUE TITLE
Order for mutiple outputs

### ISSUE THREAD

**Issue by arogozhnikov** [onnx/onnx-tensorflow#46]
Looking at these lines:

https://github.com/onnx/onnx-tensorflow/blob/3c2723e4077345405defad12ac3a6b31dfdbea4d/onnx_tf/backend_rep.py#L39-L41

Order of output is not determenistic prior to python 3.7 since dict can store and return values in any order.

Replacing `dict` with `OrderedDict` should fix this.

**Comment by tjingrant** [comment]
Hi, this does not seem to be a problem because my implementation does not rely on .values() producing a particular-ordered list of the values. So long as .values() and .keys() correspond, they will be zipped together in the correct way. The correspondence condition is guaranteed here:

https://docs.python.org/2/library/stdtypes.html#dict.items

Which states:

> If items(), keys(), values(), iteritems(), iterkeys(), and itervalues() are called with no intervening modifications to the dictionary, the lists will directly correspond.

I'd be happy to look into your code if you run into troubles. Otherwise this doesn't seem to be an issue?

**Comment by arogozhnikov** [comment]
Exactly, as you said, `.values()` correspond to contents, but the problem is in creation of dict, below is a simple example (note, that I'm adding elements 2, then 1):
```
$ python2.7
Python 2.7.12 (default, Dec  4 2017, 14:50:18) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> d = dict(zip([2, 1], [2, 1]))
>>> d.values()
[1, 2]
>>> d
{1: 1, 2: 2}
```

**Comment by tjingrant** [comment]
@arogozhnikov , I'd like to make 3 things clear:
1. The output of backend.run is a **dictionary**, not a list; thus order does not matter.
2. Sess.run is order preserving and thus behaves much like a map function.
3. The internal ordering of the dictionary elements does not change (unless modified); thus .values() and .keys() reflect the same internal order, thus they will **correspond** . And by correspond, I mean, for all `i`:
```
d[d.keys[i]] == d.values[i] 
```

Thus to continue your demonstration:
```
>>> d = dict(zip([2,1],[2,1]))
>>> d.values()
[1, 2]
>>> d
{1: 1, 2: 2}
# by 2, mimic sess.run using map
>>> sess_out = map(str, d.values())
>>> sess_out
['1', '2']
# by 3, the correspondence guarantee
>>> zip(d.keys(), sess_out)
[(1, '1'), (2, '2')]
```
Now, by 1, the output is a dictionary, the order of items moved around, but that doesn't matter.

**Comment by arogozhnikov** [comment]
> Sess.run is order preserving and thus behaves much like a map function.

Ah, sorry. That's what I forgot.
