### ISSUE TITLE
Need to Support Tensorflow 2.0

### ISSUE THREAD

**Issue by chinhuang007** [onnx/onnx-tensorflow#460]
Tensorflow 2.0 has a lot of API changes. We are looking into how to support it. Current thinking we will complete our next release with Tensorflow 1.14 (stable) and switch to 2.0, skipping 2.0 beta. Due the incompatible APIs, we don't plan to support both 1.x and 2.0 with the same onnx-tf release. Comments are welcome.

**Comment by fumihwh** [comment]
Is switching tf_func by tf version workable?

**Comment by chinhuang007** [comment]
We considered two approaches to support TF 2.0 as welll as TF 1.x since 1.x will be there for at least a year according to the TF community.
1. Keep 1.x and 2.0 code in the master and use conditional imports when loading the handlers
2. Start a new branch for 1.x and make master to be totally for 2.0
We are currently inclined to go with option 2 for the code simplicity and cleanliness. A couple of PRs will be opened to more this forward. That means we need to implement new operators in two branches in the future.
Please let us know your opinions ASAP. Thanks!

**Comment by vijay39312** [comment]
Option 2 sounds good and is good for the longer term.

**Comment by chinhuang007** [comment]
@vijay39312 Thanks for the comment. We are proceeding with option 2. The PR is ready for review, https://github.com/onnx/onnx-tensorflow/pull/531.

**Comment by chinhuang007** [comment]
We support TF 2.0 now in the master branch! For TF 1.x please use the tf-1.x branch.
