### ISSUE TITLE
The backend of Slice Op doesn't support dynamic shape.

### ISSUE THREAD

**Issue by JiayiFu** [onnx/onnx-tensorflow#464]
The backend of _slice_ uses `tf.constant` to construct the `input_tensor_shape`. If the input tensor has a dynamic dimension, the process will fail since `tf.constant` doesn't support unknown shape. Should it be implemented with another way?

**Comment by chinhuang007** [comment]
Dynamic input/output shape is not currently supported in ONNX. More details here, https://github.com/onnx/onnx/issues/654

**Comment by JiayiFu** [comment]
> Dynamic input/output shape is not currently supported in ONNX. More details here, [onnx/onnx#654](https://github.com/onnx/onnx/issues/654)

Thanks for your reply! But I also found onnx/onnx#740 which seems like ONNX has supported dynamic input shape. 
Most of the discussion was a year ago and I am a little confused about is there any updates.

**Comment by chinhuang007** [comment]
Good question. The onnx spec has dim_param for unknown input shape. I haven't seen official doc or test cases for converters to deal with dynamic input shape. Since some of our conversion logic currently depends known shape, more investigation is definitely needed to determine the best solution.

**Comment by linkerzhang** [comment]
dim parameter was designed to handle dynamic shape, though I admit that it's not that clear in the spec about what and how dynamic shape is supported. @gramalingam is going to make some spec clarification on this. Thanks a lot!

**Comment by gramalingam** [comment]
ONNX itself has supported dynamic shapes for a long time now. A tensor-type is allowed to have no shape (which means that even the rank is unknown). A tensor type may have a shape, in which case its rank is known. Each dimension may itself be a statically known constant or unknown. By the way, I have added the spec clarification Ke is referring to (see IR.md) but that is more to do with some finer details, like the scoping of symbolic-identifiers used in shapes.

**Comment by JiayiFu** [comment]
@linkerzhang thanks for your reply! @gramalingam thanks for your reply and clarification! 
@chinhuang007 ONNX has supported dynamic shapes, should onnx_tf also support it? thx!

**Comment by chinhuang007** [comment]
Yeah, we should look into how to support dynamic (unknown or not specified at the modeling time) shape and rank. @gramalingam are you aware of ONNX test cases for backend converters to verify the dynamic shape and rank support?

**Comment by JiayiFu** [comment]
@chinhuang007 Is there any updates about the supports of dynamic shape? I found there are some updates about the negative axis #510 .

**Comment by chinhuang007** [comment]
We should support negative axis everywhere now. The dynamic shape is a bigger issue which is still a work-in-progress.

**Comment by JiayiFu** [comment]
> We should support negative axis everywhere now. The dynamic shape is a bigger issue which is still a work-in-progress.

Thanks for your reply! Please let me know when there are some updates about the dynamic shape.

**Comment by JiayiFu** [comment]
@chinhuang007 Hi, are there any updates about the supports of dynamic shape? : )

**Comment by lxl910915** [comment]
https://github.com/onnx/tensorflow-onnx/issues/784

**Comment by chinhuang007** [comment]
@JiayiFu we added the dynamic input shapes support for first few ops here, https://github.com/onnx/onnx-tensorflow/pull/548. There is an open PR for Slice, https://github.com/onnx/onnx-tensorflow/pull/543, which should be good to go soon.

There are more ops affected by dynamic shapes. We will document and handle them case by case.

**Comment by JiayiFu** [comment]
@chinhuang007 Cool! I also found that there are some discussions(#553) and WIPs. I will try to convert my model which needs dynamic shape when enough ops have been done. Thanks!

**Comment by JiayiFu** [comment]
My issue has been solved by PR#566. So I close this.
