### ISSUE TITLE
lp_normalization.py implementation is not right

### ISSUE THREAD

**Issue by wutiantong** [onnx/onnx-tensorflow#465]
Currently, the implementation is equal to `tf.norm()`, which is ReduceL2 actually.

Totally speaking, lp_normalization should be `tf.div(X, tf.norm(X))`.

**Comment by chinhuang007** [comment]
Thanks for pointing it out. Will look into a fix.

**Comment by chinhuang007** [comment]
The fix is merged. Please go ahead and verify. Reopen if the problem is not addressed.
