### ISSUE TITLE
Duplicate source codes

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#47]
In `backend.py`, `frontend.py`, I find there are a lot duplicate source code which are also in `common.py`. It is not good for maintenance.
I just want to keep them in `common.py` and remove unneeded one in `backend.py`, `frontend.py`.

When this done, I think I could implement some ops(handlers) supported in onnx but not here yet.

**Comment by tjingrant** [comment]
Yes, indeed, I'm trying to move some of the shared codes from `backend` to `common` but didn't want to break anything. It's probably ultimately a good thing to keep things clean.

Would you care to submit a PR for this?

**Comment by fumihwh** [comment]
Yes, I am trying to do this currently.
I will create a PR when it is done.
