### ISSUE TITLE
Gemm Op doesn't support batch operation?

### ISSUE THREAD

**Issue by JiayiFu** [onnx/onnx-tensorflow#471]
I found the is a flatten op in the backend of Gemm Op:  ` x = tf.layers.flatten(x)`.
If I put a 3-dimension matrix to the Gemm Op, it will return a 2-dimension matrix.
I guess this is not reasonable? The results of this Op should be the same shape in dimension?

**Comment by chinhuang007** [comment]
Good question. I opened an issue in ONNX to clarify the expected results with 3-d inputs for the Gemm op. I will work on a fix once getting clarification from ONNX community.

**Comment by JiayiFu** [comment]
> Good question. I opened an issue in ONNX to clarify the expected results with 3-d inputs for the Gemm op. I will work on a fix once getting clarification from ONNX community.

Thanks for your reply! I found ONNX community has replied your issue and they said Gemm just support the 2-d operations.

**Comment by JiayiFu** [comment]
Maybe onnx2tf should do a dimension check?

**Comment by chinhuang007** [comment]
Based on the comments and code that enforces 2-d inputs, https://github.com/onnx/onnx/issues/2209, the Gemm inputs in an ONNX model will always be 2-d. Therefore, I feel adding a dimension check in our backend converter might not be necessary.

**Comment by JiayiFu** [comment]
> Based on the comments and code that enforces 2-d inputs, [onnx/onnx#2209](https://github.com/onnx/onnx/issues/2209), the Gemm inputs in an ONNX model will always be 2-d. Therefore, I feel adding a dimension check in our backend converter might not be necessary.

Thanks for your reply!
