### ISSUE TITLE
Does onnx2tf support name scope?

### ISSUE THREAD

**Issue by JiayiFu** [onnx/onnx-tensorflow#475]
Hi,
  I tried to use tensorboard to visualize the model converted from ONNX. But the model is too complex to understand. So if the model has some name scopes, the graph of the model may be more directly understanding. 
  Does onnx2tf support name scope in TensorFlow? like setting the 'domain' of ONNX op as the name scope of TensorFlow op? or some other ways?

**Comment by fumihwh** [comment]
You can add something like `with tf.name_scope(node.name)` just after backend.py:L126 `for node in graph_def.node:`.

**Comment by chinhuang007** [comment]
Since our handlers currently support domain=defs.ONNX_DOMAIN, which is '', the use of custom domains in ONNX ops for tf name scope will not work.

**Comment by chinhuang007** [comment]
Please note node.name is optional in ONNX. So after `with tf.name_scope(node.name)` is added to backend.py, all nodes will be in the same tf name space if the exporter does not provide specific node names as "name space" indicators.

**Comment by JiayiFu** [comment]
Thanks for your replies!
