### ISSUE TITLE
FER+ Emotion Recognition : Cannot Run the Model: gives Error : Negative dimension size caused by subtracting 3 from 1

### ISSUE THREAD

**Issue by surajkandukuri** [onnx/onnx-tensorflow#502]
I tried to implement the FER+ Emotion Recognition model in the system with configuration 
System : Ubuntu 18.04
Tensorflow- gpu : 1.14.0
Keras: 2.2.5
Python: 3.6.8 
  
    
[Error in Onnx FER+.docx](https://github.com/onnx/models/files/3588474/Error.in.Onnx.FER%2B.docx)

**Comment by prasanthpul** [comment]
transferred this issue to onnx-tensorflow repo as the problem seems to be with the ONNX to TF converter rather than the model. the model has previously been verified with [ONNX Runtime](https://github.com/microsoft/onnxruntime).

**Comment by chinhuang007** [comment]
@prasanthpul Thanks for transferring the issue. @ebarsoum Sure, I will take a look.

**Comment by chinhuang007** [comment]
@surajkandukuri Can you provide 1.jpg so we are using exact same input to verify and debug?

**Comment by surajkandukuri** [comment]
@chinhuang007 sure. Please find the attached. 
![1](https://user-images.githubusercontent.com/20826129/64579223-b38cd200-d347-11e9-8a11-997ba0e87858.jpg)

**Comment by chinhuang007** [comment]
The issue is addressed by PR #504
