### ISSUE TITLE
onnx-tf convert throws an error but onnx_tensorrt.backend is fine (the same onnx file)

### ISSUE THREAD

**Issue by paapu88** [onnx/onnx-tensorflow#503]
Dear Developers,

I'm able to read in onnx data in jetson nano, and making predictions by tensorRT, for instance:
(below just random data, but I have verified it can box my face..)
(this is a tiny-yolo-3l net)
```
import onnx
import onnx_tensorrt.backend as backend
import numpy as np
from timeit import default_timer as timer

print("loading onnx model")
model = onnx.load('./weights/final.onnx')
engine = backend.prepare(model)
input_data = np.random.random(size=(32, 3, 320, 320)).astype(np.float32)
output_data = engine.run(input_data)[0]
print("Time for input data:", input_data.shape, timer() - start)
```
Now, when I check the neural net it looks ok to me:
`onnx2trt ./weights/final.onnx -t ./weights/final.onnx.txt -l -v`

> [2019-09-10 12:50:43    INFO] 001_convolutional:Conv -> (16, 320, 320)
[2019-09-10 12:50:43    INFO] 001_convolutional_bn:BatchNormalization -> (16, 320, 320)
[2019-09-10 12:50:43    INFO] 001_convolutional_lrelu:LeakyRelu -> (16, 320, 320)
[2019-09-10 12:50:43    INFO] 002_maxpool:MaxPool -> (16, 160, 160)
[2019-09-10 12:50:43    INFO] 003_convolutional:Conv -> (32, 160, 160)
[2019-09-10 12:50:43    INFO] 003_convolutional_bn:BatchNormalization -> (32, 160, 160)
[2019-09-10 12:50:43    INFO] 003_convolutional_lrelu:LeakyRelu -> (32, 160, 160)
[2019-09-10 12:50:43    INFO] 004_maxpool:MaxPool -> (32, 80, 80)
[2019-09-10 12:50:43    INFO] 005_convolutional:Conv -> (64, 80, 80)
[2019-09-10 12:50:43    INFO] 005_convolutional_bn:BatchNormalization -> (64, 80, 80)
[2019-09-10 12:50:43    INFO] 005_convolutional_lrelu:LeakyRelu -> (64, 80, 80)
[2019-09-10 12:50:43    INFO] 006_maxpool:MaxPool -> (64, 40, 40)
[2019-09-10 12:50:43    INFO] 007_convolutional:Conv -> (128, 40, 40)
[2019-09-10 12:50:43    INFO] 007_convolutional_bn:BatchNormalization -> (128, 40, 40)
[2019-09-10 12:50:43    INFO] 007_convolutional_lrelu:LeakyRelu -> (128, 40, 40)
[2019-09-10 12:50:43    INFO] 008_maxpool:MaxPool -> (128, 20, 20)
[2019-09-10 12:50:43    INFO] 009_convolutional:Conv -> (256, 20, 20)
[2019-09-10 12:50:43    INFO] 009_convolutional_bn:BatchNormalization -> (256, 20, 20)
[2019-09-10 12:50:43    INFO] 009_convolutional_lrelu:LeakyRelu -> (256, 20, 20)
[2019-09-10 12:50:43    INFO] 010_maxpool:MaxPool -> (256, 10, 10)
[2019-09-10 12:50:43    INFO] 011_convolutional:Conv -> (512, 10, 10)
[2019-09-10 12:50:43    INFO] 011_convolutional_bn:BatchNormalization -> (512, 10, 10)
[2019-09-10 12:50:43    INFO] 011_convolutional_lrelu:LeakyRelu -> (512, 10, 10)
[2019-09-10 12:50:43    INFO] 012_maxpool:MaxPool -> (512, 10, 10)
[2019-09-10 12:50:43    INFO] 013_convolutional:Conv -> (1024, 10, 10)
[2019-09-10 12:50:43    INFO] 013_convolutional_bn:BatchNormalization -> (1024, 10, 10)
[2019-09-10 12:50:43    INFO] 013_convolutional_lrelu:LeakyRelu -> (1024, 10, 10)
[2019-09-10 12:50:43    INFO] 014_convolutional:Conv -> (256, 10, 10)
[2019-09-10 12:50:43    INFO] 014_convolutional_bn:BatchNormalization -> (256, 10, 10)
[2019-09-10 12:50:43    INFO] 014_convolutional_lrelu:LeakyRelu -> (256, 10, 10)
[2019-09-10 12:50:43    INFO] 015_convolutional:Conv -> (512, 10, 10)
[2019-09-10 12:50:43    INFO] 015_convolutional_bn:BatchNormalization -> (512, 10, 10)
[2019-09-10 12:50:43    INFO] 015_convolutional_lrelu:LeakyRelu -> (512, 10, 10)
[2019-09-10 12:50:43    INFO] 016_convolutional:Conv -> (252, 10, 10)
[2019-09-10 12:50:43    INFO] 019_convolutional:Conv -> (128, 10, 10)
[2019-09-10 12:50:43    INFO] 019_convolutional_bn:BatchNormalization -> (128, 10, 10)
[2019-09-10 12:50:43    INFO] 019_convolutional_lrelu:LeakyRelu -> (128, 10, 10)
[2019-09-10 12:50:43    INFO] 020_upsample:Upsample -> (128, 20, 20)
[2019-09-10 12:50:43    INFO] 021_route:Concat -> (384, 20, 20)
[2019-09-10 12:50:43    INFO] 022_convolutional:Conv -> (256, 20, 20)
[2019-09-10 12:50:43    INFO] 022_convolutional_bn:BatchNormalization -> (256, 20, 20)
[2019-09-10 12:50:43    INFO] 022_convolutional_lrelu:LeakyRelu -> (256, 20, 20)
[2019-09-10 12:50:43    INFO] 023_convolutional:Conv -> (36, 20, 20)
[2019-09-10 12:50:43    INFO] 026_convolutional:Conv -> (128, 20, 20)
[2019-09-10 12:50:43    INFO] 026_convolutional_bn:BatchNormalization -> (128, 20, 20)
[2019-09-10 12:50:43    INFO] 026_convolutional_lrelu:LeakyRelu -> (128, 20, 20)
[2019-09-10 12:50:43    INFO] 027_upsample:Upsample -> (128, 40, 40)
[2019-09-10 12:50:43    INFO] 028_route:Concat -> (256, 40, 40)
[2019-09-10 12:50:43    INFO] 029_convolutional:Conv -> (128, 40, 40)
[2019-09-10 12:50:43    INFO] 029_convolutional_bn:BatchNormalization -> (128, 40, 40)
[2019-09-10 12:50:43    INFO] 029_convolutional_lrelu:LeakyRelu -> (128, 40, 40)
[2019-09-10 12:50:43    INFO] 030_convolutional:Conv -> (36, 40, 40)

When I try to convert to tensorflow by:
`onnx-tf convert  -i ./weights/duranc_all_tiny_3l_v6_1_final.onnx -o test.pb ` 

I get

> ValueError: Dimension 0 in both shapes must be equal, but are 8 and 16. Shapes are [8,8] and [16,16]. for '021_route' (op: 'ConcatV2') with input shapes: [1,128,8,8], [1,256,16,16], [] and with computed input tensors: input[2] = <1>.

What gather, layer '021_route' puts together layers 
'020_upsample'  and '009_convolutional_lrelu'
and it looks ok to me.

This is probably some upsample issue, could not quite figure it out...
Markus
ps. below keras representation of the same network and pip freeze in jetson nano

```
Layer (type)                    Output Shape         Param #     Connected to                     
input_1 (InputLayer)            (None, 320, 320, 3)  0                                            
conv2d_1 (Conv2D)               (None, 320, 320, 16) 432         input_1[0][0]                    
batch_normalization_1 (BatchNor (None, 320, 320, 16) 64          conv2d_1[0][
leaky_re_lu_1 (LeakyReLU)       (None, 320, 320, 16) 0           batch_normalization_1[0][0]      
max_pooling2d_1 (MaxPooling2D)  (None, 160, 160, 16) 0           leaky_re_lu_1[0][0]              
conv2d_2 (Conv2D)               (None, 160, 160, 32) 4608        max_pooling2d_1[0][0]            
batch_normalization_2 (BatchNor (None, 160, 160, 32) 128         conv2d_2[0][0]                   
leaky_re_lu_2 (LeakyReLU)       (None, 160, 160, 32) 0           batch_normalization_2[0][0]      
max_pooling2d_2 (MaxPooling2D)  (None, 80, 80, 32)   0           leaky_re_lu_2[0][0]              
conv2d_3 (Conv2D)               (None, 80, 80, 64)   18432       max_pooling2d_2[0][0]            
batch_normalization_3 (BatchNor (None, 80, 80, 64)   256         conv2d_3[0][0]                   
leaky_re_lu_3 (LeakyReLU)       (None, 80, 80, 64)   0           batch_normalization_3[0][0]      
max_pooling2d_3 (MaxPooling2D)  (None, 40, 40, 64)   0           leaky_re_lu_3[0][0]              
conv2d_4 (Conv2D)               (None, 40, 40, 128)  73728       max_pooling2d_3[0][0]            
batch_normalization_4 (BatchNor (None, 40, 40, 128)  512         conv2d_4[0][0]                   
leaky_re_lu_4 (LeakyReLU)       (None, 40, 40, 128)  0           batch_normalization_4[0][0]      
max_pooling2d_4 (MaxPooling2D)  (None, 20, 20, 128)  0           leaky_re_lu_4[0][0]              
conv2d_5 (Conv2D)               (None, 20, 20, 256)  294912      max_pooling2d_4[0][0]            
batch_normalization_5 (BatchNor (None, 20, 20, 256)  1024        conv2d_5[0][0]                   
leaky_re_lu_5 (LeakyReLU)       (None, 20, 20, 256)  0           batch_normalization_5[0][0]      
max_pooling2d_5 (MaxPooling2D)  (None, 10, 10, 256)  0           leaky_re_lu_5[0][0]              
conv2d_6 (Conv2D)               (None, 10, 10, 512)  1179648     max_pooling2d_5[0][0]            
batch_normalization_6 (BatchNor (None, 10, 10, 512)  2048        conv2d_6[0][0]                   
leaky_re_lu_6 (LeakyReLU)       (None, 10, 10, 512)  0           batch_normalization_6[0][0]      
max_pooling2d_6 (MaxPooling2D)  (None, 10, 10, 512)  0           leaky_re_lu_6[0][0]              
conv2d_7 (Conv2D)               (None, 10, 10, 1024) 4718592     max_pooling2d_6[0][0]            
batch_normalization_7 (BatchNor (None, 10, 10, 1024) 4096        conv2d_7[0][0]                   
leaky_re_lu_7 (LeakyReLU)       (None, 10, 10, 1024) 0           batch_normalization_7[0][0]      
conv2d_8 (Conv2D)               (None, 10, 10, 256)  262144      leaky_re_lu_7[0][0]              
batch_normalization_8 (BatchNor (None, 10, 10, 256)  1024        conv2d_8[0][0]                   
leaky_re_lu_8 (LeakyReLU)       (None, 10, 10, 256)  0           batch_normalization_8[0][0]      
conv2d_11 (Conv2D)              (None, 10, 10, 128)  32768       leaky_re_lu_8[0][0]              
batch_normalization_10 (BatchNo (None, 10, 10, 128)  512         conv2d_11[0][0]                  
leaky_re_lu_10 (LeakyReLU)      (None, 10, 10, 128)  0           batch_normalization_10[0][0]     
up_sampling2d_1 (UpSampling2D)  (None, 20, 20, 128)  0           leaky_re_lu_10[0][0]             
concatenate_1 (Concatenate)     (None, 20, 20, 384)  0           up_sampling2d_1[0][0]            
                                                                 leaky_re_lu_5[0][0]              
conv2d_12 (Conv2D)              (None, 20, 20, 256)  884736      concatenate_1[0][0]              
batch_normalization_11 (BatchNo (None, 20, 20, 256)  1024        conv2d_12[0][0]                  
leaky_re_lu_11 (LeakyReLU)      (None, 20, 20, 256)  0           batch_normalization_11[0][0]     
conv2d_14 (Conv2D)              (None, 20, 20, 128)  32768       leaky_re_lu_11[0][0]             
batch_normalization_12 (BatchNo (None, 20, 20, 128)  512         conv2d_14[0][0]                  
leaky_re_lu_12 (LeakyReLU)      (None, 20, 20, 128)  0           batch_normalization_12[0][0]     
up_sampling2d_2 (UpSampling2D)  (None, 40, 40, 128)  0           leaky_re_lu_12[0][0]             
concatenate_2 (Concatenate)     (None, 40, 40, 256)  0           up_sampling2d_2[0][0]            
                                                                 leaky_re_lu_4[0][0]              
conv2d_9 (Conv2D)               (None, 10, 10, 512)  1179648     leaky_re_lu_8[0][0]              
conv2d_15 (Conv2D)              (None, 40, 40, 128)  294912      concatenate_2[0][0]              
batch_normalization_9 (BatchNor (None, 10, 10, 512)  2048        conv2d_9[0][0]                   
batch_normalization_13 (BatchNo (None, 40, 40, 128)  512         conv2d_15[0][0]                  
leaky_re_lu_9 (LeakyReLU)       (None, 10, 10, 512)  0           batch_normalization_9[0][0]      
leaky_re_lu_13 (LeakyReLU)      (None, 40, 40, 128)  0           batch_normalization_13[0][0]     
conv2d_10 (Conv2D)              (None, 10, 10, 222)  113886      leaky_re_lu_9[0][0]              
conv2d_13 (Conv2D)              (None, 20, 20, 74)   19018       leaky_re_lu_11[0][0]             
conv2d_16 (Conv2D)              (None, 40, 40, 37)   4773        leaky_re_lu_13[0][0]             
```

> pip freeze
absl-py==0.7.1
Adafruit-GPIO==1.0.4
Adafruit-PureIO==0.2.3
Adafruit-SSD1306==1.6.2
aiohttp==3.5.4
amqp==2.5.1
appdirs==1.4.3
apt-clone==0.2.1
apturl==0.5.2
arrow==0.10.0
asn1crypto==0.24.0
astor==0.8.0
async-timeout==3.0.1
atomicwrites==1.3.0
attrs==19.1.0
backcall==0.1.0
beautifulsoup4==4.6.0
billiard==3.6.1.0
bistiming==0.4.0
bleach==3.1.0
blinker==1.4
Brlapi==0.6.6
celery==4.3.0
certifi==2019.3.9
chardet==3.0.4
Click==7.0
coverage==4.5.4
cryptography==2.1.4
cupshelpers==1.0
cycler==0.10.0
Cython==0.29.13
decorator==4.4.0
defer==1.0.6
defusedxml==0.6.0
distro-info===0.18ubuntu0.18.04.1
docutils==0.15.2
entrypoints==0.3
eyewitness==1.0.8
feedparser==5.2.1
fire==0.2.1
Flask==1.0.2
Flask-Admin==1.5.2
future==0.17.1
gast==0.2.2
gevent==1.4.0
google-pasta==0.1.7
GPUtil==1.4.0
graphsurgeon==0.3.2
greenlet==0.4.15
grpcio==1.22.0
h5py==2.9.0
html5lib==0.999999999
httplib2==0.9.2
idna==2.8
idna-ssl==1.1.0
importlib-metadata==0.19
ipykernel==5.1.1
ipython==7.5.0
ipython-genutils==0.2.0
ipywidgets==7.4.2
itsdangerous==1.1.0
jedi==0.13.3
jetcam==0.0.0
jetcard==0.0.0
Jinja2==2.10.1
joblib==0.13.2
jsonschema==3.0.1
jupyter==1.0.0
jupyter-clickable-image-widget==0.1.0.dev0
jupyter-client==5.2.4
jupyter-console==6.0.0
jupyter-core==4.4.0
jupyterlab==0.35.6
jupyterlab-server==0.2.0
Keras==2.2.4
Keras-Applications==1.0.8
Keras-Preprocessing==1.1.0
-e git+git@github.com:onnx/keras-onnx.git@4f88c4dc6b09508073c7bbf19cea7fd1979e9b2f#egg=keras2onnx
keyring==10.6.0
keyrings.alt==3.0
kombu==4.6.4
language-selector==0.1
launchpadlib==1.10.6
lazr.restfulclient==0.13.5
lazr.uri==1.0.3
line-bot-sdk==1.13.0
louis==3.5.0
lxml==4.2.4
macaroonbakery==1.1.3
Mako==1.0.7
Markdown==3.1.1
MarkupSafe==1.1.1
matplotlib==2.1.1
meld==3.18.0
mistune==0.8.4
mock==3.0.5
more-itertools==7.2.0
multidict==4.5.2
nbconvert==5.5.0
nbformat==4.4.0
nose2==0.9.1
notebook==5.7.8
numpy==1.17.0
oauth==1.0.1
oauthlib==2.0.6
olefile==0.45.1
onnx==1.4.1
onnx-tensorrt==0.1.0
onnx-tf==1.3.0
onnxconverter-common==1.5.3
onnxmltools==1.5.0
packaging==19.1
PAM==0.4.2
pandocfilters==1.4.2
parso==0.4.0
pathlib==1.0.1
pbr==5.4.2
peewee==3.7.1
pexpect==4.7.0
pickleshare==0.7.5
Pillow==6.1.0
pluggy==0.12.0
portpicker==1.3.1
prometheus-client==0.7.0
prompt-toolkit==2.0.9
protobuf==3.9.1
psutil==5.6.3
ptyprocess==0.6.0
py==1.8.0
py-cpuinfo==5.0.0
pycairo==1.16.2
pycrypto==2.6.1
pycuda==2019.1
pycups==1.9.73
pydot==1.4.1
Pygments==2.4.2
pygobject==3.26.1
PyICU==1.9.8
PyJWT==1.5.3
pymacaroons==0.13.0
PyNaCl==1.1.2
pyparsing==2.4.2
pyRFC3339==1.0
pyrsistent==0.15.2
pytest==5.0.1
python-apt==1.6.4
python-dateutil==2.8.0
python-debian==0.1.32
pytools==2019.1.1
pytz==2018.3
pyxdg==0.25
PyYAML==5.1.2
pyzmq==18.0.1
qtconsole==4.5.1
requests==2.22.0
requests-unixsocket==0.1.5
scikit-learn==0.21.3
scikit-video==1.1.11
scipy==1.2.1
SecretStorage==2.3.1
Send2Trash==1.5.0
simplegeneric==0.8.1
simplejson==3.13.2
six==1.12.0
skl2onnx==1.5.0
spidev==3.4
ssh-import-id==5.7
system-service==0.3
systemd-python==234
tensorboard==1.14.0
tensorflow-estimator==1.14.0
tensorflow-gpu==1.14.0+nv19.7
tensorrt==5.0.6.3
termcolor==1.1.0
terminado==0.8.2
testpath==0.4.2
testresources==2.0.1
torch==1.1.0a0+b457266
torchvision==0.2.2.post3
tornado==6.0.2
traitlets==5.0.0.dev0
typing==3.7.4
typing-extensions==3.7.4
ubuntu-drivers-common==0.0.0
uff==0.5.5
unattended-upgrades==0.1
unity-scope-calculator==0.1
unity-scope-chromiumbookmarks==0.1
unity-scope-colourlovers==0.1
unity-scope-devhelp==0.1
unity-scope-firefoxbookmarks==0.1
unity-scope-manpages==0.1
unity-scope-openclipart==0.1
unity-scope-texdoc==0.1
unity-scope-tomboy==0.1
unity-scope-virtualbox==0.1
unity-scope-yelp==0.1
unity-scope-zotero==0.1
urllib3==1.25.3
vine==1.3.0
wadllib==1.3.2
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.15.5
wget==3.2
widgetsnbextension==3.4.2
wrapt==1.11.2
wtf-peewee==3.0.0
WTForms==2.2.1
xkit==0.0.0
yarl==1.3.0
zipp==0.5.2
zope.interface==4.3.2

**Comment by chinhuang007** [comment]
Can you please provide the onnx file for debugging?

**Comment by paapu88** [comment]
Hi, File is 35MB, so I sent you a dropbox link. Hope you got it?

**Comment by paapu88** [comment]
Another thing: there may be something wrong with my onnx conversion (which is mostly taken from nvidia): the result of yolo-boxes is maximally off about 5% when comparing keras h5 result (at a regular gpu laptop) and tensorRT/onnx result (at a jetson nano).

So maybe your code is able to spot that something is wrong...

**Comment by paapu88** [comment]
Tried now a couple of ways to email address on your github page... hope you get it know

**Comment by chinhuang007** [comment]
Got it. Will take a look.

**Comment by chinhuang007** [comment]
The problem is in Conv. The auto_pad attribute was not supported earlier. With PR https://github.com/onnx/onnx-tensorflow/pull/504, we started to support auto_pad="NOTSET", "SAME_UPPER", and "VALID". Due to incompatible TF API, SAME_LOWER is still not supported. Unfortunately your model has Conv with auto_pad="SAME_LOWER".

**Comment by paapu88** [comment]
Thank's!!! I guess we can live with other padding. Markus
