### ISSUE TITLE
Upsample TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

### ISSUE THREAD

**Issue by thibault20cent** [onnx/onnx-tensorflow#514]
Hi,  
I have a problem with the upsample op when trying to prepare an onnx model converted from keras. Any idea of the solution ? Thx

> 
>   File "C:\Users\vthibault\anaconda3\envs\tensorflow\lib\site-packages\onnx_tf\backend.py", line 56, in prepare
>     return cls.onnx_model_to_tensorflow_rep(model, strict)
>   File "C:\Users\vthibault\anaconda3\envs\tensorflow\lib\site-packages\onnx_tf\backend.py", line 76, in onnx_model_to_tensorflow_rep
>     return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
>   File "C:\Users\vthibault\anaconda3\envs\tensorflow\lib\site-packages\onnx_tf\backend.py", line 133, in _onnx_graph_to_tensorflow_rep
>     onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
>   File "C:\Users\vthibault\anaconda3\envs\tensorflow\lib\site-packages\onnx_tf\backend.py", line 228, in _onnx_node_to_tensorflow_op
>     return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
>   File "C:\Users\vthibault\anaconda3\envs\tensorflow\lib\site-packages\onnx_tf\handlers\handler.py", line 59, in handle
>     return ver_handle(node, **kwargs)
>   File "C:\Users\vthibault\anaconda3\envs\tensorflow\lib\site-packages\onnx_tf\handlers\backend\upsample.py", line 33, in version_7
>     new_height = np.floor(x_shape[2] * scales[2])
> TypeError: unsupported operand type(s) for *: 'NoneType' and 'float'

**Comment by thibault20cent** [comment]
My model uses dynamic shapes

**Comment by chinhuang007** [comment]
A similar issue is opened, https://github.com/onnx/onnx-tensorflow/issues/464, for not supporting dynamic shapes. We are working on a solution now. Will provide updates later.
