### ISSUE TITLE
Broken with Tensorflow 2.0

### ISSUE THREAD

**Issue by ek9852** [onnx/onnx-tensorflow#521]
A lot of  renaming in function of TF 2.0. IT broken it.

**Comment by chinhuang007** [comment]
Thanks for the comment. We are working on this. Please follow the earlier issue, https://github.com/onnx/onnx-tensorflow/issues/460 for the latest development.

**Comment by chinhuang007** [comment]
We support TF 2.0 now in the master branch! For TF 1.x please use the tf-1.x branch.
