### ISSUE TITLE
failed in CI testing

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#53]
There are two reasons.

- lack of ops
- result not match

Actually, I am working on them and already done the first one.

**Comment by tjingrant** [comment]
I could look at the 2nd one when I get back and if you have not already done so.
A couple of ops have differing definitions in TF; most are variants of the relu ops. I don't think that matters so I may disable the relevant tests soon.

**Comment by fumihwh** [comment]
@tjingrant 
I am working at https://github.com/onnx/onnx-tensorflow/compare/master...fumihwh:fix-build and almost there.
Add and fix a lots of handlers. Let's what will happen https://travis-ci.org/fumihwh/onnx-tensorflow/branches

**Comment by tjingrant** [comment]
Looks great!

**Comment by tjingrant** [comment]
@fumihwh what seems to be the problem?

**Comment by fumihwh** [comment]
@tjingrant 
For backend, FAILED (failures=5, errors=6, skipped=281). [log here](https://api.travis-ci.org/v3/job/344734835/log.txt) Not a big problem.
Frontend is not reached because of that.

**Comment by tjingrant** [comment]
@fumihwh dont worry about fixing every error, I will work on them once I get back next Wed.

I'm fine with merging new changes as long as it does not increase the number of errors/failures.
