### ISSUE TITLE
NotImplementedError: Conv version 11 is not implemented

### ISSUE THREAD

**Issue by huangbinz** [onnx/onnx-tensorflow#533]
Hi,
I am trying to convert a pytorch model to tensorflow via onnx,
I've got an onnx model， When I was going to convert the onnx model to the tensorflow model, I got an error：NotImplementedError: Conv version 11 is not implemented.

the code is:
**onnx_model = onnx.load("299.onnx")
tf_rep = prepare(onnx_model)
tf_rep.export_graph("299.pb")**

the error is:
Traceback (most recent call last):
  File "onnx_to_tf.py", line 5, in <module>
    tf_rep = prepare(onnx_model, optset_version=11)  # prepare tf representation
  File "/home/zugou/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_tf/backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "/home/zugou/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_tf/backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "/home/zugou/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_tf/backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "/home/zugou/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_tf/backend.py", line 238, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "/home/zugou/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_tf/handlers/handler.py", line 62, in handle
    exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
  File "/home/zugou/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 31, in __call__
    super(OpUnimplementedException, self).__call__(op, version, domain)
  File "/home/zugou/anaconda3/envs/onnx/lib/python3.6/site-packages/onnx_tf/common/exception.py", line 13, in __call__
    raise self._func(self.get_message(*args, **kwargs))
NotImplementedError: Conv version 11 is not implemented.

Versions Info: 
python version: 3.6.8
pytorch version: 1.3.1
tensorflow version: 1.15.0
onnx version: 1.6.0
onnx-tf version: 1.5.0

How can I correctly convert onnx to tensorflow model？
Thank you!

**Comment by chinhuang007** [comment]
@huangbinz thanks for opening the issue. We are working on the new and updated ops introduced in ONNX 1.6 (opset 11) and will track the progress in this issue, https://github.com/onnx/onnx-tensorflow/issues/449. Will give Conv a high priority.

**Comment by luto65** [comment]
I confirm, tried today and got the same :-(
Is there the possibility online to convert onnx to tf ?

**Comment by dipsatch** [comment]
@chinhuang007 : Is there an ETA by when we can get this resolved?

**Comment by chinhuang007** [comment]
A simple fix is there, https://github.com/onnx/onnx-tensorflow/pull/539. Before it is reviewed and merged, feel free to give it a try. Please note the master branch requires TF 2.0. A similar fix will be added to the tf-1.x branch soon.

**Comment by chinhuang007** [comment]
The PR is merged. Conv should work with tf 2.0.

**Comment by cannguyen275** [comment]
@chinhuang007 Any news fix in tf-1.x branch?
Should I change my env to TF2.0? Does TF2.0 work best with onnx_tf 1.5.0?

**Comment by rrricharrrd** [comment]
> A similar fix will be added to the tf-1.x branch soon.
This doesn't appear to be present yet. Shall I create an issue to track porting this fix?

**Comment by chinhuang007** [comment]
@cannguyen275 Conv version 11 is added to the tf-1.x branch as well. TF 2.0 works well with the current master branch. If possible, I would recommend moving to TF 2.0.

**Comment by snowuyl** [comment]
TensorFlow 1.15.3 still has this issue.

**Comment by CR-Ko** [comment]
TensorFlow 1.14.0 + tf-1.x branch still has this issue.
TensorFlow 1.15.0 + tf-1.x branch still has this issue.

**Comment by amitrokade47** [comment]
Yes , issue still persistent in 1.x

**Comment by chinhuang007** [comment]
Did you do a build from source using tf-1.x branch? Based on the code, https://github.com/onnx/onnx-tensorflow/blob/eaf6563d05b59582d86399520cd247841a457c1c/onnx_tf/handlers/backend/conv.py#L14, conv version 11 is supported.

**Comment by amitrokade47** [comment]
Yes, built using bazel.
The code mentioned is not present in the release, maybe it's still not merged yet.

**Comment by chinhuang007** [comment]
The code is merged. I feel you might not have the latest code base. Can you try the following?
```
git clone https://github.com/onnx/onnx-tensorflow.git
cd onnx-tensorflow
git checkout -b tf-1.x remotes/origin/tf-1.x
pip install -e .
```

**Comment by mnakhaeecourse** [comment]
I still have the problem in using for tensorflow 1.x
