### ISSUE TITLE
NotImplementedError: Gemm version 11 is not implemented.

### ISSUE THREAD

**Issue by futuyao** [onnx/onnx-tensorflow#542]
**Describe the bug**

I'm trying to convert an onnx model into tensorflow, and getting "`NotImplementedError: Gemm version 11 is not implemented`" error.

**To Reproduce**

Running conversion from command line with: `onnx-tf convert -i GoogLeNetPlaces.onnx -o GoogLeNetPlaces.pb`

**ONNX model file**

Here's the model I'm trying to convert: 
https://drive.google.com/file/d/1CfZTL7vl9HaeApIYHYbAWyIetPAPsf2c/view

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.7.6
 - ONNX version: 1.6.0
 - ONNX-TF version: from source (commit ddfea34f1fa528c4d56ed1a3d070af019fac58db)
 - Tensorflow version: 2.1.0

**Additional context**

**Comment by Ehtasha** [comment]
I'm also facing this issue.
Did you find any solution ?

**Comment by futuyao** [comment]
@Ehtasha Not that I know of at the moment.

**Comment by pluradj** [comment]
#554 was merged recently on `master`

**Comment by pluradj** [comment]
See also #558 for `tf-1.x`

**Comment by futuyao** [comment]
Thanks!

**Comment by Hari-Guhan-s** [comment]
i am getting the same issue in rel1.3

**Comment by chinhuang007** [comment]
@Hari-Guhan-s The patch is in the master and tf-1.x branches. It is not officially available yet via pip install. To pick up the fix, please do a source install, https://github.com/onnx/onnx-tensorflow#installation

**Comment by Hari-Guhan-s** [comment]
Thanks

**Comment by Hari-Guhan-s** [comment]
> Thanks @chinhuang007  but as I am using tensorflow 1.14 I cannot move to master branch or tf1.x branch and I did a source installation from rel1.3 

Any update on this issue
