### ISSUE TITLE
onnx to tensorflow conversion error: "module 'tensorflow' has no attribute 'ceil'"

### ISSUE THREAD

**Issue by TheArheus** [onnx/onnx-tensorflow#547]
**Describe the bug**

Hi, I'm trying to import my onnx model, which is exported from PyTorch. But when I tried to to use `prepare()` method, first of all, I started to get errors like this:

```
C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\common\__init__.py:89: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
Traceback (most recent call last):
  File "C:/Users/1/PycharmProjects/untitled/onnx_.py", line 3, in <module>
    from onnx_tf.backend import prepare
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\__init__.py", line 1, in <module>
    from . import backend
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 29, in <module>
    from onnx_tf.common.handler_helper import get_all_backend_handlers
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\common\handler_helper.py", line 5, in <module>
    from onnx_tf.handlers.backend import *  # noqa
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\handlers\backend\ceil.py", line 10, in <module>
    @tf_func(tf.ceil)
AttributeError: module 'tensorflow' has no attribute 'ceil'
```

But after trying to fix all problems like this I got next error:
```
C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\common\__init__.py:89: UserWarning: onnx_tf.common.get_outputs_names is deprecated. It will be removed in future release. Use TensorflowGraph.get_outputs_names instead.
  warnings.warn(message)
Traceback (most recent call last):
  File "C:/Users/1/PycharmProjects/untitled/onnx_.py", line 17, in <module>
    tf_rep = prepare(model)
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "C:\Users\1\Anaconda3\lib\site-packages\onnx_tf\backend.py", line 123, in _onnx_graph_to_tensorflow_rep
    x = tf.placeholder(
AttributeError: module 'tensorflow' has no attribute 'placeholder'
```

**To Reproduce**

My code to reproduce my problem and my onnx model below in next section:
```
import onnx
import warnings
from onnx_tf.backend import prepare


warnings.filterwarnings('ignore')

model = onnx.load_model("model.onnx")

tf_rep = prepare(model)
```

**ONNX model file**

https://drive.google.com/file/d/1NjYMbidm5WOB4SeeBw22dGzn-jZIrU2-/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.7.5 (default, Oct 31 2019, 15:18:51) [MSC v.1916 64 bit (AMD64)]
 - ONNX version: 1.6.0
 - ONNX-TF version: 1.5.0
 - Tensorflow version: 2.2.0-dev20200115

**Comment by geethaaluri** [comment]
Hi @TheArheus, I have the exact error. Were you able to find a solution?
`module 'tensorflow' has no attribute 'ceil'`
`---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-19-b6db7b00a0d2> in <module>
      1 import onnx
      2 
----> 3 from onnx_tf.backend import prepare
      4 
      5 onnx_model = onnx.load("/mnt/efficientnet.onnx")  # load onnx model

/anaconda/envs/image/lib/python3.6/site-packages/onnx_tf/__init__.py in <module>
----> 1 from . import backend

/anaconda/envs/image/lib/python3.6/site-packages/onnx_tf/backend.py in <module>
     27 from onnx_tf.common import get_unique_suffix
     28 from onnx_tf.common import supports_device as common_supports_device
---> 29 from onnx_tf.common.handler_helper import get_all_backend_handlers
     30 from onnx_tf.pb_wrapper import OnnxNode
     31 import onnx_tf.common as common

/anaconda/envs/image/lib/python3.6/site-packages/onnx_tf/common/handler_helper.py in <module>
      3 from onnx import defs
      4 
----> 5 from onnx_tf.handlers.backend import *  # noqa
      6 from onnx_tf.handlers.backend_handler import BackendHandler
      7 

/anaconda/envs/image/lib/python3.6/site-packages/onnx_tf/handlers/backend/ceil.py in <module>
      8 
      9 @onnx_op("Ceil")
---> 10 @tf_func(tf.ceil)
     11 class Ceil(BasicMathMixin, BackendHandler):
     12 

AttributeError: module 'tensorflow' has no attribute 'ceil'
`

**Comment by chinhuang007** [comment]
Please note the current onnx-tf release, v 1.5.0 does not support Tensorflow 2.0. If you build onnx-tf from source using the master branch, you should not see the error.

**Comment by TheArheus** [comment]
@chinhuang007 thank you. This helps

**Comment by jdariasl** [comment]
Hi,

I had the same problem importing prepare method. I installed onnx-ft from source as @chinhuang007 suggested and it worked, but now every time I try to run prepare(onnx_model).run(input) from a jupyter notebook, the kernel died. Python log says Segmentation fault (core dumped). Any idea of what is happening?

**Comment by LukasMosser** [comment]
@jdariasl I am getting exactly the same problem, not from a Jupiter notebook but just a general python script. Is onnx-tf compatible with tensorflow-2.2?

**Comment by chinhuang007** [comment]
Onnx-tf is compatible with Tensorflow 2.2. I just got the latest stable TF 2.2 and prepare works fine. I have (running python util/get_version.py):
Python version:
3.6.9 (default, Nov  7 2019, 10:44:02)
[GCC 8.3.0]
ONNX version:
1.7.0
ONNX-TF version:
1.5.0
Tensorflow version:
2.2.0
If you continue to have the seq fault, please share the onnx file. I can give it a try and debug.

**Comment by avisrazo** [comment]
Hi  @chinhuang007,
I'm also getting this error when I try to import onnx_tf:
 "module 'tensorflow' has no attribute 'ceil'"
I installed in via pip install. Do I need to install it differently?

I'm using
ONNX version:
1.7.0
ONNX-TF version:
1.5.0
Tensorflow version:
2.2.0
Python version 3.7

**Comment by chinhuang007** [comment]
@avisrazo pip install right now still gives you the TF 1.x version of onnx-tf. In order to get the TF 2.2 version, you will need to do an install from source using the master branch, https://github.com/onnx/onnx-tensorflow#installation

**Comment by Eliza-and-black** [comment]
With TF 2.2 version, I manage to convert onnx model to tf.

**Comment by arjunsoin** [comment]
> @avisrazo pip install right now still gives you the TF 1.x version of onnx-tf. In order to get the TF 2.2 version, you will need to do an install from source using the master branch, https://github.com/onnx/onnx-tensorflow#installation

Using: 

onnx 1.7.0
onnx-tf 1.6.0
tensorflow 2.3.0

But now I get INFO:tensorflow:Assets written to: myPath/assets when I call export graph from ONNX. How do I convert a directory with "saved_model.pb", "assets" and "variables" to Tensorflow graph? It seems like "saved_model.pb" is in text format since calling GraphDef on it returns Error: Unable to parse string. Any help will be appreciated

**Comment by justjinn** [comment]
hi chinhuang007, 
I really hope you are still around. I am having a conversion issue when i'm trying to convert a .pth file to a .tf or .tflite file. but i am getting an AttributeError: module 'tf2onnx.convert' has no attribute 'from_onnx'. 

is there a version of onnx that works with tensorflow and tflite?
