### ISSUE TITLE
onnx'op Maxpooling which is not supported great!!!!!

### ISSUE THREAD

**Issue by CConory** [onnx/onnx-tensorflow#571]
The onnx' op Maxpooling which converts to TensorFlow will use a tf.pyfunc, but this way can't freeze to a TensorFlow Pb model!
Is there any good way to freeze the onnx'Maxpooling to a Pb model???

**Comment by fumihwh** [comment]
Try using common attribute...VALID type is preferred...

**Comment by sdmonov** [comment]
@CConory Maxpooling will use pyfunc only in certain situations and with older implementation for < v10 of the ONNX opset. What version of ONNX you are using? There is a new implementation of the maxpool for v10 and later which supports all the cases without using py_func. Also there is a new PR #565 that removes the old code and all versions of the opset will run the latest implementation.

**Comment by chinhuang007** [comment]
The issue should be fixed.
