### ISSUE TITLE
RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 2 (ADD) failed to invoke.

### ISSUE THREAD

**Issue by stev3** [onnx/onnx-tensorflow#581]
Originally posted to tensorflow, but I'm at loss for a solution and the problem could be arrising when converting from onnx to tf. Feel free to disregard if you believe this to be a tensorflow specific issue and thanks in advance for any suggestions/ideas.

System information

OS Platform and Distribution (e.g., Linux Ubuntu 16.04): Ubuntu 18.04
TensorFlow installed from (source or binary): source
TensorFlow version (or github SHA if from source): 1.15

```
import numpy as np
import tensorflow as tf
from PIL import Image

interpreter = tf.lite.Interpreter(model_path="out.tflite")
interpreter.allocate_tensors()
input_details = interpreter.get_input_details()
output_details = interpreter.get_output_details()
print(input_details)
[{'name': 'image', 'index': 21904, 'shape': array([  3, 270, 480], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
print(output_details)
[{'name': 'action', 'index': 7204, 'shape': array([], dtype=int32), 'dtype': <class 'numpy.float32'>, 'quantization': (0.0, 0)}]
input_shape = input_details[0]['shape']
input_data = np.array(np.random.random_sample(input_shape), dtype=np.float32)
interpreter.set_tensor(input_details[0]['index'], input_data)
interpreter.invoke()
output_data = interpreter.get_tensor(output_details[0]['index'])
print(output_data)
```

The output from the converter invocation

```
RuntimeError: Inputs and outputs not all float|uint8|int16 types.Node number 2 (ADD) failed to invoke.
```

Models:
 
https://we.tl/t-kQRi8iB2Qd <-- .onnx
https://we.tl/t-lWH3XmYihS <-- .pb
https://we.tl/t-Bkid4ThzN1 <-- .tflite

Failure details

The conversion is successful and I can run inference on the .pb, but I get the following error when I run inference on the tflite file. Originally trained in pytorch with mobilenetV2 arch.

python==3.6.5
onnx==1.6.0
onnx-tf==1.5.0
tensorflow==1.14.0

**Comment by stev3** [comment]
A followup:

Seems the issue is with a node datatype. Specifically:

```
{'name': 'add_10', 'index': 7205, 'shape': array([2], dtype=int32), 'dtype': <class 'numpy.int64'>, 'quantization': (0.0, 0)}
```

Is this something I can fix at time of conversion (onnx-tf) or something I should fix by changing node in protobuf file?

**Comment by codeislife99** [comment]
Did you fix this ? I am facing the same issue

**Comment by codeislife99** [comment]
After investigating I have found that this is indeed not a onnx-tf issue. While visualizing the tf graph in netron, I saw that the all nodes are indeed float32.

**Comment by sdac** [comment]
If solved, please share you solution. I am facing the same issue.

**Comment by jaggernaut007** [comment]
Same issue here. trying to use netron to debug this issue

**Comment by chinhuang007** [comment]
Please share the onnx file if possible for debugging.

**Comment by jaggernaut007** [comment]
Yes sure.

Here is the onnx file. 
https://drive.google.com/file/d/1SjJmqIhHiacwZZhv57OrT1nCM_KEv7Kk/view?usp=sharing

I have converted this to tensorflow then to tflite using the code below.
https://colab.research.google.com/gist/jaggernaut007/efe78df81a697c2f39652cb0cbe88169/untitled0.ipynb

**Comment by chinhuang007** [comment]
@jaggernaut007 This doesn't seem a problem from onnx-tf converter. The original model has inputs and outputs with float32. THe onnx file converts to TF pb with the PR, https://github.com/onnx/onnx-tensorflow/pull/622. So I believe the fix should be in the tf.lite converter.

**Comment by jaggernaut007** [comment]
Cool Got it.
TF lite team also has helped out in solving this issue. 
Thanks for your help. great to see TF pb conversion is also done.
Kudos to the team!

**Comment by chinhuang007** [comment]
Glad your problem is resolved.
