### ISSUE TITLE
cannot load a model for which operation name starts with '_'

### ISSUE THREAD

**Issue by shas19** [onnx/onnx-tensorflow#589]
cannot load a model for which operation name starts with '_'

**To Reproduce**
```
import onnx
import torch
import onnxruntime
from onnx_tf.backend import prepare

model = onnx.load("model_name.onnx")
dummy_input = torch.randn(1, 1, 64, 256, 256).cpu().numpy()
output = prepare(model).run(dummy_input) 
```

**ONNX model file**
Cannot share the model. But names of all nodes are similar to `_layers.0.block1.bn1.running_mean`

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.9
 - ONNX version: 1.2.0
 - ONNX-TF version: 1.5.0
 - Tensorflow version: 2.1.0

**Additional context**
Seems like there is an open PR #348 for scope naming, but it is still pending for long time. 
What is the best way to address this issue?

**Comment by shas19** [comment]
Currently I am just adding this snippet of code 
```
for init_vals in model.graph.initializer:
	init_vals.name = 'tf_' + init_vals.name

for inp in model.graph.input:
	inp.name = 'tf_' + inp.name

for op in model.graph.output:
	op.name = 'tf_' + op.name

for node in model.graph.node:
	node.name = 'tf_' + node.name
	for i in range(len(node.input)):
		node.input[i] = 'tf_' + node.input[i]
	for i in range(len(node.output)):
		node.output[i] = 'tf_' + node.output[i]	
```

**Comment by chinhuang007** [comment]
Thanks for suggesting the solution. This issue should be fixed with the latest master. If not, please reopen

**Comment by zaytsevand** [comment]
Looks like it's still a thing on a latest master
