### ISSUE TITLE
SSD ONNX Model not able to pass onnx_tf.backend.prepare

### ISSUE THREAD

**Issue by rit7897** [onnx/onnx-tensorflow#599]
Hi the ssd onnx model is thowing out error of ValueError: None values not supported, when i ran onnx_tf.backend.prepare.
please help me out
![Screenshot from 2020-03-23 20-09-28](https://user-images.githubusercontent.com/15844690/77328209-3dc7e100-6d42-11ea-9466-c0e207bb335d.png)

**Comment by chinhuang007** [comment]
@rit7897 Looks like slice is not handling dynamic input shape. Can you please provide the onnx file?

**Comment by chinhuang007** [comment]
Just checked and believe the slice issue was fixed by this PR https://github.com/onnx/onnx-tensorflow/pull/543. If you want, please verify with an onnx-tf build from source using the master branch and TF 2.x.

**Comment by chinhuang007** [comment]
Close because the issue is fixed.
