### ISSUE TITLE
TypeError: Value passed to parameter 'x' has DataType bool not in list of allowed values: bfloat16, float16, float32, float64

### ISSUE THREAD

**Issue by heliqi** [onnx/onnx-tensorflow#600]
**Describe the bug**

While trying to convert the model from onnx to tensorflow i encountered the following issue

TypeError: Value passed to parameter 'x' has DataType bool not in list of allowed values: bfloat16, float16, float32, float64 ...etc

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.8
 - ONNX version:  1.6.0
 - ONNX-TF version:1.5.0
 - Tensorflow version: 1.15.0
 
Note:
Error info  show: this error occurred in the tensorflow_core/python/framework/op_def_library.py code. 
error op is  "mul",  describe 'x' must be 'bfloat16, float16, float32, float64 ...etc', not be  bool.

How can I solve this problem？

**Comment by heliqi** [comment]
Through print info, I find "Expand" has a problem. When x.dtyoe is tf.bool,  'x * ones' is an error.  Because the input of tf.Mul must not be  tf.bool type.
```
@onnx_op("Expand")
class Expand(BackendHandler):

  @classmethod
  def version_8(cls, node, **kwargs):
    tensor_dict = kwargs["tensor_dict"]
    x, shape = tensor_dict[node.inputs[0]], tensor_dict[node.inputs[1]]
    ones = tf.ones(shape, dtype=x.dtype)
    return [x * ones]
```
https://github.com/onnx/onnx-tensorflow/blob/c4fc047e7ec71daa6aa8f71e9cc2ee9e5a3768b6/onnx_tf/handlers/backend/expand.py#L15

**Comment by chinhuang007** [comment]
Good catch! A patch coming soon.

**Comment by GotG** [comment]
hello, i pip installed onnx-tf and i still get this error:
'TypeError: Value passed to parameter 'input' has DataType bool not in list of allowed values: float32, float64, int32, uint8, int16, int8, complex64, int64, qint8, quint8, qint32, bfloat16, uint16, complex128, float16, uint32, uint64'
