### ISSUE TITLE
Cannot import onnx_tf: module 'onnx_tf' has no attribute 'common'

### ISSUE THREAD

**Issue by salernoa** [onnx/onnx-tensorflow#606]
**Describe the bug**

Cannot import `onnx_tf`. `onnx_tf.backend` fails to import `onnx_tf.common`, yielding

```python
AttributeError: module 'onnx_tf' has no attribute 'common'
```

**To Reproduce**

1. Installed `onnx-tensorflow` from master branch using the README instructions:
```linux
git clone https://github.com/onnx/onnx-tensorflow.git && cd onnx-tensorflow.
pip install -e .
```

2. Tried to import `onnx_tf` per the README (to start ONNX model inference with Tensorflow backend):

```python

import onnx
from onnx_tf.backend import prepare
```

```python
d:\projects\onnx-tensorflow\onnx_tf\__init__.py in <module>
----> 1 from . import backend

d:\projects\onnx-tensorflow\onnx_tf\backend.py in <module>
     29 from onnx_tf.common.handler_helper import get_all_backend_handlers
     30 from onnx_tf.pb_wrapper import OnnxNode
---> 31 import onnx_tf.common as common

AttributeError: module 'onnx_tf' has no attribute 'common'
```
3. Checked to make sure the `\onnx_tf\common\__init__.py` exists, which it does.

**Python, ONNX, ONNX-TF, Tensorflow version**

- Python version: 3.6.10 
- ONNX version: 1.6.0
- ONNX-TF version: 1.5.0
- Tensorflow version: 2.1.0

**Comment by salernoa** [comment]
Was able to accomplish what I needed via the CLI instead.

**Comment by zhaoyewei** [comment]
> Was able to accomplish what I needed via the CLI instead.

How do you solve it?
