### ISSUE TITLE
ValueError: '_blocks.0._bn1.bias' is not a valid node name

### ISSUE THREAD

**Issue by ahmadmuqry** [onnx/onnx-tensorflow#609]
I am trying to load ONNX model that was converted from pytorch framework as tensorflow using the onnx_tf.backend. It raises an error saying that the specified node name isn't valid. How do I fix this?

`# Convert onnx model to tensorflow format
import onnx
from onnx_tf.backend import prepare

model = onnx.load('weights/efficientnet-b0/output/health-ID-efficientnet-b0.onnx')
tf_rep = prepare(model)`

`---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
 in 
      4 
      5 model = onnx.load('weights/efficientnet-b0/output/health-ID-efficientnet-b0.onnx')
----> 6 tf_rep = prepare(model)

c:\users\user\desktop\onnx-tensorflow\onnx_tf\backend.py in prepare(cls, model, device, strict, logging_level, **kwargs)
     63     common.logger.setLevel(logging_level)
     64 
---> 65     return cls.onnx_model_to_tensorflow_rep(model, strict)
     66 
     67   @classmethod

c:\users\user\desktop\onnx-tensorflow\onnx_tf\backend.py in onnx_model_to_tensorflow_rep(cls, model, strict)
     83     else:
     84       opset_import = model.opset_import
---> 85     return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
     86 
     87   @classmethod

c:\users\user\desktop\onnx-tensorflow\onnx_tf\backend.py in _onnx_graph_to_tensorflow_rep(cls, graph_def, opset, strict)
    104       if graph_def.initializer:
    105         input_dict_items = cls._onnx_initializer_to_input_dict_items(
--> 106             graph_def.initializer)
    107         initialized = {init.name for init in graph_def.initializer}
    108       else:

c:\users\user\desktop\onnx-tensorflow\onnx_tf\backend.py in _onnx_initializer_to_input_dict_items(cls, initializer)
    218                  dtype=data_type.onnx2tf(init.data_type),
    219                  name=validate_initializer_name(init.name)))
--> 220             for init in initializer]
    221 
    222   @classmethod

c:\users\user\desktop\onnx-tensorflow\onnx_tf\backend.py in (.0)
    218                  dtype=data_type.onnx2tf(init.data_type),
    219                  name=validate_initializer_name(init.name)))
--> 220             for init in initializer]
    221 
    222   @classmethod

~\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\constant_op.py in constant(value, dtype, shape, name)
    256   """
    257   return _constant_impl(value, dtype, shape, name, verify_shape=False,
--> 258                         allow_broadcast=True)
    259 
    260 

~\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\constant_op.py in _constant_impl(value, dtype, shape, name, verify_shape, allow_broadcast)
    300       attrs={"value": tensor_value,
    301              "dtype": dtype_value},
--> 302       name=name).outputs[0]
    303   return const_tensor
    304 

~\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\ops.py in _create_op_internal(self, op_type, inputs, dtypes, input_types, name, attrs, op_def, compute_device)
   3320           input_types=input_types,
   3321           original_op=self._default_original_op,
-> 3322           op_def=op_def)
   3323       self._create_op_helper(ret, compute_device=compute_device)
   3324     return ret

~\AppData\Roaming\Python\Python37\site-packages\tensorflow_core\python\framework\ops.py in __init__(self, node_def, g, inputs, output_types, control_inputs, input_types, original_op, op_def)
   1702             "Cannot create a tensor proto whose content is larger than 2GB.")
   1703       if not _VALID_OP_NAME_REGEX.match(node_def.name):
-> 1704         raise ValueError("'%s' is not a valid node name" % node_def.name)
   1705       c_op = None
   1706     elif type(node_def).__name__ == "SwigPyObject":

ValueError: '_blocks.0._bn1.bias' is not a valid node name`

**Comment by hemin110** [comment]
how to resolve?

**Comment by chinhuang007** [comment]
@hemin110 If you want to help solve this issue, please look into TF restrictions on node names. We will need to convert unsupported characters, such as a leading underscore, based on https://github.com/tensorflow/tensorflow/blob/77245d07d13522a5cb5d060390fffa1894df5bbf/tensorflow/python/framework/ops.py#L1709

**Comment by chinhuang007** [comment]
@ahmadmuqry A PR is created, https://github.com/onnx/onnx-tensorflow/pull/643. Please check if it fixes your issue.

**Comment by amitrokade47** [comment]
This issue is present in 1.x branch as well? Is there any fix for that?
