### ISSUE TITLE
Troubles during converting from TF model to TFlite

### ISSUE THREAD

**Issue by MaratZakirov** [onnx/onnx-tensorflow#614]
**Describe the bug**

I use following code  to convert yollo3 based model from PyTorch to TFLite. 
First I convert to ONNX format and then convert it using onnx_tf converter
and then trying to convert it to TFlite format
My problem is in:
```
2020-05-06 14:56:26.620505: F tensorflow/lite/toco/import_tensorflow.cc:2690] Check failed: status.ok() Unexpected value for attribute 'data_format'. Expected 'NHWC'
Fatal Python error: Aborted
```

**To Reproduce**

Use attached ONNX file and code below
```
    import onnx
    import tensorflow as tf
    from onnx_tf.backend import prepare

    print(tf.__version__)

    model_onnx = onnx.load('./model120.onnx')

    tf_rep = prepare(model_onnx)

    # Export model as .pb file
    tf_rep.export_graph('./model120.pb')
```
And then

```
    import tensorflow as tf
    import numpy as np

    #from_session from_frozen_graph(sess.graph_def
    converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph('./model120.pb', ['test_input'], ['test_output'])
    tflite_model = converter.convert()
```
**ONNX model file**

https://drive.google.com/file/d/10MO9LMdstARlNnV7nCmT4DKFrSbIwbX6/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: Python 3.7.7 (default, Mar 26 2020, 15:48:22)  
 - ONNX version: 1.6.0
 - ONNX-TF version:
commit c4fc047e7ec71daa6aa8f71e9cc2ee9e5a3768b6
Author: Simeon Monov <sdmonov@us.ibm.com>
Date:   Wed Apr 15 01:24:42 2020 +0200
 - Tensorflow version: '2.1.0'

**Additional context**

**Comment by MaratZakirov** [comment]
@sdmonov said that onnx-tensoflow tries to convert NCWH Conv2d to NWHC https://github.com/onnx/onnx-tensorflow/issues/578#issuecomment-625225086 I actually do not see this behavior in practice. For purpose of convertion to NWHC (and convertion to TFlite model) I use project https://github.com/paulbauriegel/tensorflow-tools/blob/master/convert-model-to-NHWC.py

**Comment by sdmonov** [comment]
@MaratZakirov I see you have issue with Conv2d. This is part of the code that is supposed to transpose the input if  it's not running on GPU: https://github.com/onnx/onnx-tensorflow/blob/08e41de7b127a53d072a54730e4784fe50f8c7c3/onnx_tf/handlers/backend/conv_mixin.py#L94-L99 . My guess is you are using a system with a GPU and the code is using  data_format="NCHW" attribute which is not supported in tflite. You can workaround this by forcing the converter to "think" it's a CPU only machine by disabling the CUDA devices with `export CUDA_VISIBLE_DEVICES=`. Hope this helps.

**Comment by sdmonov** [comment]
@MaratZakirov regarding the Dilation2D op used instead of MaxPool there is a fix I submitted yesterday #613 .

**Comment by MaratZakirov** [comment]
> @MaratZakirov regarding the Dilation2D op used instead of MaxPool there is a fix I submitted yesterday #613 .

Will it help in non (1, 1, 1, 1) case?

**Comment by sdmonov** [comment]
If your input to MaxPool op is 4-D (NCHW) and have specified dilations != [1,1] the code will utilize tf.nn.dilation2d with filter shape equal to the kernel shape and containing all zeros as this is the most direct and fast way to do maxpool with dilations in TF. Do you have this case? I tried to download your onnx file but I have no permission to access your google drive.

You can use `git pull origin pull/613/head`. It will create a new commit in your local repo with the merged changes.

**Comment by MaratZakirov** [comment]
> If your input to MaxPool op is 4-D (NCHW) and have specified dilations != [1,1] the code will utilize tf.nn.dilation2d with filter shape equal to the kernel shape and containing all zeros as this is the most direct and fast way to do maxpool with dilations in TF. Do you have this case? I tried to download your onnx file but I have no permission to access your google drive.
> 
> You can use `git pull origin pull/613/head`. It will create a new commit in your local repo with the merged changes.

It is seems that I successfully converted pytorch reset18 and executed it in tflite

**Comment by MaratZakirov** [comment]
@sdmonov I also faced some troubles with `F.interpolate` (not also torch.view somehow fails too) conversion, somehow TFlite converter fails on converting module which is consist just of this operator. Did you have problems like that?

**Comment by chinhuang007** [comment]
PR merged. So close the issue.

**Comment by judeharis** [comment]
> > If your input to MaxPool op is 4-D (NCHW) and have specified dilations != [1,1] the code will utilize tf.nn.dilation2d with filter shape equal to the kernel shape and containing all zeros as this is the most direct and fast way to do maxpool with dilations in TF. Do you have this case? I tried to download your onnx file but I have no permission to access your google drive.
> > You can use `git pull origin pull/613/head`. It will create a new commit in your local repo with the merged changes.
> 
> It is seems that I successfully converted pytorch reset18 and executed it in tflite

Hello, is it possible to share the resnet18 tflite file. Is it quantised in any manner? Would love any steps to repeat this process.
