### ISSUE TITLE
Pytorch -> ONNX -> TFLite: Exact version number for conversion of Mobilenet V2 architecture

### ISSUE THREAD

**Issue by mgarbade** [onnx/onnx-tensorflow#617]
Can someone provide an exact version list for the above mentioned conversion of a vanilla mobilenet v2 from pytorch to tflite via onnx?

I'm trying for days to convert a vanilla mobilenet v2 model from pytorch to tflite, which should be a quite common use case for onnx. Conversion is failing as described here on [stackoverflow](https://stackoverflow.com/questions/61679908/pytorch-convert-2d-cnn-model-to-tflite)

A clear and concise description of what the bug is:

    Exception: <unknown>:0: error: loc("convolution"): 'tf.Conv2D' op is neither a custom op nor a flex op

**Code to Reproduce**
```
import torch
import torch.onnx
import onnx
from onnx_tf.backend import prepare

# Create random input
input_data = torch.randn(1,3,224,224)

# Create network
model = torch.hub.load('pytorch/vision:v0.6.0', 'mobilenet_v2', pretrained=True)
model.eval()

# Forward Pass
output = model(input_data)

# Export model to onnx
filename_onnx = "my_model.onnx"
filename_tf = "my_model.pb"

torch.onnx.export(model, input_data, filename_onnx)

# Export model to tensorflow
onnx_model = onnx.load(filename_onnx)
tf_rep = prepare(onnx_model)
tf_rep.export_graph(filename_tf)
```
then 
```
tflite_convert \
    --output_file=model.tflite \
    --graph_def_file=mv2_200508_6stgs_tfpe_export.pb \
    --input_arrays=input.1 \
    --output_arrays=473 \
    --enable_v1_converter  # <-- needed for conversion of frozen graphs
```

**Python, ONNX, ONNX-TF, Tensorflow version**

```
torch                1.6.0.dev20200508 
tensorflow-gpu       2.2.0
onnx                 1.7.0              
onnx-tf              1.5.0 
```
If a model exported from PyTorch and Caffe2 is having trouble in ONNX-TF, use the next section to attach the model.

**[ONNX model file](https://drive.google.com/open?id=1I9F6RAnfaBG9fyyuOlQUrW_UewWKyV-J)**

`get_version.py` output:
```
Python version:
3.6.10 |Anaconda, Inc.| (default, May  8 2020, 02:54:21) 
[GCC 7.3.0]
ONNX version:
1.7.0
ONNX-TF version:
1.5.0
Tensorflow version:
2.2.0
```

I also tried 
- deeplab model: `model = torch.hub.load('pytorch/vision:v0.6.0', 'deeplabv3_resnet101', pretrained=True)` -> same error as mentioned above ('tf.Conv2D' op is neither a custom op nor a flex op)
- the `tf-1.x` branch with `tensorflow==1.14.0` which leads to the 'NCHW' error
- tensorflow==2.0.0 which leads to `AttributeError: module 'tensorflow' has no attribute 'ceil'`

Maybe a working example in colab would be nice

**Comment by mgarbade** [comment]
There is a conversion working for resnet18 ONLY! (#614), though I haven't yet checked if the converted tflite works on my mobilephone.

configuration:
- python 3.7.7
- pytorch 1.5.0 
- tensorflow-gpu       2.1.0
- tensorflow-addons    0.9.1
- onnx 1.6.0
- onnx-tf installed as described in #614

same configuration with mobilenet v2 gives

     UserWarning: Fail to get since_version of BitShift in domain `` with max_inclusive_version=9. Set to 1.

during `prepare`

and during `tflite_convert` throws the following error:

    2020-05-13 10:54:27.504204: F tensorflow/lite/toco/graph_transformations/resolve_constant_gather.cc:108] Check failed: coords_array.data_type == ArrayDataType::kInt32 Only int32 indices are supported
Fatal Python error: Aborted

**Comment by chinhuang007** [comment]
The warning from prepare is harmless. The pb file is successfully created. So the issue is in the TFLite converter, seemingly with limited supported data types.

**Comment by skyler1253** [comment]
@mgarbade Running into the same issue here.  Did you find a way around this issue to convert to tflite?

**Comment by mgarbade** [comment]
@skyler1253 , kind of
I repost my answer from #579 here, as the issue is marked as 'closed' but problems even after successful conversion persist:

> - There is a fully working conversion example in google Colab as mentioned in [this](https://stackoverflow.com/a/58576060/2191652) stackoverflow answer
> - however the converted model only works on CPU (mobile phone and computer)
> but not on GPU (mobile phone)
> -  also the CPU version is much slower than a corresponding model build in TF directly as mentioned [here](https://stackoverflow.com/a/62343410/2191652)
> 
>

**Comment by chinhuang007** [comment]
The performance issues of the converted models are well-known since there is no matching TF operator for what is in the ONNX spec for the same operator name. An optimization component can be added to onnx-tf. Contribution is always appreciated!
