### ISSUE TITLE
output op cannot find

### ISSUE THREAD

**Issue by syslot** [onnx/onnx-tensorflow#620]
Hi, 
I am trying to convert the model from pytorch to TensorFlow serving pb graph. I refer to [this blog](https://cugtyt.github.io/blog/2019/1216.html) and have successfully converted the model to pb file. When I tried to use tf-serving, the last output node op cannot be found, even though I change output_name to op_name ( 'Add'). Is this the wrong way to use API?

Here is my env:
| package        | version           |
| ------------- |:-------------:|
| python      | 3.7.2 |
| pytorch      |1.0.0 (  also test 1.5.0)     |
| tensorflow | 1.15.0 | 
|onnx |1.6.0 (also test 1.7.0)|
|onnx-tensorflow| 1.5.0|

**Comment by jaggernaut007** [comment]
You might need to change the opset version from pytorch exprter

**Comment by syslot** [comment]
> You might need to change the opset version from pytorch exprter

Thanks for you answering, and what kind of opset version you suggests?

**Comment by jaggernaut007** [comment]
https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status.md
This should answer your question

**Comment by chinhuang007** [comment]
Please provide the onnx file if you continue to have the problem.

**Comment by duaneya** [comment]
Hi，I have the same problem, do you solve this?

**Comment by chinhuang007** [comment]
@duaneya do you have an onnx file for debugging the problem?

**Comment by duaneya** [comment]
> @duaneya do you have an onnx file for debugging the problem?

I solved that by update to latest version

**Comment by chinhuang007** [comment]
Glad to hear that!
