### ISSUE TITLE
Can't Prepare tensorflow model from onnx

### ISSUE THREAD

**Issue by akshayklr057** [onnx/onnx-tensorflow#639]
**Describe the bug**
I was trying to convert a huggingface model to tensorflow. Getting error in "prepare" method of onnx_tf.backend. Getting a key error 'axis', attached below is the entire traceback of error and my model.

I converted a huggingface model trained & saved using pytorch to onnx version, so that I can convert it to tensorflow. 

**To Reproduce**

Please give us instructions to reproduce your problem.

A __self-contained__ piece of code that can demonstrate the problem is required.
`import onnx

from onnx_tf.backend import prepare

onnx_model = onnx.load("./version3.onnx")  # load onnx model
tf_rep = prepare(onnx_model)  # prepare tf representation
tf_rep.export_graph("version3.pb")`

Please do not expect us to have PyTorch, Caffe2 installed.

If a model exported from PyTorch and Caffe2 is having trouble in ONNX-TF, use the next section to attach the model.

**ONNX model file**
My model is hosted here.
https://drive.google.com/file/d/1oYB7cpz9qwtlR0nfIjW7HnIKpzQvlN94/view?usp=sharing

If applicable, attach the onnx model file in question using Gist, DropBox or Google Drive.

**Python, ONNX, ONNX-TF, Tensorflow version**
Python - 3.6
tensorflow - 2.2

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 
 - ONNX version: 
 - ONNX-TF version:
 - Tensorflow version: 

**Additional context**

`2020-06-04 09:23:25,227 - onnx-tf - INFO - Unknown op ConstantFill in domain `ai.onnx`.
2020-06-04 09:23:25,228 - onnx-tf - INFO - Unknown op ImageScaler in domain `ai.onnx`.
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-37-0b06f55f6108> in <module>()
      6 
      7 onnx_model = onnx.load("./version3.onnx")  # load onnx model
----> 8 tf_rep = prepare(onnx_model)  # prepare tf representation
      9 tf_rep.export_graph("version3.pb")

5 frames
/content/onnx-tensorflow/onnx_tf/backend.py in prepare(cls, model, device, strict, logging_level, **kwargs)
     64     common.logger.handlers[0].setLevel(logging_level)
     65 
---> 66     return cls.onnx_model_to_tensorflow_rep(model, strict)
     67 
     68   @classmethod

/content/onnx-tensorflow/onnx_tf/backend.py in onnx_model_to_tensorflow_rep(cls, model, strict)
     84     else:
     85       opset_import = model.opset_import
---> 86     return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
     87 
     88   @classmethod

/content/onnx-tensorflow/onnx_tf/backend.py in _onnx_graph_to_tensorflow_rep(cls, graph_def, opset, strict)
    145                                                      handlers,
    146                                                      opset=opset,
--> 147                                                      strict=strict)
    148         curr_node_output_map = dict(zip(onnx_node.outputs, output_ops))
    149         tensor_dict.update(curr_node_output_map)

/content/onnx-tensorflow/onnx_tf/backend.py in _onnx_node_to_tensorflow_op(cls, node, tensor_dict, handlers, opset, strict)
    247     handler = handlers[node.domain].get(node.op_type, None)
    248     if handler:
--> 249       return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    250     else:
    251       exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type)

/content/onnx-tensorflow/onnx_tf/handlers/handler.py in handle(cls, node, **kwargs)
     58     if ver_handle:
     59       cls.args_check(node, **kwargs)
---> 60       return ver_handle(node, **kwargs)
     61     exception.OP_UNIMPLEMENTED_EXCEPT(node.op_type, cls.SINCE_VERSION)
     62     return None

/content/onnx-tensorflow/onnx_tf/handlers/backend/cumsum.py in version_11(cls, node, **kwargs)
     35     if len(node.inputs) > 1:
     36       # optional 0-D tensor, range [-rank(x), rank(x)-1]
---> 37       axis = tensor_dict["axis"]
     38       inputs.append(axis)
     39 

KeyError: 'axis'`

**Comment by akshayklr057** [comment]
> @akshayklr057 Please provide access to the onnx file.

Provided, please check.

**Comment by chinhuang007** [comment]
There is an open PR about the default for axis, https://github.com/onnx/onnx/pull/2611. Until it is address, we don't really know the correct logic when axis is not provided as an input to cumsum op.

**Comment by chinhuang007** [comment]
With a bit debugging, found the problem in expecting specific input name for cumsum op. A PR is opened, https://github.com/onnx/onnx-tensorflow/pull/640, to patch it.

**Comment by Shiro-LK** [comment]
@akshayklr057  Have you succeed to transform to tensorflow a huggingface model ? (Bert-like model ?)

**Comment by akshayklr057** [comment]
@Shiro-LK no, I have tried all the possible options but there are errors everywhere.
