### ISSUE TITLE
some problem about node.attr in frontend

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#65]
After `frontend.py` L149, I get such `node.attr` as
```
{'padding': s: "SAME"
, 'data_format': s: "NHWC"
, 'strides': list {
  i: 1
  i: 1
  i: 1
  i: 1
}
, 'use_cudnn_on_gpu': b: true
}
```
If I just pass it to `make_node` in `helper.py`, I get
```
{ValueError}Value "s: "NHWC"
" is not valid attribute data type.
```
So I try to get value before `make_node`: `node.attr = dict(map(lambda item: (item[0], get_attribute_value(item[1])), node.attr.items()))`,
then I get
```
{ValueError}Protocol message has no non-repeated submessage field "t"
```
---
So there are two problems
- current `frontend.py` can not handle attr structure (maybe changed?) -> can be fixed with my code above
- how to deal with different behavior between tf protobuf3 and onnx protobuf2 (`HasField` in protobuf3 will cause error) -> create `get_attribute_value` in `onnx-tensorflow` or make `onnx` `get_attribute_value` let it can deal with both protobuf version

**Comment by tjingrant** [comment]
1. The first solution sounds good to me. 
2. I'm not sure what you mean by this:

> make onnx get_attribute_value let it can deal with both protobuf version

Can you explain a bit more?

**Comment by fumihwh** [comment]
@tjingrant 
I mean that rewrite [`get_attribute_value`](https://github.com/onnx/onnx/blob/master/onnx/helper.py#L207) as following:
```
def get_attribute_value(attr):
  if _has_field(attr, 'list'):
    attr = attr.list
  if _has_field(attr, 'f'):
    return attr.f
  elif _has_field(attr, 'i'):
    return attr.i
  elif _has_field(attr, 's'):
    return attr.s
  elif _has_field(attr, 't'):
    return attr.t
  elif _has_field(attr, 'g'):
    return attr.g
  elif _has_field(attr, 'b'):
    return attr.b
  elif _has_field(attr, 'floats') and len(attr.floats):
    return list(attr.floats)
  elif _has_field(attr, 'ints') and len(attr.ints):
    return list(attr.ints)
  elif _has_field(attr, 'strings') and len(attr.strings):
    return list(attr.strings)
  elif _has_field(attr, 'tensors') and len(attr.tensors):
    return list(attr.tensors)
  elif _has_field(attr, 'graphs') and len(attr.graphs):
    return list(attr.graphs)
  else:
    raise ValueError("Unsupported ONNX attribute: {}".format(attr))

def _has_field(message_pb, property_name):
  """Determine if a field is set on a protobuf.
  :type message_pb: :class:`google.protobuf.message.Message`
  :param message_pb: The message to check for ``property_name``.
  :type property_name: str
  :param property_name: The property value to check against.
  :rtype: bool
  :returns: Flag indicating if ``property_name`` is set on ``message_pb``.
  """
  # NOTE: As of proto3, HasField() only works for message fields, not for
  #       singular (non-message) fields. First try to use HasField and
  #       if it fails (with a ValueError) we manually consult the fields.
  try:
    return message_pb.HasField(property_name)
  except ValueError:
    all_fields = set([field.name for field in message_pb._fields])
    return property_name in all_fields
```

Then, onnx's `get_attribute_value` can handle pbs both protobuf2 and protobuf3.
Another choice is put above source inside `onnx-tensorflow`.

**Comment by fumihwh** [comment]
So I am here. `onnx`'s `get_attrbute_value` checks fields (f, g, ints, floats, strings, tensors, graphs) that does not exist in [`AttrValue`](https://github.com/tensorflow/tensorflow/blob/r1.6/tensorflow/core/framework/attr_value.proto).
Maybe we should make `get_attribute_value` inside `onnx-tensorflow`?
```
def get_attribute_value(attr):
    if attr.HasField('f'):
        return attr.f
    elif attr.HasField('i'):
        return attr.i
    elif attr.HasField('s'):
        return attr.s
    elif attr.HasField('t'):
        return attr.t
    elif attr.HasField('g'):
        return attr.g
    elif len(attr.floats):
        return list(attr.floats)
    elif len(attr.ints):
        return list(attr.ints)
    elif len(attr.strings):
        return list(attr.strings)
    elif len(attr.tensors):
        return list(attr.tensors)
    elif len(attr.graphs):
        return list(attr.graphs)
    else:
        raise ValueError("Unsupported ONNX attribute: {}".format(attr))
```

**Comment by tjingrant** [comment]
It occurs to me that we need proper sanitization before passing it to `make_node` b/c ONNX does not accept the `data_format` attribute. Also, I don't think there's Conv op in the frontend yet (and that's part of the reason why `data_format` attribute wasn't filtered out..). Am I missing something? I don't see why we need to get its attribute.

**Comment by fumihwh** [comment]
Just leave `data_format`, attr I mentioned at first is just a example, my local works.
The point is I think we can not just use `onnx`'s `get_attribute_value ` because it contains unneeded checkers.

**Comment by tjingrant** [comment]
Can you push your local (as I understand, your local is your proposed changes right?) as a work in progress PR so we can actually look at the code?

**Comment by fumihwh** [comment]
I've created a PR. I think it shows how do I handle above problems.
You can get example pb: https://www.dropbox.com/s/5qd8tlbzesyh6z6/tf_gh_mnist.pb?dl=0
