### ISSUE TITLE
Cannot convert onnx model to pb model because of "OneHot depth must be in int32 but it is currently in <dtype: 'int64'> which is not supported in Tensorflow"

### ISSUE THREAD

**Issue by baopanda** [onnx/onnx-tensorflow#666]
Hi all, I have a pytorch model and trying to convert it to tensorflow model but I have a bug that I can't fix. Anyone can help me? 
Because all of my tensors in pytorch model are Long Tensor (int64) but one onnx-tf just support int64 type in Onehot deplth.
RuntimeError: OneHot depth must be in int32 but it is currently in <dtype: 'int64'> which is not supported in Tensorflow.
Can I convert into int64 to export the graph in onnx model? 
Thank you in advance.

**Comment by baopanda** [comment]
Done

**Comment by HaoYang0123** [comment]
> Done

how did you do? I have the same problem.

**Comment by unsw-luopan** [comment]
+1, how did you solve that problem, could you share your method?
