### ISSUE TITLE
TypeError: pad() got multiple values for argument 'name'

### ISSUE THREAD

**Issue by sayakpaul** [onnx/onnx-tensorflow#673]
I am trying to convert the PyTorch checkpoints of [`tunit`](https://github.com/clovaai/tunit) model to TensorFlow using ONNX. I was able to generate the ONNX files but I could not export the TensorFlow file from the ONNX files and ended up with the following error:

![image](https://user-images.githubusercontent.com/22957388/84979370-effa2380-b14c-11ea-815d-88c6e90e4386.png)

Here's the [Colab Notebook](https://colab.research.google.com/gist/sayakpaul/1372e124eedab998f39eb59d358faa35/scratchpad.ipynb) that reproduces the issue. Please note that I used the animalFaces10_0_00 pre-trained checkpoints. I first copied the files from [here](https://drive.google.com/drive/folders/1rU1B9OLQjYMBzU6VQX7UwLxod2WzOfNz?usp=sharing) to my personal Drive, created a folder called animalFaces10_0_00, and copied the files to that folder.

**Comment by chinhuang007** [comment]
There is a recent fix https://github.com/onnx/onnx-tensorflow/pull/650. Please install tensorflow 2.2 and do a source build for onnx-tf. The problem should be resolved.

**Comment by sayakpaul** [comment]
Thanks. That solved the issue.

**Comment by Zhoushanglin100** [comment]
Is there a way I can fix this problem when using tf 1.x? I need to use tensorflow 1.x version because of some other requirements. Thanks!

**Comment by chinhuang007** [comment]
Yes, we will backport the fix into the tf-1.x branch. A PR will be created shortly and a new onnx-tf release should be available in about a week.

**Comment by huangguanbin** [comment]
> Thanks. That solved the issue.

How did you solve the issue?  I changed tf to tf1.x. But I got this error.  (the major issue is at the last line). Can you tell me how to convert onnx to tensorflow, plz? 

TypeError                                 Traceback (most recent call last)
<ipython-input-2-9d7b223cb53e> in <module>()
      7 
      8 model = onnx.load('reidmodel.onnx')
----> 9 tf_rep = prepare(model)

8 frames
/usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend_handler.py in _run_tf_func(cls, tf_func, inputs, attrs)
    180     attrs = cls._process_attrs(attrs)
    181     return tf_func(*inputs,
--> 182                    **dict([(p, attrs[p]) for p in params if p in attrs]))

TypeError: pad() got multiple values for argument 'name'

**Comment by sayakpaul** [comment]
@huangguanbin I am in TensorFlow 2.

**Comment by Tristacheng** [comment]
> > Thanks. That solved the issue.
> 
> How did you solve the issue? I changed tf to tf1.x. But I got this error. (the major issue is at the last line). Can you tell me how to convert onnx to tensorflow, plz?
> 
> TypeError Traceback (most recent call last)
> in ()
> 7
> 8 model = onnx.load('reidmodel.onnx')
> ----> 9 tf_rep = prepare(model)
> 
> 8 frames
> /usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend_handler.py in _run_tf_func(cls, tf_func, inputs, attrs)
> 180 attrs = cls._process_attrs(attrs)
> 181 return tf_func(*inputs,
> --> 182 **dict([(p, attrs[p]) for p in params if p in attrs]))
> 
> TypeError: pad() got multiple values for argument 'name'

have you solved it? I got same problem in tf1.15

**Comment by Tristacheng** [comment]
> > > Thanks. That solved the issue.
> > 
> > 
> > How did you solve the issue? I changed tf to tf1.x. But I got this error. (the major issue is at the last line). Can you tell me how to convert onnx to tensorflow, plz?
> > TypeError Traceback (most recent call last)
> > in ()
> > 7
> > 8 model = onnx.load('reidmodel.onnx')
> > ----> 9 tf_rep = prepare(model)
> > 8 frames
> > /usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend_handler.py in _run_tf_func(cls, tf_func, inputs, attrs)
> > 180 attrs = cls._process_attrs(attrs)
> > 181 return tf_func(*inputs,
> > --> 182 **dict([(p, attrs[p]) for p in params if p in attrs]))
> > TypeError: pad() got multiple values for argument 'name'
> 
> have you solved it? I got same problem in tf1.15

I solved it refers to https://github.com/onnx/onnx-tensorflow/pull/650/commits/6685fd45a4f1d0607156eaa03149114f213927dc
