### ISSUE TITLE
Cannot convert a model from onnx to tf

### ISSUE THREAD

**Issue by alex96295** [onnx/onnx-tensorflow#675]
Hello,

I am converting this model --> http://www.mediafire.com/file/rt3etotdplgrop5/mbntv2_sqzdet_eval.onnx/file
to tensorflow. I have version 1.15.0 and followed the list of instructions for installation of onnx-tensorflow.

Nevertheless, this error message appears when I am converting the model:

![Cattura](https://user-images.githubusercontent.com/62642743/85075669-fa550580-b1be-11ea-8ca9-0b697ad1a1c4.PNG)

It seems that this module tensorflow-addons is missing, I don't know if it should have been installed with onnx.tensorflow or not. If I install it with pip install tensorflow-addons, it rise another error since perhaps tensorflow-addons is suited for tf 2.X and not 1.X versions.

Where am I doing something wrong? I leave you the model if you want to try, maybe it is a problem of the model itself

**Comment by winnietsang** [comment]
@alex96295 Since you are running on Tensorflow 1.15, please use branch tf-1.x to convert your ONNX model. The master branch expect Tensorflow 2.x is installed on your environment, that's why you see the error message you stated above.

**Comment by alex96295** [comment]
@winnietsang Thank you for the reply
Indeed I am referring to this webage: https://github.com/onnx/onnx-tensorflow/tree/tf-1.x

Even though, to be honest, I can't read the difference in the Installation guide command line istruction with respect to the tf-2.x version, the commands seem the same. The onyl thing I had changed is this line:

```git clone git@github.com:onnx/onnx-tensorflow.git && cd onnx-tensorflow```

for which the git@ does not work for me and therefore - as I read in a past issue - I used

``` git clone https://github.com/onnx/onnx-tensorflow.git && cd onnx-tensorflow```

Is this right according to you?

**Comment by winnietsang** [comment]
@alex96295 Thanks for point this out. We didn't mention about switch to the tf-1.x branch in the instruction at all, no wonder you are confuse. I will update that in my PR #676. Here is the instruction to checkout tf-1.x branch:
git clone https://github.com/onnx/onnx-tensorflow.git 
cd onnx-tensorflow
git branch -a
git checkout -b tf-1.x remotes/origin/tf-1.x
pip install -e .

**Comment by alex96295** [comment]
@winnietsang THanks a lot, I'll try this out and come back to you, please don't close the issue

**Comment by alex96295** [comment]
@winnietsang It worked with your instructions, so probably I haven't switched to the 1.x branch, thank you

Just one thing, it didn't recognize the portion of the conversion command '-t tf' so I removed it: is it important?

**Comment by winnietsang** [comment]
@alex96295 '-t tf' should be removed from the documentation, thanks for pointing it out. I will update it in my PR.

**Comment by alex96295** [comment]
Ok, so I don't have further questions

Thank you!
