### ISSUE TITLE
description misleads

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#68]
`Tensorflow Backend for ONNX` mislead people. 
Even member from onnx create a new repository `tensorflow-onnx` for converting TensorFlow models to ONNX.
Maybe we should change the description.

**Comment by tjingrant** [comment]
Indeed that's my bad. Our frontend support is not very mature yet so I didn't put it out there... Maybe it's time to make it clear.

**Comment by fumihwh** [comment]
@tjingrant We should fix README.md also. And....let's do more at frontend side!!!

**Comment by tjingrant** [comment]
@fumihwh definitely... Sorry I have been very busy at the beginning of the week, now I'm much freer and will concentrate on ONNX.
