### ISSUE TITLE
pass additional args to handlers

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#69]
Currently we pass `consts` to handlers in frontend, but in some case, we need more to deal with ops.
For example, at least we need input shape to calculate pad size for pooling and conv because `SAME` and `VALID` is deprecated.
So I have to pass all ops' `_output_shape` to handlers.

Then, there are three questions:
1. do we really need additional args
2. if 1 is yes, what should we pass to handlers
3. how to do that in a smart way

**Comment by tjingrant** [comment]
I think for _output_shape, we can just keep it in the proto attribute instead of a parameter to the handler? I feel like this is easier to handle.

**Comment by fumihwh** [comment]
Actually, I need previous node's `_ouput_shape`....

**Comment by tjingrant** [comment]
Ah, so it's really `input_shape`. In this case, yes, let's put it in the kwargs then.
