### ISSUE TITLE
KeyError: 'identity_out' when trying to export tf_rep  (graph output name conversion issue)

### ISSUE THREAD

**Issue by amitrokade47** [onnx/onnx-tensorflow#699]
I ran the following to try to convert the .onnx file to tensorflow 
`onnx_model = onnx.load("model.onnx")`
`tf_rep = onnx_tf.backend.prepare(onnx_model)`
`

tf_rep.export_graph("/tmp/sample_onnx_to_tf.pb")`

Python version: 3.6
ONNX version: 1.6.0
ONNX-TF version: 1.5.0
Tensorflow version: 1.15

I get the following error:
Traceback (most recent call last):
    tf_rep.export_graph("/tmp/sample_onnx_to_tf.pb")
  File "miniconda3/envs/algdev/lib/python3.6/site-packages/onnx_tf/backend_rep.py", line 108, in export_graph
    ':0', '')] = output_name
KeyError: 'identity_out'

(my graph output name is 'identity_out')

I observed that inside the backend.py file here https://github.com/onnx/onnx-tensorflow/blob/c60a32caef3271b93e843bac7a44eda388f67165/onnx_tf/backend.py#L148-L159 
The outputs are getting stored in tensor_dict with some form of name conversion but the tf_rep ouputs on line 158 are not converted and this unconverted output names are being accessed by the dictionary.
Maybe this is what is causing the issue, correct me if I'm wrong.

I have attached the onnx model I am using 
[onnx_file.zip](https://github.com/onnx/onnx-tensorflow/files/4920670/onnx_file.zip)

**Comment by chinhuang007** [comment]
Thanks for reporting the issue. I just successfully converted your model.onnx with no errors using a source build from the tf-1.x branch. Please make sure your onnx-tf is coming from the correct branch since our master branch works only for Tensorflow 2.x.

**Comment by amitrokade47** [comment]
Switched to 1.x branch and it worked
