### ISSUE TITLE
remove consts/inputs after use them as attr in frontend

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#70]
In case input in TF which is attr in onnx, such as `handle_reshape`:
```
  @classmethod
  def handle_reshape(cls, node, consts):
    assert node.inputs[1] in consts.keys()
    shape = consts[node.inputs[1]]
    return helper.make_node("Reshape",
                            [node.inputs[0]],
                            [node.name],
                            shape=shape)
```
After use it as an attr of node `Reshape`, it should not be a `initializer` or `input` anymore.
We should delete it from graph. (remove them from `inputs_proto` and `consts_proto`)

**Comment by tjingrant** [comment]
That's very nice.
