### ISSUE TITLE
MaxPool_with_argmax indices issue

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx-tensorflow#719]
MaxPool_with_argmax only return indices that are in channel last format. The current code only works with input data that have one channel only. 
For multiple channels support, may need to convert the "index values" to the original data format like NCHW.

**Comment by chinhuang007** [comment]
@sdmonov can you please take a look? Thanks.

**Comment by winnietsang** [comment]
PR #726 will fix this issue
