### ISSUE TITLE
duplicate repository for converting tensorflow->onnx

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#72]
@tjingrant 
I mentioned in another issue that there is a duplicate repository for converting tensorflow->onnx.
And maybe we should discuss how to deal with this.
https://github.com/onnx/tensorflow-onnx/issues/1

**Comment by fumihwh** [comment]
@guschmue

**Comment by tjingrant** [comment]
Closing because the issue has been resolved. Integration has commenced.
