### ISSUE TITLE
Some tests fail to run on Mac against ONNX 1.7.0

### ISSUE THREAD

**Issue by pluradj** [onnx/onnx-tensorflow#721]
**Describe the bug**

I attempted to run `python test/backend/test_node.py` and encountered this error:

```
[libprotobuf ERROR google/protobuf/descriptor_database.cc:394] Invalid file descriptor data passed to EncodedDescriptorDatabase::Add().
[libprotobuf FATAL google/protobuf/descriptor.cc:1356] CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
libc++abi.dylib: terminating with uncaught exception of type google::protobuf::FatalException: CHECK failed: GeneratedDatabase()->Add(encoded_file_descriptor, size):
Abort trap: 6
```

This error does not appear when using ONNX 1.6.0 on Mac. Not an issue on Ubuntu 18.04 or Windows Server 2016 either.

**To Reproduce**

Running on macOS Catalina Version 10.15.6 with Python 3.6.10

```
pip install onnx==1.7.0 tensorflow==2.2.0 tensorflow-addons==0.10.0 pytest tabulate
git clone https://github.com/onnx/onnx-tensorflow.git
cd onnx-tensorflow/
git checkout rel-1.6.0
pip install -e .
python test/backend/test_node.py TestNode.test_add
```

**ONNX model file**

N/A

**Python, ONNX, ONNX-TF, Tensorflow version**

Python version:
3.6.10 (default, Jul  9 2020, 23:47:59)
[GCC 4.2.1 Compatible Apple LLVM 11.0.3 (clang-1103.0.32.62)]
ONNX version:
1.7.0
ONNX-TF version:
1.6.0
Tensorflow version:
2.2.0

**Additional context**

This is similar to issue reported on tf2onnx https://github.com/onnx/tensorflow-onnx/issues/1002. The fix there was to `import onnx` before tensorflow related imports. I'm not clear on what the underlying cause is, but I have a pull request prepared for a similar fix in `test_node.py` and `test_dynamic_shape.py` which allows these tests to run. `test_cli.py`, `test_model.py`, and `test_onnx_backend.py` were able to run without any changes.

**Comment by chinhuang007** [comment]
Here is a similar issue in ONNX, with a reference link to Catalina's new security requirements, https://github.com/onnx/onnx/issues/2940#issuecomment-669447747
