### ISSUE TITLE
How to use converted pb?

### ISSUE THREAD

**Issue by JuHyung-Son** [onnx/onnx-tensorflow#727]
Hi,
I read the converted output is graphdef and converting to saved model is in progress.
And this [link](https://stackoverflow.com/questions/44329185/convert-a-graph-proto-pb-pbtxt-to-a-savedmodel-for-use-in-tensorflow-serving-o/44329200#44329200) is for tensorflow 1.0.

Should I convert onnx model to graphdef and then convert it to saved model using tensorflow 1?
or is there another way to do it??

**Comment by cenkbircanoglu** [comment]
+1

**Comment by chinhuang007** [comment]
The current converted output is a graphdef. You can construct the graphdef in a session and use tensorflow 1 api to make a SavedModel. However the api is removed in TF 2; therefore a PR is created to change the converted output as a SavedModel, https://github.com/onnx/onnx-tensorflow/pull/603

**Comment by matinehshaker** [comment]
@chinhuang007 
Similar question here. Will appreciate your help. I have converted my onnx file to tensorflow pb file. Now I need to read the tensorflow pb file from the disk and load it to a tensorflow session in python. How can I do that? Is a single pb file enough? I have to use tensorflow version 1.15.2. So I'm using tf-1.x brach of onnx-tensorflow repo. 

I know there's tf.saved_model.load method in tensorflow, but not sure how to use it or if it's the right way of loading pb file. I don't know what should be tags input.

I see you're suggesting "construct the graphdef in a session and use tensorflow 1 api to make a SavedModel. " Can you please elaborate on that? Are there examples or code snippets on how this could be done?

Thank you very much in advance.

**Comment by chinhuang007** [comment]
The SavedModel format is for the master branch, applicable only for Tensorflow 2.x. The exported file is still a graph pb if you are using tf-1.x branch. That means you can use graph util api, https://www.tensorflow.org/versions/r1.15/api_docs/python/tf/graph_util/import_graph_def, to load the graph from the pb file.

The following code will return the graph in a pb file:

def load_graph(frozen_graph_filename):
    # We load the protobuf file from the disk and parse it to retrieve the
    # unserialized graph_def
    with tf.gfile.GFile(frozen_graph_filename, "rb") as f:
        graph_def = tf.GraphDef()
        graph_def.ParseFromString(f.read())
    # Then, we import the graph_def into a new Graph and returns it
    with tf.Graph().as_default() as graph:
        tf.import_graph_def(graph_def)
    return graph

Then you can use the graph in a session like

with tf.Session(graph=graph) as sess:
     my_out = sess.run(some_data)

**Comment by matinehshaker** [comment]
@chinhuang007 Thanks for your response. Very helpful.
I have a follow up questions. So when import graph_def to the default graph of tf session, how do I know which tensor is input and which one is output? I see solutions like this:

input_tensor = graph.get_tensor_by_name(INPUT_TENSOR_NAME)
output_tensor = graph.get_tensor_by_name(OUTPUT_TENSOR_NAME)

However, I use a separate service which just gives me the pb file after it converts onnx to tf pb. Does this mean I need to modify the service so that it also extracts INPUT_TENSOR_NAME and OUTPUT_TENSOR_NAME from the onnx file?

**Comment by chinhuang007** [comment]
@matinehshaker correct. Unfortunately TF GraphDef doesn't have APIs for input and output names. The names can be extracted from the onnx file or collected using onnx_tf TensorflowRep APIs.

**Comment by matinehshaker** [comment]
Thank you very much for the response. Again very useful.

I am now dealing with another issue when using `tf.import_graph_def(graph_def)`:

File "/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
producer_op_list=producer_op_list)
File "/lib/python3.6/site-packages/tensorflow_core/python/framework/importer.py", line 505, in _import_graph_def_internal
raise ValueError(str(e))
ValueError: Node 'output:0': Node name contains invalid characters

I set the node name when converting original TF to ONNX using tf2onnx. (then onnx to TF PB, then to TF GraphDef). This is tf2onnx code, one of their examples:

`
import tf2onnx
import tensorflow as tf

with tf.Session() as sess:
  x = tf.placeholder(tf.float32, [2, 3], name="input")
  x_ = tf.add(x, x)
  _ = tf.identity(x_, name="output")
  onnx_graph = tf2onnx.tfonnx.process_tf_graph(sess.graph, input_names=["input:0"], output_names=["output:0"])
  model_proto = onnx_graph.make_model("test")
  with open("/tmp/model.onnx", "wb") as f:
  f.write(model_proto.SerializeToString())
`
Without setting input_names=["input:0"] and output_names=["output:0"], I won't be able to extract input, output nodes from onnx_model or tf_representation using onnx_tf. So I have to do that, but full round trip process of TF -> ONNX -> TF PB -> TF GraphDef doesn't work still. 

I know it's partly related to tf2onnx too, but I wonder if you have any insights. 

Thanks.

**Comment by chinhuang007** [comment]
The name rule is "^[A-Za-z0-9.][A-Za-z0-9_.\\/>-]*$" as seen https://github.com/tensorflow/tensorflow/blob/582c8d236cb079023657287c318ff26adb239002/tensorflow/python/framework/ops.py#L1801. So you could try input/output names without colon.
