### ISSUE TITLE
Need to support ONNX operators introduced or changed in opset 13

### ISSUE THREAD

**Issue by winnietsang** [onnx/onnx-tensorflow#728]
1.	Abs
4.	Concat (#753)
5.	Constant (#753)
6.	DepthToSpace
7.	DequantizeLinear
8.	Div
10.	Equal
13.	Expand
14.	Flatten
16.	Gather
17.	GatherElements 
19.	Gemm
20.	Greater (#758)
21.	Hardmax (#758)
22.	Identity (#758)
23.   If (#753)
23.	IsNaN (#758)
24.	Less (#758)
26.	LogSoftmaxi
27.   Loop (#753) 
28.	MatMul (#753)
29.	Mean
30.	MeanVarianceNormalization
31.	Mod (#775)
34.	NonZero
35.	Pad
37.	QuantizeLinear
38.	Reciprocal
39.	ReduceL1
40.	ReduceL2
41.	ReduceLogSum
42.	ReduceLogSumExp
43.	ReduceMax (PR #777) 
44.	ReduceMean (PR #777)
45.	ReduceMin (PR #777)
46.	ReduceProd (PR #777)
47.	ReduceSum
48.	ReduceSumSquare
49.	Relu
50.	Reshape
52.	Scatter
53.	ScatterElements
54.	ScatterND
55.	Shape
56.	Sigmoid
58.	Size
60.	Softmax
61.	SoftmaxCrossEntropyLoss
62.	SpaceToDepth
64.	Squeeze
65.	Sub (#753)
66.	Sum 
68.	Tile
69.	Transpose
70.	Unsqueeze

**Comment by shahirdaya** [comment]
@winnietsang I have submitted PR #757 for Add, Ceil, Erf, Exp, and Floor operators. Thanks

**Comment by winnietsang** [comment]
> @winnietsang I have submitted PR #757 for Add, Ceil, Erf, Exp, and Floor operators. Thanks

Thanks @shahirdaya I updated the list above with your status.

**Comment by shahirdaya** [comment]
@winnietsang I have submitted PR #758 for the Greater, Hardmax, Identity, IsNaN, and Less operators. Thanks

**Comment by shahirdaya** [comment]
@winnietsang PR #761 takes care of Log, LRN, Mul, and Neg.

**Comment by shahirdaya** [comment]
Hi @winnietsang  PR #772 for Sign, Sqrt, and Tanh. Thanks

**Comment by shahirdaya** [comment]
@winnietsang PR #777 for ReduceMax, ReduceMean, ReduceMin, and ReduceProd. Thanks

**Comment by chinhuang007** [comment]
Here are the remaining ops for opset 13

1. Abs
2. DepthToSpace
3. DequantizeLinear
4. Div
5. Expand
6. Flatten
7. Gather
8. Gemm
9. LogSoftmax
10. Mean
11. MeanVarianceNormalization
12. NonZero
13. Pad
14. QuantizeLinear
15. Reciprocal
16. ReduceL1
17. ReduceL2
18. ReduceLogSum
19. ReduceLogSumExp
20. ReduceSum
21. ReduceSumSquare
22. Reshape
23. ScatterND
24. Shape
25. Sigmoid
26. Size
27. Softmax
28. SoftmaxCrossEntropyLoss
29. SpaceToDepth
30. Squeeze
31. Sum
32. Tile
33. Transpose
34. Unsqueeze

**Comment by chinhuang007** [comment]
One more update, the remaining ops for opset 13.

1. DequantizeLinear (https://github.com/onnx/onnx-tensorflow/pull/857)
2. MeanVarianceNormalization (https://github.com/onnx/onnx-tensorflow/pull/854)
3. NonZero (https://github.com/onnx/onnx-tensorflow/pull/854)
4. Pad
5. QuantizeLinear (https://github.com/onnx/onnx-tensorflow/pull/857)
6. Reciprocal (https://github.com/onnx/onnx-tensorflow/pull/854)
7. ReduceL1 (https://github.com/onnx/onnx-tensorflow/pull/854)
8. ReduceL2 (https://github.com/onnx/onnx-tensorflow/pull/854)
9. ReduceLogSum
10. ReduceLogSumExp
11. ReduceSum
12. ReduceSumSquare
13. Reshape
14. Squeeze (can't support axes as input)
15. Unsqueeze (can't support axes as input)

Currently not supported ops
MaxRoiPool (1)
Multinomial (7)
NegativeLogLikelihoodLoss (12)
SoftmaxCrossEntropyLoss (12)
StringNormalizer (10)
Unique (11)

**Comment by chinhuang007** [comment]
All ops are supported except Squeeze and Unsqueeze with known technical blockers.

**Comment by jinluyang** [comment]
Excuse me, when will Multinomial be supported? It seems to fail here: http://onnx.ai/backend-scoreboard/onnx-tf_details_stable.html and I need to convert a model from pytorch to onnx to tensorflow, which has a torch.multinomial to do sampling.

> One more update, the remaining ops for opset 13.
> 
> 1. Pad (#861)
> 2. ReduceLogSum (#863)
> 3. ReduceLogSumExp (#863)
> 4. ReduceSum (#863)
> 5. ReduceSumSquare (#863)
> 6. Reshape (#863)
> 7. Squeeze (can't support axes as input)
> 8. Unsqueeze (can't support axes as input)
> 
> Currently not supported ops (opset number)
> 
> 1. MaxRoiPool (1)
> 2. Multinomial (7)
> 3. NegativeLogLikelihoodLoss (12)
> 4. SoftmaxCrossEntropyLoss (12)
> 5. StringNormalizer (10)
> 6. Unique (11)

**Comment by chinhuang007** [comment]
Thanks for making the inquiry. A new patch is created, https://github.com/onnx/onnx-tensorflow/pull/920. Feel free to give it a try before it is landed.

**Comment by jinluyang** [comment]
> Thanks for making the inquiry. A new patch is created, #920. Feel free to give it a try before it is landed.

Thank you, but there is a little problem, tf.random.categorical  needs the logits to be a 2-D tensor, while pytorch/onnx can support 1-D or 2-D tensor. So when I convert pytorch (which I use) to onnx to tensorflow, it says: 
ValueError: Shape must be rank 2 but is rank 1 for 'onnx_tf_prefix_Multinomial_1250/Multinomial' (op: 'Multinomial') with input shapes: [21128], [].
In the end, I have to add a reshape before the pytorch multinomial. Anyway, thank you very much!

**Comment by chinhuang007** [comment]
I don't think ONNX supports 1-d input according to the spec "Input tensor with shape [batch_size, class_size], where class_size is the number of all possible outcomes.", https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-66.

**Comment by jinluyang** [comment]
> I don't think ONNX supports 1-d input according to the spec "Input tensor with shape [batch_size, class_size], where class_size is the number of all possible outcomes.", https://github.com/onnx/onnx/blob/master/docs/Operators.md#inputs-66.

OK, so the problem was in onnx, it converted 1-D pytorch Multinomial to ONNX without giving errors or warnings.
No other problems, thx.
