### ISSUE TITLE
ValueError: Node 'Sigmoid_218': Unknown input node 'Transpose_217'

### ISSUE THREAD

**Issue by BernardinD** [onnx/onnx-tensorflow#729]
**Describe the bug**

I'm converting Yolov5 from Pytorch to Tensorflow. I am able to use onnx-tf to get a .pb graph but when I try to import it i get an `ValueError: Node 'Sigmoid_218': Unknown input node 'Transpose_217'` error.

**To Reproduce**

Please give us instructions to reproduce your problem.

```
graph = tf.GraphDef.FromString(open("/content/new_pt/yolov5s.pb", 'rb').read())
input_tensor, output_tensor1 = tf.import_graph_def(graph, return_elements=['images:0',
                                                                            'output:0'])
```

**ONNX model file**

[https://drive.google.com/file/d/16iuQ-dl6zttmLdHcXSQdlxm3OLpKT0WJ/view?usp=sharing](url)

**PB model file**

[https://drive.google.com/file/d/1EKYNRLXGH8oT6Av4P326pjVKUh_813m2/view?usp=sharing](url)

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6
 - ONNX version: 1.6
 - ONNX-TF version: 1.6
 - Tensorflow version: 2.3

**Additional context**

**Comment by 15800436469try** [comment]
I  meet the same problem,Did you solved it?

**Comment by chinhuang007** [comment]
@BernardinD Please provide access to your files for debugging. Thanks.

**Comment by 15800436469try** [comment]
> @BernardinD Please provide access to your files for debugging. Thanks.

I have solved this problem by this method:
```
 with tf.Graph().as_default():
    #graph_def = tf.GraphDef()
    
    with open(tf_pb_path, "rb") as f:
        graph_def=tf.GraphDef.FromString(f.read())
        tf.import_graph_def(tf_rep.graph.as_graph_def(), name="")
 
    with tf.Session() as sess:
        init = tf.global_variables_initializer()
        init = tf.initialize_all_variables()
        sess.run(init)
        constant_graph = graph_util.convert_variables_to_constants(sess, sess.graph_def, ['Concat_1063'])
        input_x = sess.graph.get_tensor_by_name("0:0") # input
        outputs1 = sess.graph.get_tensor_by_name('Concat_1063:0') # 5
        output_tf_pb = sess.run([outputs1], feed_dict={input_x:img})
        with tf.gfile.FastGFile('./yolo5s.pb', mode='wb') as f:
            f.write(constant_graph.SerializeToString())
```
I used tensorflow's method to store the pb file and I use tf_rep.graph as graph instead of using tf_rep.export_graph("./yolo5s.pb")
environment:
    Python version: 3.6.9
    ONNX version: 1.7
    ONNX-TF version: latest
    Tensorflow version: 1.15

**Comment by chinhuang007** [comment]
Good know know the issue is resolved.

**Comment by BernardinD** [comment]
@15800436469try Where are you making these changes??
