### ISSUE TITLE
setup.sh never run?

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#73]
Is there any command for running setup.sh?
Maybe it's the reason always makes test fail at python2.7.

Example job:
https://travis-ci.org/onnx/onnx-tensorflow/jobs/354137884

Log:
```
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
./.travis/build.sh: line 12: 10259 Aborted                 (core dumped) python -m unittest discover test/backend/
```

**Comment by tjingrant** [comment]
I think it's just the case of vgg-19 not being able to get enough memory.. It happened before to the onnx-caffe project and they disabled it from running on CI infrastructure.

**Comment by fumihwh** [comment]
@tjingrant 
So maybe issue should be test failed when using python2.7.
Do you know anything about that error?

**Comment by tjingrant** [comment]
I don't think it happens very often. Also it fixes itself usually after a re-run.

**Comment by fumihwh** [comment]
OK~
