### ISSUE TITLE
support opset

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#75]
ONNX is using `opset` to version ops, which is not supported in onnx-tensorflow.
Unless support opset here, we will loss a lot of compatibilities.
One idea is separate handlers to another files - make one file per op.
In file, we have both frontend, backend versioned handlers.
For example,
```
class AddHandler(...):
   
   opsets = [1, 3]
  
   def __init__(self, opset, ...):
      all_opsets = order(opsets + [opset])
      opset = all_opsets[len(all_opsets) - 1 - all_opsets[::-1].index(opset) - 1]

   def get_backend_handler():
      return getattr(cls, 'backend_' + opset)

   def get_frontend_handler():
      return getattr(cls, 'frontend_' + opset)

   def backend_1():
      .....
   
   def backend_3():
      ....

   def frontend_1():
      .....
   
   def frontend_3():
      ....
```

How about this?

**Comment by tjingrant** [comment]
I suspect this will create way too many files and it could be very difficult to manage in the end. I think we should probably do one version per file (and only implement the handlers that have changed since the last version) and by default automatically pick the latest version of the implementation. 

What do you think?

**Comment by fumihwh** [comment]
You mean `backend_2.py`, `backend_3.py` <-- sth like this?

**Comment by tjingrant** [comment]
Yes and we only write ops that have updated definitions in newer versions. So backend_2.py, backend_3.py should be fairly small in size. Also we can pull their shared code to backend_common.py.

**Comment by fumihwh** [comment]
If use this way, it's a bit harder to find appropriate handler.
For example, graph `opset=4` and newest `AddHandler` is `opset=1`.
We should loop `backend_*.py` to check if `AddHanlder` exists.
Should we add a version management file (dict) to manage ops version?
```
AddHandler: [1, 2]
```

**Comment by tjingrant** [comment]
Indeed I think that might be a good idea. 
I think we can possibly generate this file automatically.

**Comment by fumihwh** [comment]
`this file` means indexing file of ops, right?
If yes, sounds good.

**Comment by tjingrant** [comment]
Yes.

**Comment by fumihwh** [comment]
If you have time, otherwise I can try.

**Comment by tjingrant** [comment]
Yes, let's divide the work for this one. So you can assume that you already have a dictionary like 
`
opset = {'add': [1, 2], 'subtract': [2, 3]}
`
where the list of numbers indicate the available versions in our implementation (assuming we are consistent between frontend and backend).
