### ISSUE TITLE
Dynamic input shape support in ConvTranspose missing

### ISSUE THREAD

**Issue by j-paulus** [onnx/onnx-tensorflow#750]
**Describe the bug**

When importing an ONNX model with dynamic input shape (not only batch dimension), ConvTranspose cannot determine the output size and crashes.

This is a relevant issue in, e.g., audio processing. Batch size is dynamic, length of input audio is dynamic. Conv1d is used to implement STFT-like transform with a dynamic output size, and later ConvTranspose1d is used to invert the transform. 

The fix is probably similar to #687 

**To Reproduce**

The code below demonstrates how to generate the ONNX model triggering the bug. Removing the `dyn_axis` definitions in the export command forces the inputs to have static sizes and all works.

The resulting ONNX file that triggers the issue is provided below.

```

import torch
import onnx
from onnx_tf.backend import prepare

class MyModel(torch.nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        # (n_bins*2, 1, frame_len)
        self.kernel = torch.nn.Parameter(torch.randn(5, 1, 8), requires_grad=False)
        self.stride = 4

    def forward(self, x):
        # x.shape (n_batch, n_samples)
        y = torch.nn.functional.conv1d(x[:, None, :],
                                       weight=self.kernel,
                                       bias=None,
                                       stride=self.stride,
                                       padding=0)
        # => (n_batch, 5, n_frames)
        y = torch.nn.functional.conv_transpose1d(y,
                                                 weight=self.kernel,
                                                 bias=None,
                                                 stride=self.stride,
                                                 padding=0)
        # => (n_batch, n_samples)
        return y

model = MyModel()
model.eval()
x_in = torch.randn((3, 50))
x_out = model(x_in)
traced_model = torch.jit.trace(model, x_in)

# ONNX export
onnx_name = 'model.onnx'

dyn_axes_in = {0: 'batch_sz', 1: 'n_samples'}
dyn_axes_out = {0: 'batch_sz', 1: 'n_samples'}

torch.onnx.export(model, x_in, onnx_name,
                  verbose=True,
                  example_outputs=x_out,
                  input_names=['x_in'],
                  output_names=['x_out'],
                  dynamic_axes={'x_in': dyn_axes_in,
                                'x_out': dyn_axes_out},
                  opset_version=11,  
                  enable_onnx_checker=True)

onnx_model = onnx.load(onnx_name)
tf_model = prepare(onnx_model)
```

The result should be:

> 
>   tf_model = prepare(onnx_model)
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/backend.py", line 70, in prepare
>     return cls.onnx_model_to_tensorflow_rep(model, strict)
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/backend.py", line 90, in onnx_model_to_tensorflow_rep
>     return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/backend.py", line 147, in _onnx_graph_to_tensorflow_rep
>     output_ops = cls._onnx_node_to_tensorflow_op(onnx_node,
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/backend.py", line 257, in _onnx_node_to_tensorflow_op
>     return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/handlers/handler.py", line 59, in handle
>     return ver_handle(node, **kwargs)
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/handlers/backend/conv_transpose.py", line 21, in version_11
>     return cls.conv(node, kwargs["tensor_dict"], transpose=True)
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/handlers/backend/conv_mixin.py", line 119, in conv
>     conv_output_shape += [
>   File "/Users/name/code/python/onnx-tensorflow/onnx_tf/handlers/backend/conv_mixin.py", line 120, in <listcomp>
>     strides[i] * x_spatial_shape[i] - strides[i] +
> TypeError: unsupported operand type(s) for *: 'int' and 'NoneType'

**ONNX model file**

[triggering model](https://gist.github.com/j-paulus/c507e436b7154f87b120979ae3c6b0c4)

**Python, ONNX, ONNX-TF, Tensorflow version**

 - Python version: 3.8.5
 - ONNX version:  1.7.0
 - ONNX-TF version: 1.6.0
 - Tensorflow version: 2.3.0

**Additional context**

Update: added the traceback after crash.

**Comment by cenkbircanoglu** [comment]
+1

**Comment by amandazw** [comment]
what if I want to use onnx-tf==1.2.1 (as i want to use tensorflow==1.9.0 to load model )and  there is Dynamic input shape problem? how to change the file?i found that  onnx_tf/common/tf_helper.py were not exist in onnx-tf==1.2.1.
thx!
