### ISSUE TITLE
Maybe a bug in __init__.py

### ISSUE THREAD

**Issue by Eric-Thu** [onnx/onnx-tensorflow#751]
In \_\_init\_\_.py, line 2:
`from .version import version as __version__`

In the current version, onnx_tf does not has a modula named `version'. 

Just delete it.

**Comment by winnietsang** [comment]
@Eric-Song-Love-Coding  onnx_tf/version.py is an auto generated file, it will not be save in the repo. When user run setup.py it will be generated.

**Comment by chinhuang007** [comment]
Not a bug therefore close.
