### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'as_graph_def'

### ISSUE THREAD

**Issue by acidtonic** [onnx/onnx-tensorflow#763]
File "onnx2tf.py", line 13, in <module>
    file.write(output.graph.as_graph_def().SerializeToString())

AttributeError: 'NoneType' object has no attribute 'as_graph_def'

Whenever you would get around to supporting a recent tensorflow, let us know.

**Comment by pluradj** [comment]
ONNX-TensorFlow 1.6.0 supports TensorFlow 2. It's not currently available on PyPi, but you can install it with:

```
pip install git+https://github.com/onnx/onnx-tensorflow.git@rel-1.6.0
```

**Comment by chinhuang007** [comment]
The most recent ONNX-Tensorflow, 1.7.0, https://pypi.org/project/onnx-tf/, supports Tensorflow 2.4. Feel free to reopen if this is still an issue.
