### ISSUE TITLE
None values not supported when converting onnx to tensorflow

### ISSUE THREAD

**Issue by padmasreenagarajan** [onnx/onnx-tensorflow#764]
Im trying to convert Mobilenetv3 onnx model to tensorflow.
I need tensorflow==1.12.0 for my inferencing.
I searched all over to find the onnx and onnx-tf versions corresponding to tensorflow==1.12.0

Could anyone please suggest me the compatible versions of onnx,onnx-tf and torch for my required tensorflow version?

**Comment by pluradj** [comment]
Did you test converting your model with onnx 1.3.0 and onnx-tensorflow 1.3.0 as I mentioned previously? If it failed, could you provide more details on what error you were seeing?

**Comment by padmasreenagarajan** [comment]
@pluradj 
Initially i faced 2 errors-
1)**AttributeError: module 'tensorflow._api.v1.math' has no attribute 'is_inf'**
which is solved by modifying the code in onnx_tf/handlers/backend/is_inf.py

2)**onnx.onnx_cpp2py_export.checker.ValidationError: base_net.0.bias in initializer but not in graph input**
which is solved by exporting to onnx with Keep_initializers_as _inputs==True

And finally,i am unable to solve this error
**onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.**

I used
Torch==1.3.0+cpu;Torchvision==0.4.0+cpu
onnx==1.3.0
onnx-tf==1.3.0
tensorflow==1.12.0

Do guide me in solving this!@pluradj

**Comment by pluradj** [comment]
What is the `ir_version` of your model? You'll need to make sure you're targeting a compatible version of ONNX.

**Comment by pluradj** [comment]
For reference:

ONNX version | IR version
-------------- | -----------
v1.0 - v1.3.0   | 3
v1.4.0 | 4
v1.5.0 | 5
v1.6.0 | 6
v1.7.0 | 7

**Comment by padmasreenagarajan** [comment]
my model's ir version is 3 
@pluradj

**Comment by pluradj** [comment]
Hmm. ONNX 1.3.0 supports IR version 3, so you shouldn't be getting the error "Your model ir_version is higher than the checker's." Could you please share your model?

**Comment by padmasreenagarajan** [comment]
Hi..Im facing this error when converting Mobilenetv3 onnx file to tensorflow

File "Python36\site-packages\tensorflow_core\python\framework\tensor_util.py", line 437, in make_tensor_proto
raise ValueError("None values not supported.")

ValueError: None values not supported.
Do guide me in solving this..
@pluradj 
Im using
torch==1.3.0+cpu
onnx==1.5.0
onnx-tf==1.5.0
tensorflow==1.15.0
opset==10

**Comment by pluradj** [comment]
Could you please share your ONNX model?

**Comment by padmasreenagarajan** [comment]
Sorry @pluradj 
As it is confidential, I am unable to share it here

**Comment by pluradj** [comment]
could you at least share a more complete stack trace?

**Comment by padmasreenagarajan** [comment]
This is the entire error and warning messages.
As I am very very new to onnx and tensorflow, I did not have much idea about this.
Could u please guide me in resolving this? @pluradj 


C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\common\handler_helper.py:37: UserWarning: Unknown op ConstantFill in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\common\handler_helper.py:37: UserWarning: Unknown op GatherND in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\common\handler_helper.py:37: UserWarning: Unknown op ImageScaler in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\common\handler_helper.py:37: UserWarning: Unknown op Range in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\common\handler_helper.py:37: UserWarning: Unknown op Round in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\common\handler_helper.py:37: UserWarning: Unknown op ScatterElements in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\common\handler_helper.py:37: UserWarning: Unknown op ScatterND in domain `ai.onnx`.
  handler.ONNX_OP, handler.DOMAIN or "ai.onnx"))
WARNING:tensorflow:From C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py:123: The name tf.placeholder is deprecated. Please use tf.compat.v1.placeholder instead.

2020-09-23 11:39:39.543468: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2020-09-23 11:39:39.616856: W tensorflow/stream_executor/platform/default/dso_loader.cc:55] Could not load dynamic library 'nvcuda.dll'; dlerror: nvcuda.dll not found
2020-09-23 11:39:39.617362: E tensorflow/stream_executor/cuda/cuda_driver.cc:318] failed call to cuInit: UNKNOWN ERROR (303)
2020-09-23 11:39:39.650977: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:169] retrieving CUDA diagnostic information for host: 6011052LD01
2020-09-23 11:39:39.651319: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:176] hostname: 6011052LD01
WARNING:tensorflow:From C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\backend_handler.py:182: div (from tensorflow.python.ops.math_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Deprecated in favor of operator or tf.math.divide.
WARNING:tensorflow:From C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\backend\reshape.py:26: where (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where
WARNING:tensorflow:From C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\backend\reshape.py:31: sparse_to_dense (from tensorflow.python.ops.sparse_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Create a `tf.sparse.SparseTensor` and use `tf.sparse.to_dense` instead.
WARNING:tensorflow:From C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\backend\gemm.py:14: flatten (from tensorflow.python.layers.core) is deprecated and will be removed in a future version.
Instructions for updating:
Use keras.layers.flatten instead.
WARNING:tensorflow:From C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\layers\core.py:332: Layer.apply (from tensorflow.python.keras.engine.base_layer) is deprecated and will be removed in a future version.
Instructions for updating:
Please use `layer.__call__` method instead.
Traceback (most recent call last):
  File "C:/Users/PycharmProjects/mbv3/Scripts/convert_to_onnx.py", line 252, in <module>
    tf_rep = prepare(onnx_model)  # prepare tf representation
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 65, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 85, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 143, in _onnx_graph_to_tensorflow_rep
    onnx_node, tensor_dict, handlers, opset=opset, strict=strict)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\backend.py", line 238, in _onnx_node_to_tensorflow_op
    return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\handler.py", line 61, in handle
    return ver_handle(node, **kwargs)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\onnx_tf\handlers\backend\slice.py", line 56, in version_10
    input_tensor_shape = tf.constant(input_tensor.shape.dims, ends.dtype)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 161, in constant_v1
    allow_broadcast=False)
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "C:\Users\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow_core\python\framework\tensor_util.py", line 437, in make_tensor_proto
    raise ValueError("None values not supported.")

**ValueError: None values not supported.**

**Comment by pluradj** [comment]
The last error looks like a problem with the Slice operator and dynamic size support. A fix for that was merged into `tf-1.x` branch with PR #566. Try upgrading your packages to ONNX 1.6.0 and ONNX-TF 1.6.0 to pick up this fix. The git tag for that release is `v1.6.0-tf-1.15`. ONNX-TF 1.6.0 isn't available on PyPI currently, but you can install it like this:

```
pip install git+https://github.com/onnx/onnx-tensorflow.git@v1.6.0-tf-1.15
```

**Comment by padmasreenagarajan** [comment]
Hi @pluradj ,
I have already tried the versions u mentioned onnx==onnx-tf==1.6.0 with tf=1.15.
However I face the following error for opset 11
**RuntimeError: ONNX export failed on hardtanh, which is not implemented for opset 11. Try exporting with other opset versions**
and the following for opset 9
**onnx.onnx_cpp2py_export.checker.ValidationError: Unrecognized attribute: max for operator Clip

==> Context: Bad node spec: input: "482" output: "483" op_type: "Clip" attribute { name: "max" f: 6 type: FLOAT } attribute { name: "min" f: 0 type: FLOAT }**

Let me know if u need the complete stack trace.
Thank you!

**Comment by pluradj** [comment]
`onnx-tf` has 2 development branches: `tf-1.x` should used for TF 1.15.0 and `master` would be for TF 2.x. Please keep your package versions aligned based on the recommendations `v1.6.0`. The `ir_version` of your model should be `6` aligned with the package versions.

- RuntimeError: `hardtanh` isn't an operator in ONNX. Also I can't find any of error text in either `onnx` or `onnx-tensorflow`. Where is this coming from? If it's coming from PyTorch, you should ask on that project.
- ValidationError: `max` was an attribute on `Clip` for opset 1-6, but it is an input since [opset 11](https://github.com/onnx/onnx/blob/master/docs/Changelog.md#Clip-11). You probably need to update your model accordingly.

It's usually a good idea to provide as much detail as you can, so yes, please edit your latest comment and add them.

**Comment by padmasreenagarajan** [comment]
Sorry.. I have updated the changes in the previous comment.
its not from master branch..its from tf-1.x branch only..
.Please do find them @pluradj

**Comment by pluradj** [comment]
Are the full stack traces available for the RuntimeError for hardtanh and Validation on max for Clip? These are the details I was asking about.

**Comment by padmasreenagarajan** [comment]
All the error got resolved when i upgraded torch from 1.3 to 1.5 and tensorflow got generated successfully.
The versions matrix is as follows
onnx==1.6.0
onnx-tf==1.6.0 (from tf-1.5x branch)
tensorflow==1.15.0
torch==1.5.0
torchvision==0.6.0
opset==11

Thanks for your support @pluradj

**Comment by pluradj** [comment]
It sounds like your issues are fully resolved? If so, congrats and please go ahead and close this issue. Thanks.

**Comment by padmasreenagarajan** [comment]
Yeah..The issue is resolved and hereby I'm closing the issue.
Thanks for your support @pluradj
