### ISSUE TITLE
None values not supported when converting onnx to tensorflow

### ISSUE THREAD

**Issue by padmasreenagarajan** [onnx/onnx-tensorflow#768]
Hi..Im facing this error when converting Mobilenetv3 onnx file to tensorflow

**File "Python36\site-packages\tensorflow_core\python\framework\tensor_util.py", line 437, in make_tensor_proto
raise ValueError("None values not supported.")**

**ValueError: None values not supported.**
Do guide me in solving this..

Im using
torch==1.3.0+cpu
onnx==1.5.0
onnx-tf==1.5.0
tensorflow==1.15.0
opset==10

**Comment by pluradj** [comment]
Is this the same model you opened #764 about? If so, it'd be better to close this and continue the conversation on the previous issue. You can edit the title and any of your previous comments on #764 if necessary. Thanks.

**Comment by padmasreenagarajan** [comment]
This issue is moved under #764 .
Thank u
