### ISSUE TITLE
ValueError: Cannot convert a partially known TensorShape to a Tensor

### ISSUE THREAD

**Issue by bmachin** [onnx/onnx-tensorflow#784]
I'm getting `ValueError: Cannot convert a partially known TensorShape to a Tensor: (None, 1, None, None)` while attempting to convert an onnx model file (previously migrated from pytorch) to a tensorflow model. 

**To Reproduce**

```python
import onnx
from onnx_tf.backend import prepare

onnx_model = onnx.load('model.onnx')
tf_rep = prepare(onnx_model)
tf_rep.export_graph('model.pb')
```

**ONNX model file**

https://drive.google.com/file/d/1wkxWgesupss4n5aHzMcKOxJoRkQpCudk/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**

Python version: 3.7.8 (default, Sep 30 2020, 14:10:18) [GCC 7.5.0]
ONNX version: 1.7.0
ONNX-TF version: 1.6.0
Tensorflow version: 2.2.0

Thank you.

**Comment by winnietsang** [comment]
@bmachin PR #795 should address the issue you report above. May you please give it a try and let us know does it work for you. Thanks

**Comment by Patrickctyyx** [comment]
Same problem.

Python 3.8.5 (default, Sep  4 2020, 07:30:14)[GCC 7.3.0]
ONNX version: 1.8.0
ONNX-TF version: 1.7.0
Tensorflow version: 2.3.0

**Comment by EmreOzkose** [comment]
Same problem.

Python 3.10.0
ONNX version: 1.14.0
ONNX-TF version: 1.10.0
Tensorflow version: 2.10.0

**Comment by leeqiaogithub** [comment]
Same problem.

Python 3.8.3
ONNX version: 1.12.0
ONNX-TF version: 1.8.0
Tensorflow version: 2.3.4
