### ISSUE TITLE
pytorch->onnx->tensorflow pb, Conv2DCustomBackpropInputOp only supports NHWC occurs with tensorflow_model_server.

### ISSUE THREAD

**Issue by opconty** [onnx/onnx-tensorflow#792]
**Describe the bug**
Exporting the pytorch model with` torch.onnx.export` into onnx, then using onnx_tf convert the onnx model to tensorflow pb.

 it works fine with script, but failed when depolying with tensorflow_model_server, output error
_Conv2DCustomBackpropInputOp only supports NHWC.
	 [[{{node conv2d_transpose}}]]_

**Python, ONNX, ONNX-TF, Tensorflow version**
 - Python version: 3.7.0
 - ONNX version: 1.6.0
 - ONNX-TF version:1.6.0
 - Tensorflow version: 2.2.0

**Comment by winnietsang** [comment]
@opconty may you please provide the ONNX file that is generated from PyTorch and what input data it required to run your model? if you can provide a sample input data will be very appreciate.

**Comment by opconty** [comment]
I've solved this problem ,perhaps it's a bug from tensorflow_model_server, thanks for your reply
