### ISSUE TITLE
ValueError: None values not supported

### ISSUE THREAD

**Issue by Zhongyuan-Li** [onnx/onnx-tensorflow#804]
Hi, Im trying to convert superglue(GNN) model from pytorch to tensorflow though onnx. I'v succeeded got the onnx model and tested it with onnxruntime for making sure the onnx model is right. Cause the model has some complex ops which onnx only support in opset12. So all the libs I chosen are the recent release. 
    The versions of the libs:    python=3.6  onnxruntime-gpu=1.5.2 tensorflow=2.3 pytorch=1.7.  onnx-tensorrt is on master branch
    when I use onnx_to_tf.py to convert the model to tensor. It reports the error in title. 
    It looks similar to the issue #764 but according to the trace back they may not the same problem,
    Could anyone give me some suggestions?
Here is the trace back:

Traceback (most recent call last):
  File "onnx_to_tf.py", line 8, in <module>
    tf_rep.export_graph("/home/algo/Projects/super-glue-pretrained-network_libtorch/models/weights/superglue_onnx.pb")  # export the model
  File "../onnx_tf/backend_rep.py", line 116, in export_graph
    **self.signatures))
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1167, in get_concrete_function
    concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 1073, in _get_concrete_function_garbage_collected
    self._initialize(args, kwargs, add_initializers_to=initializers)
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 697, in _initialize
    *args, **kwds))
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 2855, in _get_concrete_function_internal_garbage_collected
    graph_function, _, _ = self._maybe_define_function(args, kwargs)
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3213, in _maybe_define_function
    graph_function = self._create_graph_function(args, kwargs)
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3075, in _create_graph_function
    capture_by_value=self._capture_by_value),
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 986, in func_graph_from_py_func
    func_outputs = python_func(*func_args, **func_kwargs)
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/def_function.py", line 600, in wrapped_fn
    return weak_wrapped_fn().__wrapped__(*args, **kwds)
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/eager/function.py", line 3735, in bound_method_wrapper
    return wrapped_fn(*args, **kwargs)
  File "/home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/func_graph.py", line 973, in wrapper
    raise e.ag_error_metadata.to_exception(e)
ValueError: in user code:

    ../onnx_tf/backend_tf_module.py:105 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    ../onnx_tf/backend.py:289 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    ../onnx_tf/handlers/handler.py:59 handle  *
        return ver_handle(node, **kwargs)
    ../onnx_tf/handlers/backend/gather_elements.py:45 version_11  *
        idx_tensors_per_axis = tf.meshgrid(*list(
    /home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/util/dispatch.py:201 wrapper  **
        return target(*args, **kwargs)
    /home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/math_ops.py:1791 range
        limit = ops.convert_to_tensor(limit, dtype=dtype, name="limit")
    /home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py:1499 convert_to_tensor
        ret = conversion_func(value, dtype=dtype, name=name, as_ref=as_ref)
    /home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py:338 _constant_tensor_conversion_function
        return constant(v, dtype=dtype, name=name)
    /home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py:264 constant
        allow_broadcast=True)
    /home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/constant_op.py:282 _constant_impl
        allow_broadcast=allow_broadcast))
    /home/algo/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/tensor_util.py:444 make_tensor_proto
        raise ValueError("None values not supported.")

    ValueError: None values not supported.

**Comment by Albert337** [comment]
i get the same error,have you solved it so far?

**Comment by Zhongyuan-Li** [comment]
@Albert337 Not yet. Do you have any suggestion?

**Comment by winnietsang** [comment]
@Zhongyuan-Li and @Albert337 PR #814 should fix the problem you describe above. May you please use the latest master code to convert your model again. If you still experience any problem please let us know.

**Comment by Zhongyuan-Li** [comment]
@winnietsang I pulled the master branch and now it can successfully convert the model into a pb model. 
Thanks!
The converted model seems lack some interpretative parameters that it can't work properly with tensorflow, but this may be the model's problem itself or another issue

**Comment by Albert337** [comment]
thanks,i convert the model to a tf-pb model successfully by following guidelines,but when i test the new model,i find the node in graph is confused,which cannont be used by "get_tensorf_by_name",and the error message is "the node is not in the graph",while i can find the node through netron.

**Comment by winnietsang** [comment]
@Albert337 May you please open a new issue for your problem, we can track your problem better that way. Please provide us your onnx file, instruction on how to run your model, a sample input data for your model and your environment. Thanks.
