### ISSUE TITLE
cannot import name 'sys_config' from 'onnx_tf.common' 

### ISSUE THREAD

**Issue by sai-sai-sai** [onnx/onnx-tensorflow#808]
**Describe the bug**

Getting  this error cannot import name 'sys_config' from 'onnx_tf.common' , while trying to import prepare function

**To Reproduce**
Run : from onnx_tf.backend import prepare

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.7
 - ONNX version: 1.8.0
 - ONNX-TF version: onnx-tf-1.6.0
 - Tensorflow version: 2.3.1

**Additional context**

First I, successfully uninstalled onnx-tf-1.5.0 and then  did pip install git+https://github.com/onnx/onnx-tensorflow.git.

**Comment by chinhuang007** [comment]
I just tried on a fresh system and was unable to reproduce the error. Can you please provide the complete error log? And are you using python script or just interactive python?

**Comment by sai-sai-sai** [comment]
Thanks for your response .  It works after i imported new migrated onnx tf-onnx.

**Comment by andreybond** [comment]
Actually have same issue:

- Python version: 3.7
- ONNX version: 1.8.0
- ONNX-TF version: onnx-tf-1.6.0
- Tensorflow version: 2.3.1

did:
pip uninstall -y onnx-tf
pip install tensorflow-gpu==2.3.1
pip install tensorflow-addons
pip install git+https://github.com/onnx/onnx-tensorflow.git

Error log:
ImportErrorTraceback (most recent call last)
<ipython-input-66-a9720932d661> in <module>
      1 import onnx
----> 2 from onnx_tf.backend import prepare
      3 
      4 onnx_model = onnx.load("/mnt/notebooks/3_Images_sequence__extended_wtih_checkyourskin/model_set4_2lr.onnx")
      5 tf_rep = prepare(onnx_model)

/usr/local/lib/python3.6/dist-packages/onnx_tf/__init__.py in <module>
----> 1 from . import backend
      2 from .version import version as __version__

/usr/local/lib/python3.6/dist-packages/onnx_tf/backend.py in <module>
     25 from onnx_tf.common import get_unique_suffix
     26 from onnx_tf.common import supports_device as common_supports_device
---> 27 from onnx_tf.common.handler_helper import get_all_backend_handlers
     28 from onnx_tf.pb_wrapper import OnnxNode
     29 from onnx_tf.backend_tf_module import BackendTFModule, TFModule

/usr/local/lib/python3.6/dist-packages/onnx_tf/common/handler_helper.py in <module>
      1 from onnx import defs
      2 
----> 3 from onnx_tf.handlers.backend import *  # noqa
      4 from onnx_tf.handlers.backend_handler import BackendHandler
      5 import onnx_tf.common as common

/usr/local/lib/python3.6/dist-packages/onnx_tf/handlers/backend/clip.py in <module>
      2 
      3 from onnx_tf.common import exception
----> 4 from onnx_tf.common import sys_config
      5 from onnx_tf.handlers.backend_handler import BackendHandler
      6 from onnx_tf.handlers.handler import onnx_op

ImportError: cannot import name 'sys_config'

Could you suggest a workaround?

**Comment by Adhithya-tech** [comment]
Same issue mate @sai-sai-sai 
Especially while converting from onnx-tf
