### ISSUE TITLE
ONNX model to Tensorflow:UnliftableError

### ISSUE THREAD

**Issue by neso613** [onnx/onnx-tensorflow#837]
Hi,
I am working on Tacotron2 PyTorch. I have trying to get its encoder part and successfully converted into ONNX format. But when I am trying to convert ONNX model into Tensorflow. It gives error:

UnliftableError: Unable to lift tensor <tf.Tensor 'concat_2:0' shape=(768, 1024) dtype=float32> because it depends transitively on placeholder <tf.Operation 'split_1/279' type=Placeholder> via at least one path, e.g.: concat_2 (ConcatV2) <- transpose_1 (Transpose) <- concat_1 (ConcatV2) <- split_3 (Split) <- Squeeze_1 (Squeeze) <- split_1 (Split) <- split_1/279 (Placeholder)

Please do needful in this regard. [Link](https://github.com/onnx/onnx/issues/3166)

**Comment by chinhuang007** [comment]
Please provide the onnx file for debugging.
