### ISSUE TITLE
code style

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#84]
I know in README, we recommend pylint with tensorflow code style.
But in code, indent with 4 spaces also exist......
We should unify it. A simple way is use [`autopep8`](https://github.com/hhatto/autopep8). Although it is different with tensorflow code style.

**Comment by tjingrant** [comment]
Thats a good idea.

**Comment by fumihwh** [comment]
@tjingrant I'll apply autopep8 to all file after merge your refactor pr.

**Comment by tjingrant** [comment]
Sorry I missed that it's different with tf code style...
I'd actually like to maintain that b/c one day we might be merging the frontend to TF (although unlikely b/c we tried once lol).

**Comment by fumihwh** [comment]
I think we can use autopep8. Just need to change space size to 2.
https://www.tensorflow.org/community/style_guide

**Comment by fumihwh** [comment]
From https://www.tensorflow.org/community/style_guide,
I think we can apply autopep8 with space size 2.

Actually, I tried in my local.
pylint score is improved from 6.15/10 to 8.98/10 with tensorflow/tensorflow/tools/ci_build/pylintrc.

**Comment by fumihwh** [comment]
Use yapf with --style='{based_on_style: chromium, column_limit: 79, indent_width: 2}' got 9.14/10.
