### ISSUE TITLE
How to load converted tf pb file to a python tf 1.15 session?

### ISSUE THREAD

**Issue by matinehshaker** [onnx/onnx-tensorflow#843]
I have converted my onnx file to tensorflow pb file. Now I need to read the tensorflow pb file from the disk and load it to a tensorflow session in python. I am not quite sure how to do that. I have to use tensorflow version 1.15.2. So I'm using tf-1.x branch of onnx-tensorflow repo.

I know there's tf.saved_model.load method in tensorflow, but not sure how to use it or if it's the right way of loading pb file. I don't know what should be tags input.

I see you're suggesting "construct the graphdef in a session and use tensorflow 1 api to make a SavedModel. " Can you please elaborate on that? Are there examples or code snippets on how this could be done?

 - Python version: 3.6.9
 - ONNX version: 1.7.0
 - ONNX-TF version: older version on branch tf-1.x 
 - Tensorflow version:  1.15.2

**Comment by chinhuang007** [comment]
Duplicate issue as https://github.com/onnx/onnx-tensorflow/issues/727
