### ISSUE TITLE
onnx.onnx_cpp2py_export.defs.SchemaError: No schema registered for 'BitShift'!

### ISSUE THREAD

**Issue by malisit** [onnx/onnx-tensorflow#865]
**Describe the bug**
onnx.onnx_cpp2py_export.defs.SchemaError: No schema registered for 'BitShift'!

**To Reproduce**
A Pytorch model was exported to ONNX.

**ONNX model file**
https://www.dropbox.com/s/0y46uvwek94xbdd/m.onnx?dl=0

**Python, ONNX, ONNX-TF, Tensorflow version**
 - Python version: 3.8.5
 - ONNX version: 1.8.1
 - ONNX-TF version:1.7.0
 - Tensorflow version: 2.4.1

**Comment by hitesh-hitu** [comment]
I'm also facing the same issue, while exporting an onnx model to tensorflow. 
Can someone help me with this issue ?

**Comment by WestonLu** [comment]
same issue here

**Comment by chinhuang007** [comment]
The issue is that the most recent ONNX 1.8.1 changed an exception type. So you need to use the latest ONNX-TF from source.
Run git clone and pip install or just `pip install git+https://github.com/onnx/onnx-tensorflow.git` should work too.

**Comment by malisit** [comment]
I uninstalled the onnx-tf and reinstalled it from the master branch. Converts successfully now!

**Comment by sxzhang25** [comment]
I'm having the same bug (with the same use case, PyTorch model exported to ONNX) while using TensorFlow version 1.15.0. I've installed onnx-tensorflow from source according to the instructions on the tf-1.x branch, and have onnx 1.8.1. Is there a fix/work-around for this for older TensorFlow 1.x versions?

```
Traceback (most recent call last):
  ...
    tf_rep = prepare(model_onnx)
  File ".../onnx-tensorflow/onnx_tf/backend.py", line 69, in prepare
    return cls.onnx_model_to_tensorflow_rep(model, strict)
  File ".../onnx-tensorflow/onnx_tf/backend.py", line 89, in onnx_model_to_tensorflow_rep
    return cls._onnx_graph_to_tensorflow_rep(model.graph, opset_import, strict)
  File ".../onnx-tensorflow/onnx_tf/backend.py", line 101, in _onnx_graph_to_tensorflow_rep
    handlers = cls._get_handlers(opset)
  File ".../onnx-tensorflow/onnx_tf/backend.py", line 270, in _get_handlers
    return get_all_backend_handlers(opset_dict)
  File ".../onnx-tensorflow/onnx_tf/common/handler_helper.py", line 30, in get_all_backend_handlers
    max_inclusive_version=version).since_version
onnx.onnx_cpp2py_export.defs.SchemaError: No schema registered for 'BitShift'!
```

**Comment by leondgarse** [comment]
@sxzhang25 I have tested `tf 1.15.0`, and downgrading `onnx` by `pip install onnx=1.8.0` just works for me.

**Comment by devloper13** [comment]
> @sxzhang25 I have tested `tf 1.15.0`, and downgrading `onnx` by `pip install onnx==1.8.0` just works for me.

I get this :
`TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, None]. Consider casting elements to a supported type.`

Any ideas?

**Comment by leondgarse** [comment]
@devloper13 I think it's another issue.
- You may refer to [TypeError: Failed to convert object of type <class 'list'> to Tensor. #688](https://github.com/onnx/onnx-tensorflow/issues/688).
- Also, you may add some print info in the failed layer source code, to see what exactly happening.
- Or maybe other projects like [onnx2keras](https://github.com/nerox8664/onnx2keras).

**Comment by devloper13** [comment]
> @devloper13 I think it's another issue.
> 
> * You may refer to [TypeError: Failed to convert object of type <class 'list'> to Tensor. #688](https://github.com/onnx/onnx-tensorflow/issues/688).
> * Also, you may add some print info in the failed layer source code, to see what exactly happening.
> * Or maybe other projects like [onnx2keras](https://github.com/nerox8664/onnx2keras).

I think  the first link is for tensorflow 2. I'll check the other things.

**Comment by Vozf** [comment]
Maybe it's time to release a new version if the old one isn't compatible with the newest onnx

**Comment by chinhuang007** [comment]
We are working on a new release. Please note that Tensorflow 1.x will no longer be officially supported by onnx-tf 1.8. That means, the tf-1.x branch will stay as-is and the users of Tensorflow 1.x will need to fork and build it to make it compatible with most recent ONNX.

**Comment by CarkusL** [comment]
> > @sxzhang25 I have tested `tf 1.15.0`, and downgrading `onnx` by `pip install onnx==1.8.0` just works for me.
> 
> I get this :
> `TypeError: Failed to convert object of type <class 'list'> to Tensor. Contents: [None, None]. Consider casting elements to a supported type.`
> 
> Any ideas?

pip install onnx==1.8.0 works

**Comment by fclearner** [comment]
is that possible to use onnx1.12.0 setting the opset version to 1.10 to convert onnx model to tf1.x pb model successfully? now I met this problem and it troubles me, I'm trying to not install onnx 1.8.0
