### ISSUE TITLE
'utf-8' codec can't decode byte 0xb7 in position 3: invalid start byte

### ISSUE THREAD

**Issue by aryan461** [onnx/onnx-tensorflow#869]
I converted a PyTorch model to [onnx model](https://drive.google.com/file/d/10T3i_fhOxVfVCbh68nWB852S0WWsCl2U/view?usp=sharing).
Now I want to convert the onnx model to tflite. Here's the code:

```python
  onnx_model = onnx.load(ONNX_PATH) 
  tf_rep = prepare(onnx_model) 
  tf_rep.export_graph(TF_PATH)
  converter = tf.compat.v1.lite.TFLiteConverter.from_frozen_graph(TF_PATH+'/saved_model.pb',  # TensorFlow freezegraph .pb model file
                                                        input_arrays=['input'], # name of input arrays as defined in torch.onnx.export function before.
                                                        output_arrays=['output'] # name of output arrays defined in torch.onnx.export function before.
                                                        )

```

For the last command, I get this error:
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb7 in position 3: invalid start byte`

**Versions:**
tensorflow==2.3.0
tensorflow-addons==0.11.2
onnx-tensorflow is the last version from the git

**Comment by chinhuang007** [comment]
The saved_model.pb in the exported folder is not the frozen graph for the compat.v1 API. Instead, it is for the tf.saved_model API to load the model. Can you try converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model(saved_model_dir)?

**Comment by aryan461** [comment]
> The saved_model.pb in the exported folder is not the frozen graph for the compat.v1 API. Instead, it is for the tf.saved_model API to load the model. Can you try converter = tf.compat.v1.lite.TFLiteConverter.from_saved_model(saved_model_dir)?

thank you for your reply.  It makes worked fine and tflite is produced, but tflite interpreter doesn't run the model and give me the error:
```
RuntimeError: tensorflow/lite/kernels/conv.cc:332 input->dims->data[3] != filter->dims->data[3] (224 != 3)Node number 2 (CONV_2D) failed to prepare.
```

**Comment by aryan461** [comment]
@chinhuang007 Thank you for your reply. It worked fine and tflite is produced, but tflite interpreter doesn't run the model and gives me the error:

```
ValueError: Cannot set tensor: Got value of type NOTYPE but expected type FLOAT32 for input 0, name: serving_default_input 
```

Is that related to converting?
