### ISSUE TITLE
ONNX Conversion of MobileNet V1 Produces Model Not Compatible with Conversion to TFLite

### ISSUE THREAD

**Issue by msquigle** [onnx/onnx-tensorflow#874]
**Describe the bug**
The saved model that is generated from a simple MobileNet produces errors when converting to TFLite. The error from the resultant conversion is as follows

lib\site-packages\tensorflow\lite\python\wrap_toco.py", line 32, in wrapped_toco_convert
    return _pywrap_toco_api.TocoConvert(
Exception: <unknown>:0: error: loc(fused["add_28@__inference___call___31299", "PartitionedCall/add_28"]): 'tf.AddV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["add_28@__inference___call___31299", "PartitionedCall/add_28"]): see current operation: %5159 = "tf.AddV2"(%5158, %cst_20) {device = ""} : (tensor<2xi64>, tensor<2xi64>) -> tensor<2xi64>
<unknown>:0: error: loc(fused["add_29@__inference___call___31299", "PartitionedCall/add_29"]): 'tf.AddV2' op is neither a custom op nor a flex op
<unknown>:0: note: loc(fused["add_29@__inference___call___31299", "PartitionedCall/add_29"]): see current operation: %5171 = "tf.AddV2"(%5165, %5170) {device = ""} : (tensor<2xi64>, tensor<2xi64>) -> tensor<2xi64>
<unknown>:0: error: failed while converting: 'main': Ops that can be supported by the flex runtime (enabled via setting the -emit-select-tf-ops flag):
        tf.AddV2 {device = ""}
<unknown>:0: note: see current operation: "func"() ( {
^bb0(%arg0: tensor<?x224x224x3xf32>):  // no predecessors
  %cst = "std.constant"() {value = dense<[[0, 0], [0, 0], [1, 1], [1, 1]]> : tensor<4x2xi32>} : () -> tensor<4x2xi32>
  %cst_0 = "std.constant"() {value = dense<[[0, 0], [0, 0], [0, 1], [0, 1]]> : tensor<4x2xi32>} : () -> tensor<4x2xi32>
  %cst_1 = "std.constant"() {value = dense<2> : tensor<1xi64>} : () -> tensor<1xi64>
  %cst_2 = "std.constant"() {value = dense<-1> : tensor<i32>} : () -> tensor<i32>
  %cst_3 = "std.constant"() {value = dense<[0, 2, 3, 1]> : tensor<4xi32>} : () -> tensor<4xi32>
  %cst_4 = "std.constant"() {value = dense<[0, 3, 1, 2]> : tensor<4xi32>} : () -> tensor<4xi32>
  %cst_5 = "std.constant"() {value = dense<0> : tensor<i64>} : () -> tensor<i64>
  %cst_6 = "std.constant"() {value = dense<6.000000e+00> : tensor<f32>} : () -> tensor<f32>

The saved model that is generated from the first conversion is as seen below.
![image](https://user-images.githubusercontent.com/35279426/109041978-df5f5d00-768c-11eb-9f32-af6446a5e8c6.png)

**To Reproduce**
import onnx
import tempfile
from onnx_tf.backend import prepare

filename = 'mobilenet_v1_1.0_224_frozen.onnx'
saved_model_name = 'tempdir'
outfile = 'mobilenet_v1_1.0_224_frozen.tflite'

onnx_model = onnx.load(filename)
tf_rep = prepare(onnx_model)
tf_rep.export_graph(saved_model_name)
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_name)
converter.experimental_new_converter = experimental_new_converter
converter.allow_custom_ops = allow_custom_ops
tflite_model = converter.convert()

with open(outfile, 'wb') as f:
    f.write(tflite_model)

Please do not expect us to have PyTorch, Caffe2 installed.

If a model exported from PyTorch and Caffe2 is having trouble in ONNX-TF, use the next section to attach the model.

**ONNX model file**
[mobilenet_v1_1.0_224_frozen.zip](https://github.com/onnx/onnx-tensorflow/files/6037870/mobilenet_v1_1.0_224_frozen.zip)

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.8.2
 - ONNX version: 1.8.0
 - ONNX-TF version: 1.7.0
 - Tensorflow version: 2.3.2

**Additional context**

**Comment by chinhuang007** [comment]
The Tensorflow model is produced properly in the SavedModel format. Please note the pb file in the saved_model folder is NOT just the computational graph; therefore the graph looks normal. 

The error is coming from the TFLite converter. Not knowing some of your variable values such as experimental_new_converter, I just ran the following code with no errors. So I concluded the ONNX to Tensorflow conversion is working as expected.

```
import onnx_tf
import onnx
import tensorflow as tf
import tempfile

onnx_path = 'mobilenet_v1_1.0_224_frozen.onnx'
model_path = 'mobilenet_savedmodel'

model = onnx.load(onnx_path)

# convert and save the model
tf_rep = onnx_tf.backend.prepare(model, logging_level="WARN", auto_cast=True)
#print(tf_rep.onnx_op_list)

tf_rep.export_graph(model_path)

converter = tf.lite.TFLiteConverter.from_saved_model(model_path)
converter.experimental_new_converter = True
converter.allow_custom_ops = True
tflite_model = converter.convert()

_, tflite_file = tempfile.mkstemp('.tflite')

with open(tflite_file, 'wb') as f:
  f.write(tflite_model)
```

**Comment by msquigle** [comment]
Can confirm that it works when adding in auto_cast=True. Seems that without that it was causing issues, thanks for the assistance.
