### ISSUE TITLE
How to get output from an intermediate layer?

### ISSUE THREAD

**Issue by ZeyadYasser** [onnx/onnx-tensorflow#88]
I have been reading the source code for a while now but cannot identify how to get output from intermediate layers given its name. [It is not mentioned in the documentation]
I can only use the run function which make a forward pass through the whole network.
Any suggestions?
Thanks.

**Comment by tjingrant** [comment]
Hi, this sounds like you are missing some output names from your exporter. Which tool did you use to export your model?

**Comment by fumihwh** [comment]
@tjingrant It is really helpful that one can choose which tensor to output when debugging.
Should us pass output names to `run_model` in backend?
Also frontend, pass multiple outputs to `tensorflow_graph_to_onnx_graph`.

**Comment by ZeyadYasser** [comment]
I am using this inception_v1 model from https://github.com/onnx/models as a test.
Let's say I want to use the model for transfer learning so I want the output of an intermediate layer (I have its name eg:'concat_8:0' layer).
I am having difficulty figuring out how to get the output of that layer('concat_8:0'), I can only get the output  of the last layer using the tf_rep.run() method.
I am guessing I should use the run_node method but I cannot find any helpful documentation on using it.
Sorry I know it seems like an obvious thing but I have searched a lot and could not find any thing.

**Comment by tjingrant** [comment]
@fumihwh For debugging, I think there are better and more automatic ways. For instance, you can take a look at the script I wrote when debugging the backend (https://github.com/onnx/onnx-tensorflow/blob/master/example/test_model_large_stepping.py). Basically we can automatically step through each layer and compare with another backend. I can make it more general for debugging. 

I'm a bit concerned about touching run_model because currently we inherit it. Do you see a reason why we would need to output additional intermediate tensor names? Do you think generalizing the `test_model_large_stepping` script could solve your problem of debugging?

**Comment by tjingrant** [comment]
@ZeyadYasser are you looking for a partial execution of the model then? Or just execute the entire model and extract a specific non-standard output name?

**Comment by ZeyadYasser** [comment]
@tjingrant Yes exactly, I am looking for partial execution of the model or getting the actual tensorflow graph object which I can then manipulate.

**Comment by fumihwh** [comment]
@tjingrant `test_model_large_stepping.py` looks quite good~ That is enough I think.

**Comment by tjingrant** [comment]
@ZeyadYasser for a partial execution, I think we should hand you with the tensorflow graph object instead of performing partial execution in our backend. I'll include a tutorial to do that.

**Comment by tjingrant** [comment]
@ZeyadYasser to give you a quick answer, to get the TF model, it is as simple as:

```
    tf_rep = prepare(helper.make_model(graph_def))
    output = tf_rep.run({"X": X})
    print(tf.get_default_graph().as_graph_def())
```

**Comment by ZeyadYasser** [comment]
@tjingrant Thank you very much, This is exactly what I wanted.Cool trick btw, I haven't though of using tensorflow itself to get the default graph.
I am closing the issue.

**Comment by tjingrant** [comment]
Check out the new API doc [here](https://github.com/onnx/onnx-tensorflow/blob/master/onnx_tf/doc/API.md), specifically now we support 
```
tf_rep.export_graph("model.pb") 
```
for your use case. This is a function long overdue and I'm sorry about not writing this up earlier.

**Comment by ZeyadYasser** [comment]
Great, It's much better now that the tf graph object is now officially supported as it allows for many native tf specific manipulation & modifications to the graph.
Thanks a lot for your help.
