### ISSUE TITLE
ValueError: Cannot take the length of shape with unknown rank

### ISSUE THREAD

**Issue by isNeil** [onnx/onnx-tensorflow#882]
Fastai Pytorch model to ONNX to tensorflow running in a colab script.

 `ValueError                                Traceback (most recent call last)
<ipython-input-18-a1a38b85e91b> in <module>()
      5 onnx_model = onnx.load("super_resolution.onnx")  # load onnx model
      6 tf_rep = prepare(onnx_model)  # prepare tf representation
----> 7 tf_rep.export_graph("super_resolution")  # export the model

10 frames
/usr/local/lib/python3.7/dist-packages/onnx_tf/backend_rep.py in export_graph(self, path)
    114         path,
    115         signatures=self.tf_module.__call__.get_concrete_function(
--> 116             **self.signatures))

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in get_concrete_function(self, *args, **kwargs)
   1297       ValueError: if this object has not yet been called on concrete values.
   1298     """
-> 1299     concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
   1300     concrete._garbage_collector.release()  # pylint: disable=protected-access
   1301     return concrete

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _get_concrete_function_garbage_collected(self, *args, **kwargs)
   1203       if self._stateful_fn is None:
   1204         initializers = []
-> 1205         self._initialize(args, kwargs, add_initializers_to=initializers)
   1206         self._initialize_uninitialized_variables(initializers)
   1207 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    724     self._concrete_stateful_fn = (
    725         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
--> 726             *args, **kwds))
    727 
    728     def invalid_creator_scope(*unused_args, **unused_kwds):

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   2967       args, kwargs = None, None
   2968     with self._lock:
-> 2969       graph_function, _ = self._maybe_define_function(args, kwargs)
   2970     return graph_function
   2971 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3359 
   3360           self._function_cache.missed.add(call_context_key)
-> 3361           graph_function = self._create_graph_function(args, kwargs)
   3362           self._function_cache.primary[cache_key] = graph_function
   3363 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3204             arg_names=arg_names,
   3205             override_flat_arg_shapes=override_flat_arg_shapes,
-> 3206             capture_by_value=self._capture_by_value),
   3207         self._function_attributes,
   3208         function_spec=self.function_spec,

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    988         _, original_func = tf_decorator.unwrap(python_func)
    989 
--> 990       func_outputs = python_func(*func_args, **func_kwargs)
    991 
    992       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    632             xla_context.Exit()
    633         else:
--> 634           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    635         return out
    636 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/eager/function.py in bound_method_wrapper(*args, **kwargs)
   3885     # However, the replacer is still responsible for attaching self properly.
   3886     # TODO(mdan): Is it possible to do it here instead?
-> 3887     return wrapped_fn(*args, **kwargs)
   3888   weak_bound_method_wrapper = weakref.ref(bound_method_wrapper)
   3889 

/usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    975           except Exception as e:  # pylint:disable=broad-except
    976             if hasattr(e, "ag_error_metadata"):
--> 977               raise e.ag_error_metadata.to_exception(e)
    978             else:
    979               raise

ValueError: in user code:

    /usr/local/lib/python3.7/dist-packages/onnx_tf/backend_tf_module.py:98 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /usr/local/lib/python3.7/dist-packages/onnx_tf/backend.py:289 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    /usr/local/lib/python3.7/dist-packages/onnx_tf/handlers/handler.py:59 handle  *
        return ver_handle(node, **kwargs)
    /usr/local/lib/python3.7/dist-packages/onnx_tf/handlers/backend/pad.py:87 version_2  *
        return cls._common(node, **kwargs)
    /usr/local/lib/python3.7/dist-packages/onnx_tf/handlers/backend/pad.py:16 _common  *
        num_dim = len(tensor_dict[node.inputs[0]].get_shape())
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/operators/py_builtins.py:252 len_  **
        return _py_len(s)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/autograph/operators/py_builtins.py:317 _py_len
        return len(s)
    /usr/local/lib/python3.7/dist-packages/tensorflow/python/framework/tensor_shape.py:848 __len__
        raise ValueError("Cannot take the length of shape with unknown rank.")

    ValueError: Cannot take the length of shape with unknown rank.`

Link to ONNX file: https://drive.google.com/file/d/1PHn1dZAPGseR2kySkvsCLGmOYAGdn6MA/view?usp=sharing

 - Python version: 3.7.10
 - ONNX version: 1.8.0
 - ONNX-TF version: 1.7.0
 - Tensorflow version: 2.4.1

I believe my model is using adaptive pooling layers, is this something that could cause bad behaviour with the ONNX to TF conversion? In any case what's the best way for me to convert my model?

**Comment by chinhuang007** [comment]
Unfortunately the 'edge' mode for Pad is not supported by Tensorflow and the output rank cannot be inferred with the current custom implementation. So the problem occurs when the next node needs to use the input rank to do its work. If possible, please avoid using 'edge' mode.

**Comment by isNeil** [comment]
Hi, thanks for the quick response. I'll try to use a compatible padding mode. Do you think there will be any other problems with dynamic inputs? I've read tensorflow doesn't fully support dynamic graph/input. In any case I'll try changing the padding first

**Comment by isNeil** [comment]
Replacing the 'edge' padding with 'reflection' padding solved it! Thanks

**Comment by ankitmaurya001** [comment]
Hi,
@isNeil I am also facing a similar issue. Can you share how to check if unet_learner is using 'edge' padding and how you changed it to 'reflection' ?
