### ISSUE TITLE
Typecast to bool missing for "depthwise" flag in onnx_tf/handlers/backend/conv_mixin.py

### ISSUE THREAD

**Issue by vijeth-kum** [onnx/onnx-tensorflow#902]
When `x_shape` is of type np.ndarray, `depthwise` at line 101 is casted implicitly to np.bool and hence the check at line L103 fails.
```
L98    depthwise = (x_rank == 4 and len(weight_shape) == 4 and group != 1 and
L99                 not transpose and not (None in weight_shape))
L100    if depthwise and isinstance(x_shape, np.ndarray):
L101      depthwise = group == x_shape[1]
L102
L103    if depthwise is True:
```
**Expected**: `depthwise` at L101 should be casted to bool
depthwise = bool(group == x_shape[1])

**Comment by chinhuang007** [comment]
Thanks for finding the bug. A fix will be provided shortly.

**Comment by chinhuang007** [comment]
Fixed. Please reopen if not the case. Thanks.
