### ISSUE TITLE
sklearn xgboost save model to onnx, and then transform onnx to pb encount errors

### ISSUE THREAD

**Issue by dulante00** [onnx/onnx-tensorflow#904]
BackendIsNotSupposedToImplementIt: TreeEnsembleClassifier is not implemented.
Is that there are no backend support? 
How can I do it with another way

**Comment by chinhuang007** [comment]
Sorry for the late response. Unfortunately onnx-tf focuses on onnx (dl) operators, and does not support onnx ml operators, defined here, https://github.com/onnx/onnx/blob/master/docs/Operators-ml.md

**Comment by dulante00** [comment]
I get it, thank you very much!

**Comment by Shuwen-Liu** [comment]
Hi, do you know how to transfer a onnx model (converted from xgboost) to pb?
