### ISSUE TITLE
Output shape invalid

### ISSUE THREAD

**Issue by maaft** [onnx/onnx-tensorflow#913]
After converting my onnx model to tensorflow with `onnx-tensorflow`, the output-shape seems to be wrong.

When using the `tensorflowjs_wizard` to convert to tfjs, the wizard shows following shapes:
![image](https://user-images.githubusercontent.com/2518993/117348744-d8ce3c80-aeaa-11eb-8f40-8a812ee8e890.png)

Note how the output shape is given with [-1, 3, -1, -1]. 

What can I do such that the output shape will be the correct one? [1, 3, 512, 512]

**Comment by chinhuang007** [comment]
Can you provide the onnx file for debugging?

**Comment by maaft** [comment]
Hi @chinhuang007 ! Thank you for looking into this.

[Here](https://transfer.sh/fV0Qu/model.onnx) is the model. The link is only valid for 14 days, so tell me if I need to reupload.

**Comment by chinhuang007** [comment]
Thanks for providing the model file. I believe the new patch should fix it. Please give it a try.

**Comment by maaft** [comment]
I'll try it ASAP and report back to you - thanks a lot!

**Comment by akashAD98** [comment]
even I'm also getting the same error. i converted 
darknet -->> .pth -->> .onnx  -- >> .pb  

& I got this output at the time of testing Tensorflow .pb file

**input depth must be evenly divisible by filter depth: 416 vs 3**

Im using
tensorflow==2.3.0rc0
onnx==1.9.0
onnx-tf==1.8.0
This is output of .onxx
![apparal_onnx](https://user-images.githubusercontent.com/62583018/121335641-a19ae300-c8cf-11eb-9d54-e5a263cc5ed3.png)


output of .pb after converting onxx to .pb
![tf-onnx_bug_1](https://user-images.githubusercontent.com/62583018/121335819-c8f1b000-c8cf-11eb-9f9e-bcadce5189cd.png)


please help us to solve this error.Thanks in advance.

**Comment by chinhuang007** [comment]
It seems correct since the batch number is unknown/dynamic in the model and will become a known value during inference. Can you send some inputs to the converted model and see if inference works?

**Comment by maaft** [comment]
By the way, latest master did work for me.

Now I just have to figure out how to run my 300mb stylegan2 ada in a browser.. :laughing:

**Comment by chinhuang007** [comment]
Close since it works with latest master
