### ISSUE TITLE
add example for frontend

### ISSUE THREAD

**Issue by fumihwh** [onnx/onnx-tensorflow#92]
As title, I think we should add example for frontend.
Maybe jupyter is better. So that we can also update https://github.com/onnx/tutorials

**Comment by tjingrant** [comment]
Yes, I was actually working on updating the backend tutorial today. Will roll out an update on backend tutorial soon. I'll take a look at frontend tutorial soon after (if you haven't already done so).

**Comment by tjingrant** [comment]
import tensorflow as tf
from onnx_tf.frontend import convert_graph

graph_pb = '../frozen_resnet_v2_50.pb'

with tf.gfile.GFile(graph_pb, "rb") as f:
    graph_def = tf.GraphDef()
    graph_def.ParseFromString(f.read())
    onnx_model = convert_graph(graph_def, "resnet_v2_50/predictions/Reshape_1")
```

**Comment by fumihwh** [comment]
#93 
I've created a pr to add BN and shape op support.

**Comment by kvanhoey** [comment]
Hi all. Thanks a lot for your effort in implementing ONNX support. I'm really looking forward to it.
I've just tried out the code snippet above (applied to the provided frozen TF graph).
This failed:
`  File "/usr/local/lib/python3.6/dist-packages/onnx_tf/frontend.py", line 152, in tensorflow_graph_to_onnx_graph
    raise NotImplementedError("{} op is not implemented.".format(node.op))
NotImplementedError: Identity op is not implemented.
`

Is this normal or is there something wrong with my installation of your code?

FYI, my spec:
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: Linux Ubuntu 17.10
- **TensorFlow installed from (source or binary)**: binary
- **TensorFlow version (use command below)**: 1.7
- **Python version**: 3.6.3
- **GCC/Compiler version (if compiling from source)**: 6.4.0
- **CUDA/cuDNN version**: 9.0
- **GPU model and memory**: NVidia GeForce GTX 1060 6GB

**Comment by fumihwh** [comment]
@kvanhoey 
I guess you installed by `pip install onnx-tf` . Try clone the repository and install by `pip install -e .` .
The package in PyPi is outdated.

**Comment by kvanhoey** [comment]
Thank you for the hint @fumihwh . In unstilled via `pip` and reinstalled via `pip -e`. That indeed removed this error for my, to the benefit of a few others, unfortunately.
Backend passes `test_model.py` but none of the two other test files. Frontend doesn't pass anything.
And regarding the sample code above, I got the error 

>   File "/home/kvanhoey/tmp/tuto/onnx-tensorflow/onnx_tf/frontend.py", line 57, in __init__
    self.name = node_proto.name
AttributeError: 'str' object has no attribute 'name'

Is there something missing on my end?

Thanks.

Kenneth

**Comment by fumihwh** [comment]
@kvanhoey 
I need more information about problem you're facing.
Our CI shows we have passed all test at least on master branch.
Moreover, check your onnx version (try install onnx by pip install -e . too)

**Comment by tjingrant** [comment]
Closing because it is done.
