### ISSUE TITLE
BackendIsNotSupposedToImplementIt: _DCNv2 is not implemented.

### ISSUE THREAD

**Issue by prabhuiitdhn** [onnx/onnx-tensorflow#944]
Hi: I have onnx model (custom operator: _DCNv2 added; onnx: 1.9.0, torch: 1.2.0) and Trying to convert to Tensorflow followed by  https://github.com/onnx/onnx-tensorflow installation instruction. But I am having the following error.

onnx_tf: 1.8.0 tensorflow: 2.4.1

- conversion command: onnx-tf convert -i /path/to/input.onnx -o /path/to/output 

Error:
>   File "test_onnx.py", line 8, in <module>
>     tf_rep.export_graph("/home/uib43225/DEFT/src/models/model_mot.pb")
>   File "/home/uib43225/onnx_tf/onnx-tensorflow/onnx_tf/backend_rep.py", line 118, in export_graph
>     signatures=self.tf_module.__call__.get_concrete_function(
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
>     concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
>     self._initialize(args, kwargs, add_initializers_to=initializers)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
>     self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
>     graph_function, _ = self._maybe_define_function(args, kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
>     func_graph_module.func_graph_from_py_func(
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
>     out = weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
>     return wrapped_fn(*args, **kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> onnx.backend.test.runner.BackendIsNotSupposedToImplementIt: in user code:
> 
>     /home/uib43225/onnx_tf/onnx-tensorflow/onnx_tf/backend_tf_module.py:99 __call__  *
>         output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
>     /home/uib43225/onnx_tf/onnx-tensorflow/onnx_tf/backend.py:330 _onnx_node_to_tensorflow_op  *
>         raise BackendIsNotSupposedToImplementIt("{} is not implemented.".format(
> 
>     BackendIsNotSupposedToImplementIt: _DCNv2 is not implemented.

Full Error: Could be the issue with tensorflow installation

> > (test_onnx_tf) (base) uib43225@ozd0073u:~/onnx_check$ python test_onnx.py 
> 
> 2021-07-07 13:05:25.688463: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:25.688498: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
> 2021-07-07 13:05:27.836773: I tensorflow/compiler/jit/xla_cpu_device.cc:41] Not creating XLA devices, tf_xla_enable_xla_devices not set
> 2021-07-07 13:05:27.837763: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcuda.so.1
> 2021-07-07 13:05:27.860918: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:941] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
> 2021-07-07 13:05:27.862011: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1720] Found device 0 with properties: 
> pciBusID: 0000:02:00.0 name: TITAN Xp computeCapability: 6.1
> coreClock: 1.582GHz coreCount: 30 deviceMemorySize: 11.91GiB deviceMemoryBandwidth: 510.07GiB/s
> 2021-07-07 13:05:27.862349: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.862653: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublas.so.11'; dlerror: libcublas.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.862942: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcublasLt.so.11'; dlerror: libcublasLt.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.863229: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcufft.so.10'; dlerror: libcufft.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.863524: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcurand.so.10'; dlerror: libcurand.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.863814: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusolver.so.10'; dlerror: libcusolver.so.10: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.864095: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcusparse.so.11'; dlerror: libcusparse.so.11: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.864558: W tensorflow/stream_executor/platform/default/dso_loader.cc:60] Could not load dynamic library 'libcudnn.so.8'; dlerror: libcudnn.so.8: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
> 2021-07-07 13:05:27.864606: W tensorflow/core/common_runtime/gpu/gpu_device.cc:1757] Cannot dlopen some GPU libraries. Please make sure the missing libraries mentioned above are installed properly if you would like to use GPU. Follow the guide at https://www.tensorflow.org/install/gpu for how to download and setup the required libraries for your platform.
> Skipping registering GPU devices...
> 2021-07-07 13:05:27.865273: I tensorflow/core/platform/cpu_feature_guard.cc:142] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 FMA
> To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
> 2021-07-07 13:05:27.865924: I tensorflow/compiler/jit/xla_gpu_device.cc:99] Not creating XLA devices, tf_xla_enable_xla_devices not set
> 2021-07-07 13:05:27.865976: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1261] Device interconnect StreamExecutor with strength 1 edge matrix:
> 2021-07-07 13:05:27.866010: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1267]      
> Traceback (most recent call last):
>   File "test_onnx.py", line 8, in <module>
>     tf_rep.export_graph("/home/uib43225/DEFT/src/models/model_mot.pb")
>   File "/home/uib43225/onnx_tf/onnx-tensorflow/onnx_tf/backend_rep.py", line 118, in export_graph
>     signatures=self.tf_module.__call__.get_concrete_function(
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1299, in get_concrete_function
>     concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 1205, in _get_concrete_function_garbage_collected
>     self._initialize(args, kwargs, add_initializers_to=initializers)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 725, in _initialize
>     self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 2969, in _get_concrete_function_internal_garbage_collected
>     graph_function, _ = self._maybe_define_function(args, kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3361, in _maybe_define_function
>     graph_function = self._create_graph_function(args, kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3196, in _create_graph_function
>     func_graph_module.func_graph_from_py_func(
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 990, in func_graph_from_py_func
>     func_outputs = python_func(*func_args, **func_kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py", line 634, in wrapped_fn
>     out = weak_wrapped_fn().__wrapped__(*args, **kwds)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/eager/function.py", line 3887, in bound_method_wrapper
>     return wrapped_fn(*args, **kwargs)
>   File "/home/uib43225/test_onnx_tf/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py", line 977, in wrapper
>     raise e.ag_error_metadata.to_exception(e)
> onnx.backend.test.runner.BackendIsNotSupposedToImplementIt: in user code:
> 
>     /home/uib43225/onnx_tf/onnx-tensorflow/onnx_tf/backend_tf_module.py:99 __call__  *
>         output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
>     /home/uib43225/onnx_tf/onnx-tensorflow/onnx_tf/backend.py:330 _onnx_node_to_tensorflow_op  *
>         raise BackendIsNotSupposedToImplementIt("{} is not implemented.".format(
> 
>     BackendIsNotSupposedToImplementIt: _DCNv2 is not implemented.

**Comment by prabhuiitdhn** [comment]
It would be much appreciated If anyone can make me understand this issue. I am okay to modify the code. Thank you.

**Comment by chudegao** [comment]
onnx_tf only support operators in https://github.com/onnx/onnx-tensorflow/blob/master/doc/support_status.md.  _DCNv2 is a custom operator and is not support by onnx-tf.   To support a new operator, please follow https://github.com/onnx/onnx-tensorflow/blob/master/doc/IMPLEMENTING_NEW_OP.md. Hope it can help.

**Comment by prabhuiitdhn** [comment]
Hi @chudegao: Thanks for replying. Yes, I followed the same instructions that you have shared. But still, there is no improvement.

I added a handler to /onnx_tf/handlers/backend/ named as "_DCNv2.py" using:

```
import tensorflow as tf

from onnx_tf.handlers.backend_handler import BackendHandler
from onnx_tf.handlers.handler import onnx_op
from onnx_tf.handlers.handler import tf_func
# from .math_mixin import BasicMathMixin


@onnx_op("_DCNv2")
# @tf.func
class _DCNv2(BackendHandler):

    @classmethod
    def version_9(cls, node, **kwargs):
        return [cls.make_tensor_from_onnx_node(node, **kwargs)]

    @classmethod
    def version_10(cls, node, **kwargs):
        return [cls.make_tensor_from_onnx_node(node, **kwargs)]

```

Executed the command:

> gen_opset.py
> gen_status.py -m.

Please correct me If I am doing wrong. Thank you.

**Comment by chudegao** [comment]
1. First make sure the code you updated is where the onnx_tf are installed.
(chudg) [root@haswell01 onnx_tf]# pip list|grep onnx-tf
onnx-tf                 1.8.0               /chudg/git/onnx-tensorflow
(chudg) [root@haswell01 onnx_tf]# pwd
/chudg/git/onnx-tensorflow/onnx_tf
(chudg) [root@haswell01 onnx_tf]# 

2. After run 'python gen_opset.py .', you should can get patchs as below: 

(chudg) [root@haswell01 onnx_tf]# git diff
diff --git a/onnx_tf/opset_version.py b/onnx_tf/opset_version.py
index 86e9f87..1670e51 100644
--- a/onnx_tf/opset_version.py
+++ b/onnx_tf/opset_version.py
@@ -15,7 +15,6 @@ backend_opset_version = {
     'Atanh': [9],
     'AveragePool': [1, 7, 10, 11],
     'BatchNormalization': [1, 6, 7, 9],
     'Binarizer': [],
     'BitShift': [11],
     'Cast': [1, 6, 9, 13],
@@ -187,7 +186,8 @@ backend_opset_version = {
     'Upsample': [7, 9],
     'Where': [9],
     'Xor': [1, 7],
-    'ZipMap': []
+    'ZipMap': [],
+    '_DCNv2': [9, 10]
 }
 
 backend_partial_support = {
(chudg) [root@haswell01 onnx_tf]# git status
# On branch seqsupport
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   opset_version.py
#
# Untracked files:
#   (use "git add <file>..." to include in what will be committed)
#
#	handlers/backend/_DCNv2.py
no changes added to commit (use "git add" and/or "git commit -a")
(chudg) [root@haswell01 onnx_tf]# 

3. If 1 and 2 are ok, you should can get all handlers as below
(chudg) [root@haswell01 onnx_tf]# python
>>> from onnx_tf.common.handler_helper import get_all_backend_handlers
>>> a=get_all_backend_handlers({})
>>> a['']['_DCNv2']
<class 'onnx_tf.handlers.backend._DCNv2._DCNv2'>

(chudg) [root@haswell01 onnx_tf]# 


I can not debug without the onnx file, if you can provide the onnx file, I can help debug.

**Comment by chudegao** [comment]
I guess you set domain for your custom op. onnx-tf handler should also set same domain as the default domain is ''. Please try to add an attribute for your handler: DOMAIN=xxx. @chinhuang007  seems there's no doc for this. Correct me if I's wrong.

**Comment by chinhuang007** [comment]
Correct. There is no doc for handling custom ops. The domain would be the key to differentiate from an ONNX op since all custom ops will have specific domain names.

**Comment by prabhuiitdhn** [comment]
@chinhuang007: I have followed the same steps but unable to fix it. I am sharing onnx [folder](https://drive.google.com/drive/folders/1jreBSXcD03EsPX2XOczCJEczlJ-6tG1l?usp=sharing) Please check it for debug. I think we are too close to fix it. I am looking for strong support. Thank you for replying.

**Comment by prabhuiitdhn** [comment]
@chudegao Thanks for much more clarification. I am not sure whether I have added DOMAIN or not. This is how I have created a custom operator and added to ONNX and It works on model conversion. Please [find](https://drive.google.com/drive/folders/1jreBSXcD03EsPX2XOczCJEczlJ-6tG1l?usp=sharing) the models here for much more clearance. 

```
class _DCNv2(Function):
    @staticmethod
    def symbolic(g, input, offset, mask, weight, bias, stride, padding, dilation, deformable_groups):
        stride = _pair(stride)
        padding = _pair(padding)
        dilation = _pair(dilation)

        return g.op("custom_domain::_DCNv2", input, offset, mask, weight, bias, stride_i=stride, padding_i=padding,
                    dilation_i=dilation, deformable_groups_i=deformable_groups, )
```

Can you please give more insights that how we add an attribute for handler? Thank you.

**Comment by chudegao** [comment]
I add domain as below:
class _DCNv2(BackendHandler):
    DOMAIN = 'org.pytorch.custom_domain'



I think there are still two issues.

1. onnx-tf issue. it will exlude handlers that defined cumstom domain. After I update as below, the handlers can be included.

(chudg) [root@haswell01 onnx-tensorflow]# git diff
diff --git a/onnx_tf/gen_opset.py b/onnx_tf/gen_opset.py
index 8358b1c..6ebb93e 100755
\--- a/onnx_tf/gen_opset.py
\+++ b/onnx_tf/gen_opset.py
\@@ -20,7 +20,8 @@ def main():
     backend_opset_dict[op_name] = []
 
   backend_onnx_coverage, backend_experimental_op = get_backend_coverage()
\-  backend_opset_dict.update(backend_onnx_coverage.get(defs.ONNX_DOMAIN, {}))
\+  for domain in backend_onnx_coverage.keys():
\+    backend_opset_dict.update(backend_onnx_coverage.get(domain, {}))
   backend_ps_dict = get_backend_partial_support_detail()
 
2. your onnx model issue. The custome domain's opset version is 0(onnx_tf will use 1 by default). It should be 9 or 10 as your operator defined 9 and 10. As a workround I defined version 1 in your operator, it can work now.

>>> model=onnx.load('/root/model_mot.onnx')
>>> model.opset_import
[version: 10
, **domain: "org.pytorch.custom_domain"
version: 0**
]
>>> 


    def version_1(cls, node, **kwargs):
        return [cls.make_tensor_from_onnx_node(node, **kwargs)]

The error will change as below as the tf.func is not defined.
    RuntimeError: No Tensorflow function is given.

**Comment by prabhuiitdhn** [comment]
@chudegao: I added an attribute for handler: DOMAIN = 'org.pytorch.custom_domain' as per you mentioned, and I followed the same [https://github.com/onnx/onnx-tensorflow/blob/master/doc/IMPLEMENTING_NEW_OP.md](steps) to implement new op. But I am still unable to fix it.

This is the modified code:

```
import tensorflow as tf

from onnx_tf.handlers.backend_handler import BackendHandler
from onnx_tf.handlers.handler import onnx_op
from onnx_tf.handlers.handler import tf_func
# from .math_mixin import BasicMathMixin


@onnx_op("_DCNv2")
# @tf.func
class _DCNv2(BackendHandler):
    DOMAIN = 'org.pytorch.custom_domain'

    @classmethod
    def version_1(cls, node, **kwargs):
        return [cls.make_tensor_from_onnx_node(node, **kwargs)]

    @classmethod
    def version_9(cls, node, **kwargs):
        return [cls.make_tensor_from_onnx_node(node, **kwargs)]

    @classmethod
    def version_10(cls, node, **kwargs):
        return [cls.make_tensor_from_onnx_node(node, **kwargs)]
```

After implementing operator I tried to check the status of '_DCNv2' handler and It seems _DCNv2 is not added.

```
>>> import onnx_tf
2021-07-09 19:49:43.199937: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
2021-07-09 19:49:43.199971: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
>>> from onnx_tf.common.handler_helper import get_all_backend_handles
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'get_all_backend_handles' from 'onnx_tf.common.handler_helper' (/home/uib43225/test_onnx/lib/python3.8/site-packages/onnx_tf/common/handler_helper.py)
>>> from onnx_tf.common.handler_helper import get_all_backend_handlers
>>> a = get_all_backend_handlers({})
>>> a['']['_DCNv2']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '_DCNv2'
```

Also, I am wondering If there is an issue with Cuda or version incompatibility:
onnx: 1.9.0
onnx_tf: 1.8.0
protoc: 3.11.3
tensorflow : 2.5.0

Thank you.

**Comment by prabhuiitdhn** [comment]
Hi @chinhuang007: If you debugged the attached model, Please help me to understand and fix the issue. Thank you.

**Comment by prabhuiitdhn** [comment]
Hi @chudegao Will you please help me to fix it? I think we are too close to fix it, We just have to see even after following all the steps correctly why onnx_tensorflow is unable to implement a new operator? After everything running successfully I am still getting this issue.
```

>>> from onnx_tf.common.handler_helper import get_all_backend_handlers
>>> a = get_all_backend_handlers({})
>>> a['']['_DCNv2']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: '_DCNv2'
```

**Comment by chudegao** [comment]
Please use your domain as the key.
>>> a['org.pytorch.custom_domain']
{'_DCNv2': <class 'onnx_tf.handlers.backend._DCNv2._DCNv2'>}
>>>

**Comment by prabhuiitdhn** [comment]
@chudegao: I am not sure whether It has still the same issue. I followed the steps again but no improvement. Do you think it is because of CUDA error?

>>>import onnx_tf
2021-07-09 19:49:43.199937: W tensorflow/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libcudart.so.11.0'; dlerror: libcudart.so.11.0: cannot open shared object file: No such file or directory; LD_LIBRARY_PATH: /usr/local/cuda-10.0/lib64:/usr/local/cuda-10.0/lib
2021-07-09 19:49:43.199971: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.

>>> from onnx_tf.common.handler_helper import get_all_backend_handles
Traceback (most recent call last):
>>> a['org.pytorch.custom_domain']
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
KeyError: 'org.pytorch.custom_domain'

**Comment by chudegao** [comment]
It's not related to cuda.   Please make sure you apply onnx-tf patch I mentioned above.    I submit a PR for this: https://github.com/onnx/onnx-tensorflow/pull/945

**Comment by prabhuiitdhn** [comment]
@chudegao: Thank you for quick reply but Will you please elaborate it? I am unable to understand it.

**Comment by chudegao** [comment]
> @chudegao: Thank you for quick reply but Will you please elaborate it? I am unable to understand it.

onnx-tf have one issue to support custom op with domain name. To fix it, you can apply the patch in pr 945(replice file as https://github.com/onnx/onnx-tensorflow/pull/945/files). Then run "python gen_opset.py . " command to re-generate the opset file(_DCNv2 will be added to opset_version.py).  You should can get the right result.

**Comment by prabhuiitdhn** [comment]
@chudegao: Thank you so much for the clarification. I fixed the issue and Now I am able to see exactly the same:

> a['org.pytorch.custom_domain']
> {'_DCNv2': <class 'onnx_tf.handlers.backend._DCNv2._DCNv2'>}

But how would I fix 'No tensorflow function is given'?

>     /home/uib43225/new_onnx_tf/onnx/onnx-tensorflow/onnx_tf/handlers/backend_handler.py:139 make_tensor_from_onnx_node  *
>         raise RuntimeError("No Tensorflow function is given.")
> 
>     RuntimeError: No Tensorflow function is given.

Do I need to add any tensorflow function as default to fix because there is no function is being called? Or Can I use other function in the place of 'make_tensor_from_onnx_node(node, **kwargs)' to convert .onnx model to .pb successfully?

**Comment by chudegao** [comment]
make_tensor_from_onnx_node is an internal api , it will call tf_fun defined in the handler(where you comment ) to implement the operator. If there's a tensorflow api you can leverage for your custom op, you can use it(most operator use this, you can reference. e.g. add.py). Otherwise you can implement the op by youself(you can reference hardswish.py).

**Comment by prabhuiitdhn** [comment]
@chudegao: Thank you so much for your support, Yes, we did it, Hurray. Much appreciated.

**Comment by chudegao** [comment]
> @chudegao: Thank you so much for your support, Yes, we did it, Hurray. Much appreciated.

You are welcome.

**Comment by philip-fu** [comment]
Hi @prabhuiitdhn , could you share the op you defined? thanks!
