### ISSUE TITLE
Questions about the files generated by onnx2tf

### ISSUE THREAD

**Issue by Zengyf-CVer** [onnx/onnx-tensorflow#947]
@chinhuang007 

Hello,I used the following code:
```shell
onnx-tf convert -i ./weight/yolov5s.onnx -o ./weight/onnx2pb/yolov5s.pb
```
But what is generated is a saved_model type folder, not a pb file, as shown in the figure:
![ksnip_20210717-150320](https://user-images.githubusercontent.com/41098760/126029001-b3a5d6ab-c296-41fc-9fad-94a5b8c84080.png)
![ksnip_20210717-150329](https://user-images.githubusercontent.com/41098760/126029002-9864e197-8473-46f5-857b-34c4164c3900.png)
I want to generate this kind of pb file, as shown in the figure:
![ksnip_20210717-150455](https://user-images.githubusercontent.com/41098760/126029046-af806e0a-9ba7-45fa-bc27-a010bf080a02.png)
#### What instructions should be executed? Thank you.
My related configuration:
- tensorflow:2.4.1
- onnx-tf:1.8.0
- tensorflow-addons:0.13.0
- python:3.8

**Comment by chinhuang007** [comment]
Sorry for the late reply... The current exported model is a TF saved model, not a pb with computational graph because the direct use of graph is not recommended since TF 2.0. We could look into an option to also produce a graph pb if resources permit.

**Comment by Zengyf-CVer** [comment]
@chinhuang007
Thank you very much for your reply.
