### ISSUE TITLE
ValueError: Dimensions must be equal, but are 32 and 8 for '{{node Add_4}} = Add[T=DT_FLOAT](concat_4/concat, Add_4/y)' with input shapes: [?,51,8,32], [8].

### ISSUE THREAD

**Issue by nikhiltiru** [onnx/onnx-tensorflow#951]
**Describe the bug**

Cannot convert onnx model to Tensorflow.

Converted PyTorch model to onnx.
Checked that onnx model works using onnxruntime
Converting from onnx to Intel OpenVino also works.
But converting to TensorFlow fails.

**To Reproduce**

```
import onnx
import onnx_tf

onnx_path = 'float_model.onnx'
onnx_model = onnx.load(onnx_path)
tf_rep = onnx_tf.backend.prepare(onnx_model)
tf_rep.export_graph("model.tf")
```

**ONNX model file**

https://drive.google.com/file/d/1zax7qCOxF0dCQ2VYOwyF1kG_eCpn6sk7/view?usp=sharing

**PyTorch model file**

https://drive.google.com/file/d/1UIKKECuanMlb0ilxvPNn_MrUNI-wSpyf/view?usp=sharing

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.8.2 [GCC 8.3.0]
 - ONNX version: 1.9.0
 - ONNX-TF version: 1.8.0
 - Tensorflow version: 2.5.0

**Additional context**

Stack Trace
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/tmp/ipykernel_14490/269763652.py in <module>
      5 onnx_model = onnx.load(onnx_path)
      6 tf_rep = onnx_tf.backend.prepare(onnx_model)
----> 7 tf_rep.export_graph("model.tf")

~/.local/lib/python3.8/site-packages/onnx_tf/backend_rep.py in export_graph(self, path)
    113         self.tf_module,
    114         path,
--> 115         signatures=self.tf_module.__call__.get_concrete_function(
    116             **self.signatures))

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in get_concrete_function(self, *args, **kwargs)
   1365       ValueError: if this object has not yet been called on concrete values.
   1366     """
-> 1367     concrete = self._get_concrete_function_garbage_collected(*args, **kwargs)
   1368     concrete._garbage_collector.release()  # pylint: disable=protected-access
   1369     return concrete

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _get_concrete_function_garbage_collected(self, *args, **kwargs)
   1271       if self._stateful_fn is None:
   1272         initializers = []
-> 1273         self._initialize(args, kwargs, add_initializers_to=initializers)
   1274         self._initialize_uninitialized_variables(initializers)
   1275 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    761     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    762     self._concrete_stateful_fn = (
--> 763         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    764             *args, **kwds))
    765 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   3048       args, kwargs = None, None
   3049     with self._lock:
-> 3050       graph_function, _ = self._maybe_define_function(args, kwargs)
   3051     return graph_function
   3052 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3442 
   3443           self._function_cache.missed.add(call_context_key)
-> 3444           graph_function = self._create_graph_function(args, kwargs)
   3445           self._function_cache.primary[cache_key] = graph_function
   3446 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3277     arg_names = base_arg_names + missing_arg_names
   3278     graph_function = ConcreteFunction(
-> 3279         func_graph_module.func_graph_from_py_func(
   3280             self._name,
   3281             self._python_function,

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes)
    997         _, original_func = tf_decorator.unwrap(python_func)
    998 
--> 999       func_outputs = python_func(*func_args, **func_kwargs)
   1000 
   1001       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    670         # the function a weak reference to itself to avoid a reference cycle.
    671         with OptionalXlaContext(compile_with_xla):
--> 672           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    673         return out
    674 

~/.local/lib/python3.8/site-packages/tensorflow/python/eager/function.py in bound_method_wrapper(*args, **kwargs)
   3969     # However, the replacer is still responsible for attaching self properly.
   3970     # TODO(mdan): Is it possible to do it here instead?
-> 3971     return wrapped_fn(*args, **kwargs)
   3972   weak_bound_method_wrapper = weakref.ref(bound_method_wrapper)
   3973 

~/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    984           except Exception as e:  # pylint:disable=broad-except
    985             if hasattr(e, "ag_error_metadata"):
--> 986               raise e.ag_error_metadata.to_exception(e)
    987             else:
    988               raise

ValueError: in user code:

    /home/ubuntu/.local/lib/python3.8/site-packages/onnx_tf/backend_tf_module.py:98 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /home/ubuntu/.local/lib/python3.8/site-packages/onnx_tf/backend.py:328 _onnx_node_to_tensorflow_op  *
        return handler.handle(node, tensor_dict=tensor_dict, strict=strict)
    /home/ubuntu/.local/lib/python3.8/site-packages/onnx_tf/handlers/handler.py:59 handle  *
        return ver_handle(node, **kwargs)
    /home/ubuntu/.local/lib/python3.8/site-packages/onnx_tf/handlers/backend/conv.py:15 version_11  *
        return cls.conv(node, kwargs["tensor_dict"])
    /home/ubuntu/.local/lib/python3.8/site-packages/onnx_tf/handlers/backend/conv_mixin.py:308 conv  *
        output = tf.add(output, bias)
    /home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py:395 add  **
        _, _, _op, _outputs = _op_def_library._apply_op_helper(
    /home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py:748 _apply_op_helper
        op = g._create_op_internal(op_type_name, inputs, dtypes=None,
    /home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py:599 _create_op_internal
        return super(FuncGraph, self)._create_op_internal(  # pylint: disable=protected-access
    /home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:3557 _create_op_internal
        ret = Operation(
    /home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:2041 __init__
        self._c_op = _create_c_op(self._graph, node_def, inputs,
    /home/ubuntu/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py:1883 _create_c_op
        raise ValueError(str(e))

    ValueError: Dimensions must be equal, but are 32 and 8 for '{{node Add_4}} = Add[T=DT_FLOAT](concat_4/concat, Add_4/y)' with input shapes: [?,51,8,32], [8].

**Comment by chudegao** [comment]
It's caused the input shape has unknown value. onnx-tf does support export graph for such input even it can run inference with tf_rep.run(input).  To workround the issue, when convert pytorch model to onnx, set a fixed input size or modify the tf_rep's signatures or onnx model's input before export tf model.  We will see how to enhance onnx-tf. Welcome your comments or contribution.

>>> onnx_model.graph.input
[name: "input"
type {
  tensor_type {
    elem_type: 1
    shape {
      dim {
        dim_param: "batch_size"
      }
      dim {
        dim_value: 1
      }
      dim {
        dim_value: 156
      }
      dim {
        dim_value: 26
      }
    }
  }
}
>>> tf_rep.signatures
{'input': TensorSpec(shape=(None, 1, 156, 26), dtype=tf.float32, name='input')}
>>>
>>> import tensorflow as tf
>>> tf_rep.signatures['input']=tf.TensorSpec(shape=(1, 1, 156, 26),dtype=tf.float32, name='input')
>>> tf_rep.export_graph("model.tf")
2021-07-21 14:18:26.797558: W tensorflow/python/util/util.cc:348] Sets are not currently considered sequences, but this may change in the future, so consider avoiding using them.
INFO:tensorflow:Assets written to: model.tf/assets
>>> 
]
>>>

**Comment by nikhiltiru** [comment]
OK, let me try to set a fixed input size and check.

And by the way, I am happy to take this up and contribute. But I am new to this, let me know where I can learn more and contribute.
Or if you have already started working, its ok.
Sorry for the late reply.

**Comment by chudegao** [comment]
@nikhiltiru I submit a pr for this issue. It still need review. You can try with your original model.

**Comment by chudegao** [comment]
@nikhiltiru please verify with latest build.

**Comment by chinhuang007** [comment]
Assume issue is fixed. Please reopen if not the case.
