### ISSUE TITLE
Please verify ONNX v1.10.0 Release Candidate

### ISSUE THREAD

**Issue by rajeevsrao** [onnx/onnx-tensorflow#952]
Hello ONNX partner,
We have published (to TestPyPI) a Release Candidate package for the upcoming ONNX v1.10.0 release. Please help validate it and let us know if you encounter any issues. Note that the tentative release date for ONNX v1.10.0 is July 31, 2021. Thank you for your assistance!

```
pip install numpy protobuf typing-extensions>=3.6.2.1
pip install -i https://test.pypi.org/simple/ onnx==1.9.101
```

* 07/26/2021: RC2 with `make_sequence_value_info` alias - [onnx 1.9.101](https://test.pypi.org/project/onnx/1.9.101/)
* 07/21/2021: RC1 for validation - [onnx 1.9.100](https://test.pypi.org/project/onnx/1.9.100/)

cc @chinhuang007 @tjingrant

**Comment by chinhuang007** [comment]
@rajeevsrao I just ran basic tests and everything looks good!

**Comment by rajeevsrao** [comment]
@chinhuang007 thanks for confirming. FYI we found a few issues when testing other packages (looks like onnx_tf didn't trip on those) - will post an updated test wheel.
