### ISSUE TITLE
Onnx -> pb -> tflite Conversion Issue

### ISSUE THREAD

**Issue by JunHyunjae** [onnx/onnx-tensorflow#963]
**Describe the bug**

An error occurred when running after onnx -> pb -> tflite conversion.

**To Reproduce**

# onnx -> pb

onnx_model = onnx.load("./onnx_resnet/resnet50-v1-7.onnx")
tf_model_path = "./onnx_resnet/tf_2.2.0/tflite/saved_model"
tf_rep = prepare(onnx_model)
tf_rep.export_graph(tf_model_path)

# pb -> tflite

def representative_data_gen():

    a = []
    datapath = "/MSCOCO/images/test2017"
    file_list = os.listdir(datapath)
    pixel_mean = (0.485, 0.456, 0.406)
    pixel_std = (0.229, 0.224, 0.225)

    for i in range(100):
        file_name = file_list[i]
        img = cv2.imread(os.path.join(datapath, file_list[i]))
        img = cv2.resize(img, (224, 224))        
        img = (img - pixel_mean) / pixel_std
        img = img.astype(np.float32)
        a.append(img)
    a = np.array(a)
    img = tf.data.Dataset.from_tensor_slices(a).batch(1)
    for i in img.take(1):
        yield [i]

tf_model_path = "./onnx_resnet/tf_2.2.0/tflite/saved_model"
tflite_model_path = "./tensorflow_resnet/tf.2.2.0/tflite/resnet_int8.tflite"

converter = tf.lite.TFLiteConverter.from_saved_model(tf_model_path)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.representative_dataset=representative_data_gen
tflite_model = converter.convert()

with open(tflite_model_path, 'wb') as f:
    f.write(tflite_model)

**ONNX model file**

https://github.com/onnx/models/blob/master/vision/classification/resnet/model/resnet50-v1-7.onnx

**Python, ONNX, ONNX-TF, Tensorflow version**

This section can be obtained by running `get_version.py` from util folder.
 - Python version: 3.6.9
 - ONNX version: 1.7.0
 - ONNX-TF version: 1.7.0
 - Tensorflow version: 2.2.0

**Additional context**

# TFlite Test Code
interpreter = tf.lite.Interpreter(model_path="./tensorflow_resnet/tf.2.2.0/tflite/resnet_int8.tflite")
interpreter.allocate_tensors()

# Error Log
RuntimeError: tensorflow/lite/kernels/pad.cc:106 op_context.input->type != op_context.constant_values->type (9 != 1)Node number 7 (PADV2) failed to prepare.

# Added experiment
As shown in the code below, downloading and converting tensorflow models works well.
Onnx -> pb -> tflite is a problem.
Is it a matter of onnx?

from tensorflow.keras.applications.resnet50 import ResNet50
model = ResNet50(weights='imagenet')
saved_model_path = "./tensorflow_resnet/tf.2.2.0/"
tf.keras.models.save_model(model, saved_model_path)
converter = tf.lite.TFLiteConverter.from_saved_model(saved_model_path)
converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
converter.optimizations = [tf.lite.Optimize.DEFAULT]
converter.representative_dataset = representative_data_gen
tflite_model = converter.convert()

**Comment by chinhuang007** [comment]
@JunHyunjae your code works fine in my env, which includes the following:
ONNX version:
1.10.1
ONNX-TF version:
1.8.0
Tensorflow version:
2.5.0
Since the onnx to tensorflow conversion is successful for you, I think the error is coming from tensorflow 2.2. Maybe you could upgrade to 2.5 and see if it helps.

**Comment by JunHyunjae** [comment]
@chinhuang007 
Thanks, Successful conversion was confirmed in TF 2.5.0.
