### ISSUE TITLE
BackendIsNotSupposedToImplementIt: AliasWithName is not implemented.

### ISSUE THREAD

**Issue by mountassir-el** [onnx/onnx-tensorflow#982]
Hi, 

I exported a simple functioning detectron2 model as a model.onnx file, then i tried to call the model using tensorflow.
whenever i try to execute this block of code : 
```
import onnx
from onnx_tf.backend import prepare
img = tf.keras.preprocessing.image.img_to_array(img)
onnx_model = onnx.load("./model.onnx")  # load onnx model
output = prepare(onnx_model).run(input)
```

i run into the following error : 

```
---------------------------------------------------------------------------
BackendIsNotSupposedToImplementIt         Traceback (most recent call last)
/tmp/ipykernel_30690/645701867.py in <module>
----> 1 output = prepare(onnx_model).run(img)# run the loaded model

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/onnx_tf/backend_rep.py in run(self, inputs, **kwargs)
    105         input_dict[k] = tf.constant(v)
    106 
--> 107     output_values = self.tf_module(**input_dict)
    108 
    109     o_values = []

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
    883 
    884       with OptionalXlaContext(self._jit_compile):
--> 885         result = self._call(*args, **kwds)
    886 
    887       new_tracing_count = self.experimental_get_tracing_count()

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
    931       # This is the first call of __call__, so we have to initialize.
    932       initializers = []
--> 933       self._initialize(args, kwds, add_initializers_to=initializers)
    934     finally:
    935       # At this point we know that the initialization is complete (or less

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
    757     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
    758     self._concrete_stateful_fn = (
--> 759         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
    760             *args, **kwds))
    761 

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
   3064       args, kwargs = None, None
   3065     with self._lock:
-> 3066       graph_function, _ = self._maybe_define_function(args, kwargs)
   3067     return graph_function
   3068 

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
   3461 
   3462           self._function_cache.missed.add(call_context_key)
-> 3463           graph_function = self._create_graph_function(args, kwargs)
   3464           self._function_cache.primary[cache_key] = graph_function
   3465 

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
   3296     arg_names = base_arg_names + missing_arg_names
   3297     graph_function = ConcreteFunction(
-> 3298         func_graph_module.func_graph_from_py_func(
   3299             self._name,
   3300             self._python_function,

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes, acd_record_initial_resource_uses)
   1005         _, original_func = tf_decorator.unwrap(python_func)
   1006 
-> 1007       func_outputs = python_func(*func_args, **func_kwargs)
   1008 
   1009       # invariant: `func_outputs` contains only Tensors, CompositeTensors,

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
    666         # the function a weak reference to itself to avoid a reference cycle.
    667         with OptionalXlaContext(compile_with_xla):
--> 668           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
    669         return out
    670 

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in bound_method_wrapper(*args, **kwargs)
   3988     # However, the replacer is still responsible for attaching self properly.
   3989     # TODO(mdan): Is it possible to do it here instead?
-> 3990     return wrapped_fn(*args, **kwargs)
   3991   weak_bound_method_wrapper = weakref.ref(bound_method_wrapper)
   3992 

~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
    992           except Exception as e:  # pylint:disable=broad-except
    993             if hasattr(e, "ag_error_metadata"):
--> 994               raise e.ag_error_metadata.to_exception(e)
    995             else:
    996               raise

BackendIsNotSupposedToImplementIt: in user code:

    /home/n7student/anaconda3/envs/detectron2/lib/python3.8/site-packages/onnx_tf/backend_tf_module.py:99 __call__  *
        output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
    /home/n7student/anaconda3/envs/detectron2/lib/python3.8/site-packages/onnx_tf/backend.py:349 _onnx_node_to_tensorflow_op  *
        raise BackendIsNotSupposedToImplementIt("{} is not implemented.".format(

    BackendIsNotSupposedToImplementIt: AliasWithName is not implemented.

```

What is the problem here ? and how can i solve it please ?
I thank you in advance !

**Comment by MadhuriPatil1694** [comment]
> Hi,
> 
> I exported a simple functioning detectron2 model as a model.onnx file, then i tried to call the model using tensorflow. whenever i try to execute this block of code :
> 
> ```
> import onnx
> from onnx_tf.backend import prepare
> img = tf.keras.preprocessing.image.img_to_array(img)
> onnx_model = onnx.load("./model.onnx")  # load onnx model
> output = prepare(onnx_model).run(input)
> ```
> 
> i run into the following error :
> 
> ```
> ---------------------------------------------------------------------------
> BackendIsNotSupposedToImplementIt         Traceback (most recent call last)
> /tmp/ipykernel_30690/645701867.py in <module>
> ----> 1 output = prepare(onnx_model).run(img)# run the loaded model
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/onnx_tf/backend_rep.py in run(self, inputs, **kwargs)
>     105         input_dict[k] = tf.constant(v)
>     106 
> --> 107     output_values = self.tf_module(**input_dict)
>     108 
>     109     o_values = []
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in __call__(self, *args, **kwds)
>     883 
>     884       with OptionalXlaContext(self._jit_compile):
> --> 885         result = self._call(*args, **kwds)
>     886 
>     887       new_tracing_count = self.experimental_get_tracing_count()
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _call(self, *args, **kwds)
>     931       # This is the first call of __call__, so we have to initialize.
>     932       initializers = []
> --> 933       self._initialize(args, kwds, add_initializers_to=initializers)
>     934     finally:
>     935       # At this point we know that the initialization is complete (or less
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in _initialize(self, args, kwds, add_initializers_to)
>     757     self._graph_deleter = FunctionDeleter(self._lifted_initializer_graph)
>     758     self._concrete_stateful_fn = (
> --> 759         self._stateful_fn._get_concrete_function_internal_garbage_collected(  # pylint: disable=protected-access
>     760             *args, **kwds))
>     761 
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _get_concrete_function_internal_garbage_collected(self, *args, **kwargs)
>    3064       args, kwargs = None, None
>    3065     with self._lock:
> -> 3066       graph_function, _ = self._maybe_define_function(args, kwargs)
>    3067     return graph_function
>    3068 
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _maybe_define_function(self, args, kwargs)
>    3461 
>    3462           self._function_cache.missed.add(call_context_key)
> -> 3463           graph_function = self._create_graph_function(args, kwargs)
>    3464           self._function_cache.primary[cache_key] = graph_function
>    3465 
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in _create_graph_function(self, args, kwargs, override_flat_arg_shapes)
>    3296     arg_names = base_arg_names + missing_arg_names
>    3297     graph_function = ConcreteFunction(
> -> 3298         func_graph_module.func_graph_from_py_func(
>    3299             self._name,
>    3300             self._python_function,
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in func_graph_from_py_func(name, python_func, args, kwargs, signature, func_graph, autograph, autograph_options, add_control_dependencies, arg_names, op_return_value, collections, capture_by_value, override_flat_arg_shapes, acd_record_initial_resource_uses)
>    1005         _, original_func = tf_decorator.unwrap(python_func)
>    1006 
> -> 1007       func_outputs = python_func(*func_args, **func_kwargs)
>    1008 
>    1009       # invariant: `func_outputs` contains only Tensors, CompositeTensors,
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/def_function.py in wrapped_fn(*args, **kwds)
>     666         # the function a weak reference to itself to avoid a reference cycle.
>     667         with OptionalXlaContext(compile_with_xla):
> --> 668           out = weak_wrapped_fn().__wrapped__(*args, **kwds)
>     669         return out
>     670 
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/eager/function.py in bound_method_wrapper(*args, **kwargs)
>    3988     # However, the replacer is still responsible for attaching self properly.
>    3989     # TODO(mdan): Is it possible to do it here instead?
> -> 3990     return wrapped_fn(*args, **kwargs)
>    3991   weak_bound_method_wrapper = weakref.ref(bound_method_wrapper)
>    3992 
> 
> ~/anaconda3/envs/detectron2/lib/python3.8/site-packages/tensorflow/python/framework/func_graph.py in wrapper(*args, **kwargs)
>     992           except Exception as e:  # pylint:disable=broad-except
>     993             if hasattr(e, "ag_error_metadata"):
> --> 994               raise e.ag_error_metadata.to_exception(e)
>     995             else:
>     996               raise
> 
> BackendIsNotSupposedToImplementIt: in user code:
> 
>     /home/n7student/anaconda3/envs/detectron2/lib/python3.8/site-packages/onnx_tf/backend_tf_module.py:99 __call__  *
>         output_ops = self.backend._onnx_node_to_tensorflow_op(onnx_node,
>     /home/n7student/anaconda3/envs/detectron2/lib/python3.8/site-packages/onnx_tf/backend.py:349 _onnx_node_to_tensorflow_op  *
>         raise BackendIsNotSupposedToImplementIt("{} is not implemented.".format(
> 
>     BackendIsNotSupposedToImplementIt: AliasWithName is not implemented.
> ```
> 
> What is the problem here ? and how can i solve it please ? I thank you in advance !

I am also facing the same issue did you find the solution

**Comment by MadhuriPatil1694** [comment]
@mountassir-el  I found the reason. You might have saved the onnx model using onnx.save, but somehow this model format is not supported by  onnx_tf.backend.prepare. So I tried using  torch.onnx.export with opset version 11 and then it worked.

**Comment by mountassir-el** [comment]
@MadhuriPatil1694 Hi, I actually didn't find a way to solve it by that time.
Thank you so much, I appreciate your response it means a lot !
